c-------------------------------------------------
c                                                 
c                                                 
c                              -USAGE-            
c                                                 
c     OVERVIEW: call pmf_H     (xlo,xhi,y,Niny)   
c     computes y(xlo,xhi) by averaging data over  
c     the range [xlo,xhi]. Here x is a scalar, y  
c     a vector, with Niny components used. Piece- 
c     constant Extrapolation is applied to points 
c     laying outside the range of the orig data   
c                                                 
c     domain: x in [-0.20000E+01, 0.20000E+01]  
c     number of states in vector y:    12         
c     number of x data points:    89              
c                                                 
c     CALLING PROGRAM NEEDS: none                 
c     PROCEDURE NEEDS:  none                      
c     COMPILER NEEDS: f77, long names (14 char)   
c     SYSTEM NEEDS: none                          
c     NOTES: This routine was generated by        
c     subroutine makeRoutine.                     
c                                                 
c-------------------------------------------------
c                                                 
c                          -SPECIFICATION-        
c     SYNTAX:                                     
c     subroutine pmf_H     (xlo,xhi:dp,y:dp arr, Niny: int)
c     returns: none                               
c     REQUIRES: none                              
c     MODIFIES: y, N                              
c     SIGNALS: none                               
c     EFFECTS: computes the average value of y    
c     over the range [xlo,xhi] and returns number 
c     of components used, N.                      
c                                                 
c-------------------------------------------------
c                                                 
c                         -IMPLEMENTATION-        
c     AUTHOR: auto-generated by makeAveInterp     
c     MODIFICATION HISTORY: none                  
c     NOTES: interpolation x,y data is defined in 
c     data statements for efficiency.             
c     REQUIRES: none                              
c     LOCAL VARIABLES:                            
c     xlo,xhi.........(dp) average y on this range
c     y_vector........(1D dp arr) computed y(x)   
c     Niny............(int) no. of used components
c     x_data..........(dp) x data points          
c     y_data..........(dp) y(x) data points       
c     N...............(int) number of x points    
c     M...............(int) dimension of y_data   
c     i,j,k...........(int) loop index            
c     lo_{lo,hi}side..(int) idx of data near xlo  
c     hi_{lo,hi}side..(int) idx of data near xhi  
c     x1..............(dp) interpolation point    
c     x2..............(dp) interpolation point    
c     y1..............(dp) interpolation value    
c     y2..............(dp) interpolation value    
c     dydx............(dp) slope of linear interp 
c     ylo.............(dp) value at xlo           
c     yhi.............(dp) value at xhi           
c     GLOBAL VARIABLES:none                       
c     PROCEDURES: none                            
c     FILES: none                                 
c     I/O: none                                   
c-------------------------------------------------
c                                                 
c                             -CODE-              
c     FIRST LINE:                                 
      subroutine pmf_H     (xlo,xhi,y_vector,Niny)
c                                                 

c                                                 
      integer N,M,i,j,k,lo_loside,lo_hiside       
      integer hi_loside,hi_hiside,Niny            
      double precision xlo,xhi,y_vector(*),sum    
      double precision ylo,yhi,x1,y1,x2,y2,dydx   
      double precision x_data(    89)              
      double precision y_data(    89,    12)        
      data N,M /    89,    12/                   
      Niny =     12                                
c                                                 
c     interpolation x,y data                      
c                                                 
      data x_data(     1     ) /  -0.200000000000D+01/
      data y_data(     1,   1) /   0.298000000000D+03/
      data y_data(     1,   2) /   0.267301130638D+01/
      data y_data(     1,   3) /   0.105715559218D-02/
      data y_data(     1,   4) /   0.111776630392D+00/
      data y_data(     1,   5) /   0.258465674864D-27/
      data y_data(     1,   6) /   0.773777825252D-24/
      data y_data(     1,   7) /   0.186526497426D+00/
      data y_data(     1,   8) /   0.105024923356D-26/
      data y_data(     1,   9) /   0.118009100659D-07/
      data y_data(     1,  10) /   0.840890483070D-13/
      data y_data(     1,  11) /   0.306377685259D-11/
      data y_data(     1,  12) /   0.701696860379D+00/
      data x_data(     2     ) /  -0.180000000000D+01/
      data y_data(     2,   1) /   0.298000673883D+03/
      data y_data(     2,   2) /   0.267279131056D+01/
      data y_data(     2,   3) /   0.105724260602D-02/
      data y_data(     2,   4) /   0.111695108082D+00/
      data y_data(     2,   5) /   0.439092709985D-27/
      data y_data(     2,   6) /   0.195003062617D-23/
      data y_data(     2,   7) /   0.186543338460D+00/
      data y_data(     2,   8) /   0.267761414435D-26/
      data y_data(     2,   9) /   0.376907931259D-07/
      data y_data(     2,  10) /   0.284539428267D-12/
      data y_data(     2,  11) /   0.104165606242D-10/
      data y_data(     2,  12) /   0.701761515757D+00/
      data x_data(     3     ) /  -0.140000000000D+01/
      data y_data(     3,   1) /   0.298005526431D+03/
      data y_data(     3,   2) /   0.267193696384D+01/
      data y_data(     3,   3) /   0.105758065731D-02/
      data y_data(     3,   4) /   0.111371104751D+00/
      data y_data(     3,   5) /  -0.435281110081D-22/
      data y_data(     3,   6) /   0.246329662782D-22/
      data y_data(     3,   7) /   0.186610217993D+00/
      data y_data(     3,   8) /   0.311362165904D-25/
      data y_data(     3,   9) /   0.259905577809D-06/
      data y_data(     3,  10) /   0.211873314012D-11/
      data y_data(     3,  11) /   0.780724855644D-10/
      data y_data(     3,  12) /   0.702018417270D+00/
      data x_data(     4     ) /  -0.100000000000D+01/
      data y_data(     4,   1) /   0.298027237993D+03/
      data y_data(     4,   2) /   0.267005438048D+01/
      data y_data(     4,   3) /   0.105832632892D-02/
      data y_data(     4,   4) /   0.110620434983D+00/
      data y_data(     4,   5) /  -0.441473994326D-25/
      data y_data(     4,   6) /   0.368156437939D-21/
      data y_data(     4,   7) /   0.186764883832D+00/
      data y_data(     4,   8) /  -0.195805470898D-22/
      data y_data(     4,   9) /   0.145768919982D-05/
      data y_data(     4,  10) /   0.126989338224D-10/
      data y_data(     4,  11) /   0.470661966063D-09/
      data y_data(     4,  12) /   0.702613223012D+00/
      data x_data(     5     ) /  -0.600000000000D+00/
      data y_data(     5,   1) /   0.298124709382D+03/
      data y_data(     5,   2) /   0.266612778740D+01/
      data y_data(     5,   3) /   0.105988500021D-02/
      data y_data(     5,   4) /   0.108880394164D+00/
      data y_data(     5,   5) /   0.211586662005D-25/
      data y_data(     5,   6) /   0.544508973611D-20/
      data y_data(     5,   7) /   0.187121996159D+00/
      data y_data(     5,   8) /   0.750478135654D-23/
      data y_data(     5,   9) /   0.791724642059D-05/
      data y_data(     5,  10) /   0.737897187651D-10/
      data y_data(     5,  11) /   0.275011320205D-08/
      data y_data(     5,  12) /   0.703989689606D+00/
      data x_data(     6     ) /  -0.400000000000D+00/
      data y_data(     6,   1) /   0.298301763150D+03/
      data y_data(     6,   2) /   0.266296194963D+01/
      data y_data(     6,   3) /   0.106114503473D-02/
      data y_data(     6,   4) /   0.107150371648D+00/
      data y_data(     6,   5) /   0.245417264638D-24/
      data y_data(     6,   6) /   0.343476335596D-19/
      data y_data(     6,   7) /   0.187474336844D+00/
      data y_data(     6,   8) /   0.478350826575D-22/
      data y_data(     6,   9) /   0.217823060669D-04/
      data y_data(     6,  10) /   0.213877514299D-09/
      data y_data(     6,  11) /   0.799643426981D-08/
      data y_data(     6,  12) /   0.705353500991D+00/
      data x_data(     7     ) /  -0.300000000000D+00/
      data y_data(     7,   1) /   0.298507248727D+03/
      data y_data(     7,   2) /   0.266126741305D+01/
      data y_data(     7,   3) /   0.106182070868D-02/
      data y_data(     7,   4) /   0.105858346400D+00/
      data y_data(     7,   5) /   0.693952521374D-24/
      data y_data(     7,   6) /   0.975994439151D-19/
      data y_data(     7,   7) /   0.187734558576D+00/
      data y_data(     7,   8) /   0.137490252352D-21/
      data y_data(     7,   9) /   0.401117104909D-04/
      data y_data(     7,  10) /   0.409605586805D-09/
      data y_data(     7,  11) /   0.153393250982D-07/
      data y_data(     7,  12) /   0.706366967565D+00/
      data x_data(     8     ) /  -0.200000000000D+00/
      data y_data(     8,   1) /   0.298894341404D+03/
      data y_data(     8,   2) /   0.266005457123D+01/
      data y_data(     8,   3) /   0.106230484181D-02/
      data y_data(     8,   4) /   0.104141703001D+00/
      data y_data(     8,   5) /   0.193593148227D-23/
      data y_data(     8,   6) /   0.270324055999D-18/
      data y_data(     8,   7) /   0.188075098302D+00/
      data y_data(     8,   8) /   0.389891647000D-21/
      data y_data(     8,   9) /   0.785035497582D-04/
      data y_data(     8,  10) /   0.839567348858D-09/
      data y_data(     8,  11) /   0.314820914500D-07/
      data y_data(     8,  12) /   0.707704662825D+00/
      data x_data(     9     ) /  -0.100000000000D+00/
      data y_data(     9,   1) /   0.299625336238D+03/
      data y_data(     9,   2) /   0.266041120843D+01/
      data y_data(     9,   3) /   0.106216243623D-02/
      data y_data(     9,   4) /   0.101862074301D+00/
      data y_data(     9,   5) /   0.550504296375D-23/
      data y_data(     9,   6) /   0.746614544718D-18/
      data y_data(     9,   7) /   0.188516263662D+00/
      data y_data(     9,   8) /   0.112969911509D-20/
      data y_data(     9,   9) /   0.158831703166D-03/
      data y_data(     9,  10) /   0.178586117294D-08/
      data y_data(     9,  11) /   0.669437035754D-07/
      data y_data(     9,  12) /   0.709462761604D+00/
      data x_data(    10     ) /   0.000000000000D+00/
      data y_data(    10,   1) /   0.301009570594D+03/
      data y_data(    10,   2) /   0.266462363711D+01/
      data y_data(    10,   3) /   0.106048329346D-02/
      data y_data(    10,   4) /   0.988382840428D-01/
      data y_data(    10,   5) /   0.164702900695D-22/
      data y_data(    10,   6) /   0.207802827752D-17/
      data y_data(    10,   7) /   0.189077887000D+00/
      data y_data(    10,   8) /   0.345625753751D-20/
      data y_data(    10,   9) /   0.326529452452D-03/
      data y_data(    10,  10) /   0.387697959356D-08/
      data y_data(    10,  11) /   0.144711736935D-06/
      data y_data(    10,  12) /   0.711757150917D+00/
      data x_data(    11     ) /   0.162500000000D+00/
      data y_data(    11,   1) /   0.305917030925D+03/
      data y_data(    11,   2) /   0.268958493291D+01/
      data y_data(    11,   3) /   0.105064124056D-02/
      data y_data(    11,   4) /   0.918450847798D-01/
      data y_data(    11,   5) /   0.830438002022D-22/
      data y_data(    11,   6) /   0.956915206217D-17/
      data y_data(    11,   7) /   0.190270383767D+00/
      data y_data(    11,   8) /   0.214809918953D-19/
      data y_data(    11,   9) /   0.983858439883D-03/
      data y_data(    11,  10) /   0.127514263397D-07/
      data y_data(    11,  11) /   0.467499488107D-06/
      data y_data(    11,  12) /   0.716900192763D+00/
      data x_data(    12     ) /   0.243750000000D+00/
      data y_data(    12,   1) /   0.311083915977D+03/
      data y_data(    12,   2) /   0.272251033819D+01/
      data y_data(    12,   3) /   0.103793503036D-02/
      data y_data(    12,   4) /   0.870063694207D-01/
      data y_data(    12,   5) /   0.369371363435D-21/
      data y_data(    12,   6) /   0.259415835526D-16/
      data y_data(    12,   7) /   0.190974277024D+00/
      data y_data(    12,   8) /   0.758141076849D-19/
      data y_data(    12,   9) /   0.173374054712D-02/
      data y_data(    12,  10) /   0.244923590592D-07/
      data y_data(    12,  11) /   0.857354148217D-06/
      data y_data(    12,  12) /   0.720284731162D+00/
      data x_data(    13     ) /   0.325000000000D+00/
      data y_data(    13,   1) /   0.320018489021D+03/
      data y_data(    13,   2) /   0.278540274847D+01/
      data y_data(    13,   3) /   0.101449919659D-02/
      data y_data(    13,   4) /   0.809878927840D-01/
      data y_data(    13,   5) /   0.168694201727D-20/
      data y_data(    13,   6) /   0.740288504461D-16/
      data y_data(    13,   7) /   0.191662368207D+00/
      data y_data(    13,   8) /   0.304961377360D-18/
      data y_data(    13,   9) /   0.310138050218D-02/
      data y_data(    13,  10) /   0.493319659733D-07/
      data y_data(    13,  11) /   0.160491482431D-05/
      data y_data(    13,  12) /   0.724246704260D+00/
      data x_data(    14     ) /   0.381250000000D+00/
      data y_data(    14,   1) /   0.329970688006D+03/
      data y_data(    14,   2) /   0.285967014455D+01/
      data y_data(    14,   3) /   0.988152027219D-03/
      data y_data(    14,   4) /   0.760102203963D-01/
      data y_data(    14,   5) /   0.647703507653D-20/
      data y_data(    14,   6) /   0.178302628083D-15/
      data y_data(    14,   7) /   0.192029849943D+00/
      data y_data(    14,   8) /   0.976145657083D-18/
      data y_data(    14,   9) /   0.467909950024D-02/
      data y_data(    14,  10) /   0.842305658620D-07/
      data y_data(    14,  11) /   0.250975619876D-05/
      data y_data(    14,  12) /   0.727278236174D+00/
      data x_data(    15     ) /   0.437500000000D+00/
      data y_data(    15,   1) /   0.344740082891D+03/
      data y_data(    15,   2) /   0.297377591060D+01/
      data y_data(    15,   3) /   0.950235974553D-03/
      data y_data(    15,   4) /   0.703073625629D-01/
      data y_data(    15,   5) /   0.315585684428D-19/
      data y_data(    15,   6) /   0.474756563997D-15/
      data y_data(    15,   7) /   0.192176198006D+00/
      data y_data(    15,   8) /   0.352240780360D-17/
      data y_data(    15,   9) /   0.706551280981D-02/
      data y_data(    15,  10) /   0.149353580979D-06/
      data y_data(    15,  11) /   0.394236203154D-05/
      data y_data(    15,  12) /   0.730446834906D+00/
      data x_data(    16     ) /   0.465625000000D+00/
      data y_data(    16,   1) /   0.354733756040D+03/
      data y_data(    16,   2) /   0.305259893810D+01/
      data y_data(    16,   3) /   0.925699349246D-03/
      data y_data(    16,   4) /   0.671699016936D-01/
      data y_data(    16,   5) /   0.861673507080D-19/
      data y_data(    16,   6) /   0.892994588006D-15/
      data y_data(    16,   7) /   0.192101112215D+00/
      data y_data(    16,   8) /   0.782833390246D-17/
      data y_data(    16,   9) /   0.869105487742D-02/
      data y_data(    16,  10) /   0.204878147481D-06/
      data y_data(    16,  11) /   0.495658797437D-05/
      data y_data(    16,  12) /   0.732032769748D+00/
      data x_data(    17     ) /   0.493750000000D+00/
      data y_data(    17,   1) /   0.366992806776D+03/
      data y_data(    17,   2) /   0.315041728656D+01/
      data y_data(    17,   3) /   0.896957003940D-03/
      data y_data(    17,   4) /   0.638444084938D-01/
      data y_data(    17,   5) /   0.257161615319D-18/
      data y_data(    17,   6) /   0.174416628462D-14/
      data y_data(    17,   7) /   0.191880359715D+00/
      data y_data(    17,   8) /   0.181360561682D-16/
      data y_data(    17,   9) /   0.106854010091D-01/
      data y_data(    17,  10) /   0.285344094506D-06/
      data y_data(    17,  11) /   0.623869556565D-05/
      data y_data(    17,  12) /   0.733583306742D+00/
      data x_data(    18     ) /   0.521875000000D+00/
      data y_data(    18,   1) /   0.381932745101D+03/
      data y_data(    18,   2) /   0.327075670053D+01/
      data y_data(    18,   3) /   0.863955686479D-03/
      data y_data(    18,   4) /   0.603392628069D-01/
      data y_data(    18,   5) /   0.866006024751D-18/
      data y_data(    18,   6) /   0.363360212138D-14/
      data y_data(    18,   7) /   0.191476358254D+00/
      data y_data(    18,   8) /   0.450330871571D-16/
      data y_data(    18,   9) /   0.131049362893D-01/
      data y_data(    18,  10) /   0.402886952616D-06/
      data y_data(    18,  11) /   0.784230696351D-05/
      data y_data(    18,  12) /   0.735071197456D+00/
      data x_data(    19     ) /   0.550000000000D+00/
      data y_data(    19,   1) /   0.400000000000D+03/
      data y_data(    19,   2) /   0.341740401433D+01/
      data y_data(    19,   3) /   0.826881702797D-03/
      data y_data(    19,   4) /   0.566674122534D-01/
      data y_data(    19,   5) /   0.336805043141D-17/
      data y_data(    19,   6) /   0.823255995068D-14/
      data y_data(    19,   7) /   0.190848356164D+00/
      data y_data(    19,   8) /   0.122311661017D-15/
      data y_data(    19,   9) /   0.160042037434D-01/
      data y_data(    19,  10) /   0.575967267363D-06/
      data y_data(    19,  11) /   0.982372965873D-05/
      data y_data(    19,  12) /   0.736469628142D+00/
      data x_data(    20     ) /   0.575000000000D+00/
      data y_data(    20,   1) /   0.419083748191D+03/
      data y_data(    20,   2) /   0.357323006832D+01/
      data y_data(    20,   3) /   0.790821972413D-03/
      data y_data(    20,   4) /   0.532769460642D-01/
      data y_data(    20,   5) /   0.131693905448D-16/
      data y_data(    20,   6) /   0.188967764437D-13/
      data y_data(    20,   7) /   0.190065734041D+00/
      data y_data(    20,   8) /   0.332672807579D-15/
      data y_data(    20,   9) /   0.190275269933D-01/
      data y_data(    20,  10) /   0.800278846988D-06/
      data y_data(    20,  11) /   0.119499889407D-04/
      data y_data(    20,  12) /   0.737617042633D+00/
      data x_data(    21     ) /   0.600000000000D+00/
      data y_data(    21,   1) /   0.441365377884D+03/
      data y_data(    21,   2) /   0.375602600731D+01/
      data y_data(    21,   3) /   0.752334740232D-03/
      data y_data(    21,   4) /   0.497828793900D-01/
      data y_data(    21,   5) /   0.588614860538D-16/
      data y_data(    21,   6) /   0.474702242349D-13/
      data y_data(    21,   7) /   0.189039294702D+00/
      data y_data(    21,   8) /   0.997328588299D-15/
      data y_data(    21,   9) /   0.225030716640D-01/
      data y_data(    21,  10) /   0.112173701399D-05/
      data y_data(    21,  11) /   0.144591001167D-04/
      data y_data(    21,  12) /   0.738659173407D+00/
      data x_data(    22     ) /   0.612500000000D+00/
      data y_data(    22,   1) /   0.453847179450D+03/
      data y_data(    22,   2) /   0.385875289438D+01/
      data y_data(    22,   3) /   0.732306247084D-03/
      data y_data(    22,   4) /   0.480013615220D-01/
      data y_data(    22,   5) /   0.139155684159D-15/
      data y_data(    22,   6) /   0.833616656120D-13/
      data y_data(    22,   7) /   0.188421967271D+00/
      data y_data(    22,   8) /   0.192934219658D-14/
      data y_data(    22,   9) /   0.244230579004D-01/
      data y_data(    22,  10) /   0.133618405584D-05/
      data y_data(    22,  11) /   0.158706200630D-04/
      data y_data(    22,  12) /   0.739136406503D+00/
      data x_data(    23     ) /   0.625000000000D+00/
      data y_data(    23,   1) /   0.467287266239D+03/
      data y_data(    23,   2) /   0.396958728816D+01/
      data y_data(    23,   3) /   0.711859607909D-03/
      data y_data(    23,   4) /   0.462001959556D-01/
      data y_data(    23,   5) /   0.335717161051D-15/
      data y_data(    23,   6) /   0.148351210030D-12/
      data y_data(    23,   7) /   0.187728942480D+00/
      data y_data(    23,   8) /   0.379026195405D-14/
      data y_data(    23,   9) /   0.264692043575D-01/
      data y_data(    23,  10) /   0.159583374018D-05/
      data y_data(    23,  11) /   0.173931326209D-04/
      data y_data(    23,  12) /   0.739582668240D+00/
      data x_data(    24     ) /   0.637500000000D+00/
      data y_data(    24,   1) /   0.481723397100D+03/
      data y_data(    24,   2) /   0.408885524771D+01/
      data y_data(    24,   3) /   0.691095350488D-03/
      data y_data(    24,   4) /   0.443817773358D-01/
      data y_data(    24,   5) /   0.838020476982D-15/
      data y_data(    24,   6) /   0.271882141002D-12/
      data y_data(    24,   7) /   0.186956619496D+00/
      data y_data(    24,   8) /   0.770081029378D-14/
      data y_data(    24,   9) /   0.286430729279D-01/
      data y_data(    24,  10) /   0.191049354679D-05/
      data y_data(    24,  11) /   0.190283128295D-04/
      data y_data(    24,  12) /   0.739997591434D+00/
      data x_data(    25     ) /   0.650000000000D+00/
      data y_data(    25,   1) /   0.497190513124D+03/
      data y_data(    25,   2) /   0.421686048043D+01/
      data y_data(    25,   3) /   0.670116752410D-03/
      data y_data(    25,   4) /   0.425485136538D-01/
      data y_data(    25,   5) /   0.218212568284D-14/
      data y_data(    25,   6) /   0.517053475810D-12/
      data y_data(    25,   7) /   0.186101624630D+00/
      data y_data(    25,   8) /   0.163422853069D-13/
      data y_data(    25,   9) /   0.309456176972D-01/
      data y_data(    25,  10) /   0.229221577152D-05/
      data y_data(    25,  11) /   0.207764418628D-04/
      data y_data(    25,  12) /   0.740381175361D+00/
      data x_data(    26     ) /   0.670312500000D+00/
      data y_data(    26,   1) /   0.524560092340D+03/
      data y_data(    26,   2) /   0.444383198558D+01/
      data y_data(    26,   3) /   0.635890119087D-03/
      data y_data(    26,   4) /   0.395445849632D-01/
      data y_data(    26,   5) /   0.103558624833D-13/
      data y_data(    26,   6) /   0.147141384485D-11/
      data y_data(    26,   7) /   0.184531530150D+00/
      data y_data(    26,   8) /   0.558010779084D-13/
      data y_data(    26,   9) /   0.349576280949D-01/
      data y_data(    26,  10) /   0.308566667729D-05/
      data y_data(    26,  11) /   0.238517977717D-04/
      data y_data(    26,  12) /   0.740939319325D+00/
      data x_data(    27     ) /   0.690625000000D+00/
      data y_data(    27,   1) /   0.554776519493D+03/
      data y_data(    27,   2) /   0.469498845824D+01/
      data y_data(    27,   3) /   0.601873439231D-03/
      data y_data(    27,   4) /   0.365175892743D-01/
      data y_data(    27,   5) /   0.556369601043D-13/
      data y_data(    27,   6) /   0.481438909797D-11/
      data y_data(    27,   7) /   0.182730065587D+00/
      data y_data(    27,   8) /   0.222634463156D-12/
      data y_data(    27,   9) /   0.393005888597D-01/
      data y_data(    27,  10) /   0.417007690407D-05/
      data y_data(    27,  11) /   0.271950841345D-04/
      data y_data(    27,  12) /   0.741420391113D+00/
      data x_data(    28     ) /   0.710937500000D+00/
      data y_data(    28,   1) /   0.587929443696D+03/
      data y_data(    28,   2) /   0.497115462415D+01/
      data y_data(    28,   3) /   0.568437126615D-03/
      data y_data(    28,   4) /   0.334765888713D-01/
      data y_data(    28,   5) /   0.333324495203D-12/
      data y_data(    28,   6) /   0.177338615952D-10/
      data y_data(    28,   7) /   0.180687659734D+00/
      data y_data(    28,   8) /   0.101905785269D-11/
      data y_data(    28,   9) /   0.439700127520D-01/
      data y_data(    28,  10) /   0.566080979145D-05/
      data y_data(    28,  11) /   0.307684850508D-04/
      data y_data(    28,  12) /   0.741829309329D+00/
      data x_data(    29     ) /   0.731250000000D+00/
      data y_data(    29,   1) /   0.624085793430D+03/
      data y_data(    29,   2) /   0.527298006300D+01/
      data y_data(    29,   3) /   0.535899779015D-03/
      data y_data(    29,   4) /   0.304299198964D-01/
      data y_data(    29,   5) /   0.225395461645D-11/
      data y_data(    29,   6) /   0.735622626940D-10/
      data y_data(    29,   7) /   0.178396438759D+00/
      data y_data(    29,   8) /   0.538365605461D-11/
      data y_data(    29,   9) /   0.489588265713D-01/
      data y_data(    29,  10) /   0.772663346541D-05/
      data y_data(    29,  11) /   0.345047788550D-04/
      data y_data(    29,  12) /   0.742172583279D+00/
      data x_data(    30     ) /   0.751562500000D+00/
      data y_data(    30,   1) /   0.663290856142D+03/
      data y_data(    30,   2) /   0.560094969239D+01/
      data y_data(    30,   3) /   0.504519591446D-03/
      data y_data(    30,   4) /   0.273850660446D-01/
      data y_data(    30,   5) /   0.170080114950D-10/
      data y_data(    30,   6) /   0.343429985866D-09/
      data y_data(    30,   7) /   0.175850110567D+00/
      data y_data(    30,   8) /   0.327095124076D-10/
      data y_data(    30,   9) /   0.542579708369D-01/
      data y_data(    30,  10) /   0.106238727819D-04/
      data y_data(    30,  11) /   0.382899877896D-04/
      data y_data(    30,  12) /   0.742457938298D+00/
      data x_data(    31     ) /   0.761718750000D+00/
      data y_data(    31,   1) /   0.684072464599D+03/
      data y_data(    31,   2) /   0.577508281436D+01/
      data y_data(    31,   3) /   0.489307069932D-03/
      data y_data(    31,   4) /   0.258650932206D-01/
      data y_data(    31,   5) /   0.609785151245D-10/
      data y_data(    31,   6) /   0.925940028864D-09/
      data y_data(    31,   7) /   0.174477664504D+00/
      data y_data(    31,   8) /   0.104085514760D-09/
      data y_data(    31,   9) /   0.570229396842D-01/
      data y_data(    31,  10) /   0.125439242123D-04/
      data y_data(    31,  11) /   0.401280755943D-04/
      data y_data(    31,  12) /   0.742581629501D+00/
      data x_data(    32     ) /   0.771875000000D+00/
      data y_data(    32,   1) /   0.705646844075D+03/
      data y_data(    32,   2) /   0.595606382818D+01/
      data y_data(    32,   3) /   0.474438980513D-03/
      data y_data(    32,   4) /   0.243480524068D-01/
      data y_data(    32,   5) /   0.207770645434D-09/
      data y_data(    32,   6) /   0.237908217103D-08/
      data y_data(    32,   7) /   0.173037629869D+00/
      data y_data(    32,   8) /   0.319083695137D-09/
      data y_data(    32,   9) /   0.598633543967D-01/
      data y_data(    32,  10) /   0.148641090629D-04/
      data y_data(    32,  11) /   0.418889944183D-04/
      data y_data(    32,  12) /   0.742694207318D+00/
      data x_data(    33     ) /   0.782031250000D+00/
      data y_data(    33,   1) /   0.728014163339D+03/
      data y_data(    33,   2) /   0.614391292028D+01/
      data y_data(    33,   3) /   0.459933089414D-03/
      data y_data(    33,   4) /   0.228346547693D-01/
      data y_data(    33,   5) /   0.720779878664D-09/
      data y_data(    33,   6) /   0.621512821764D-08/
      data y_data(    33,   7) /   0.171529558411D+00/
      data y_data(    33,   8) /   0.101141799689D-08/
      data y_data(    33,   9) /   0.627776684789D-01/
      data y_data(    33,  10) /   0.176895963131D-04/
      data y_data(    33,  11) /   0.435186588705D-04/
      data y_data(    33,  12) /   0.742796902138D+00/
      data x_data(    34     ) /   0.787109375000D+00/
      data y_data(    34,   1) /   0.739498333785D+03/
      data y_data(    34,   2) /   0.624044647079D+01/
      data y_data(    34,   3) /   0.452818378258D-03/
      data y_data(    34,   4) /   0.220794910991D-01/
      data y_data(    34,   5) /   0.145768464279D-08/
      data y_data(    34,   6) /   0.106013404320D-07/
      data y_data(    34,   7) /   0.170749628095D+00/
      data y_data(    34,   8) /   0.195066235224D-08/
      data y_data(    34,   9) /   0.642623079580D-01/
      data y_data(    34,  10) /   0.193453225147D-04/
      data y_data(    34,  11) /   0.442554796916D-04/
      data y_data(    34,  12) /   0.742844958036D+00/
      data x_data(    35     ) /   0.792187500000D+00/
      data y_data(    35,   1) /   0.751182993676D+03/
      data y_data(    35,   2) /   0.633872449266D+01/
      data y_data(    35,   3) /   0.445797708006D-03/
      data y_data(    35,   4) /   0.213254881855D-01/
      data y_data(    35,   5) /   0.286346323772D-08/
      data y_data(    35,   6) /   0.178485514896D-07/
      data y_data(    35,   7) /   0.169952293570D+00/
      data y_data(    35,   8) /   0.370591839128D-08/
      data y_data(    35,   9) /   0.657650442940D-01/
      data y_data(    35,  10) /   0.211852532437D-04/
      data y_data(    35,  11) /   0.449270474249D-04/
      data y_data(    35,  12) /   0.742891037232D+00/
      data x_data(    36     ) /   0.797265625000D+00/
      data y_data(    36,   1) /   0.763067749293D+03/
      data y_data(    36,   2) /   0.643874640893D+01/
      data y_data(    36,   3) /   0.438872518196D-03/
      data y_data(    36,   4) /   0.205727222559D-01/
      data y_data(    36,   5) /   0.557447112540D-08/
      data y_data(    36,   6) /   0.299603687471D-07/
      data y_data(    36,   7) /   0.169137519392D+00/
      data y_data(    36,   8) /   0.704922973870D-08/
      data y_data(    36,   9) /   0.672856665579D-01/
      data y_data(    36,  10) /   0.232317576274D-04/
      data y_data(    36,  11) /   0.455181303796D-04/
      data y_data(    36,  12) /   0.742935299322D+00/
      data x_data(    37     ) /   0.802343750000D+00/
      data y_data(    37,   1) /   0.775152056957D+03/
      data y_data(    37,   2) /   0.654051046609D+01/
      data y_data(    37,   3) /   0.432044083587D-03/
      data y_data(    37,   4) /   0.198212677693D-01/
      data y_data(    37,   5) /   0.107655207841D-07/
      data y_data(    37,   6) /   0.502608015007D-07/
      data y_data(    37,   7) /   0.168305278845D+00/
      data y_data(    37,   8) /   0.134421572434D-07/
      data y_data(    37,   9) /   0.688239584975D-01/
      data y_data(    37,  10) /   0.255074854156D-04/
      data y_data(    37,  11) /   0.460103192546D-04/
      data y_data(    37,  12) /   0.742977902615D+00/
      data x_data(    38     ) /   0.807421875000D+00/
      data y_data(    38,   1) /   0.787435156283D+03/
      data y_data(    38,   2) /   0.664401317582D+01/
      data y_data(    38,   3) /   0.425313553079D-03/
      data y_data(    38,   4) /   0.190711991021D-01/
      data y_data(    38,   5) /   0.205600937599D-07/
      data y_data(    38,   6) /   0.842209630784D-07/
      data y_data(    38,   7) /   0.167455558956D+00/
      data y_data(    38,   8) /   0.256227104505D-07/
      data y_data(    38,   9) /   0.703796942761D-01/
      data y_data(    38,  10) /   0.280326609089D-04/
      data y_data(    38,  11) /   0.463813450026D-04/
      data y_data(    38,  12) /   0.743019003256D+00/
      data x_data(    39     ) /   0.812500000000D+00/
      data y_data(    39,   1) /   0.799915954474D+03/
      data y_data(    39,   2) /   0.674924834546D+01/
      data y_data(    39,   3) /   0.418682008110D-03/
      data y_data(    39,   4) /   0.183225935111D-01/
      data y_data(    39,   5) /   0.386774706488D-07/
      data y_data(    39,   6) /   0.140727244429D-06/
      data y_data(    39,   7) /   0.166588369289D+00/
      data y_data(    39,   8) /   0.486121564103D-07/
      data y_data(    39,   9) /   0.719526303414D-01/
      data y_data(    39,  10) /   0.308204819499D-04/
      data y_data(    39,  11) /   0.466043425472D-04/
      data y_data(    39,  12) /   0.743058754017D+00/
      data x_data(    40     ) /   0.817578125000D+00/
      data y_data(    40,   1) /   0.812592831604D+03/
      data y_data(    40,   2) /   0.685620544259D+01/
      data y_data(    40,   3) /   0.412150550939D-03/
      data y_data(    40,   4) /   0.175755362569D-01/
      data y_data(    40,   5) /   0.713954528336D-07/
      data y_data(    40,   6) /   0.233962739995D-06/
      data y_data(    40,   7) /   0.165703756475D+00/
      data y_data(    40,   8) /   0.913631664331D-07/
      data y_data(    40,   9) /   0.735424906125D-01/
      data y_data(    40,  10) /   0.338701210717D-04/
      data y_data(    40,  11) /   0.466471627538D-04/
      data y_data(    40,  12) /   0.743097302651D+00/
      data x_data(    41     ) /   0.822656250000D+00/
      data y_data(    41,   1) /   0.825463323906D+03/
      data y_data(    41,   2) /   0.696486692738D+01/
      data y_data(    41,   3) /   0.405720436582D-03/
      data y_data(    41,   4) /   0.168301292366D-01/
      data y_data(    41,   5) /   0.128881572915D-06/
      data y_data(    41,   6) /   0.386087977973D-06/
      data y_data(    41,   7) /   0.164801826860D+00/
      data y_data(    41,   8) /   0.169298257992D-06/
      data y_data(    41,   9) /   0.751489406121D-01/
      data y_data(    41,  10) /   0.371573164902D-04/
      data y_data(    41,  11) /   0.464719377946D-04/
      data y_data(    41,  12) /   0.743134789769D+00/
      data x_data(    42     ) /   0.827734375000D+00/
      data y_data(    42,   1) /   0.838523628199D+03/
      data y_data(    42,   2) /   0.707520406548D+01/
      data y_data(    42,   3) /   0.399393264754D-03/
      data y_data(    42,   4) /   0.160865050202D-01/
      data y_data(    42,   5) /   0.226875988826D-06/
      data y_data(    42,   6) /   0.630877472240D-06/
      data y_data(    42,   7) /   0.163882779825D+00/
      data y_data(    42,   8) /   0.307933675380D-06/
      data y_data(    42,   9) /   0.767715442762D-01/
      data y_data(    42,  10) /   0.406236121506D-04/
      data y_data(    42,  11) /   0.460352519353D-04/
      data y_data(    42,  12) /   0.743171346328D+00/
      data x_data(    43     ) /   0.832812500000D+00/
      data y_data(    43,   1) /   0.851767861003D+03/
      data y_data(    43,   2) /   0.718717064594D+01/
      data y_data(    43,   3) /   0.393171247730D-03/
      data y_data(    43,   4) /   0.153448486995D-01/
      data y_data(    43,   5) /   0.388584717313D-06/
      data y_data(    43,   6) /   0.101835569406D-05/
      data y_data(    43,   7) /   0.162946953976D+00/
      data y_data(    43,   8) /   0.547579187189D-06/
      data y_data(    43,   9) /   0.784096953958D-01/
      data y_data(    43,  10) /   0.441669727869D-04/
      data y_data(    43,  11) /   0.452894394027D-04/
      data y_data(    43,  12) /   0.743207090997D+00/
      data x_data(    44     ) /   0.837890625000D+00/
      data y_data(    44,   1) /   0.865187009472D+03/
      data y_data(    44,   2) /   0.730069405266D+01/
      data y_data(    44,   3) /   0.387057563312D-03/
      data y_data(    44,   4) /   0.146054301707D-01/
      data y_data(    44,   5) /   0.646467024104D-06/
      data y_data(    44,   6) /   0.162022393905D-05/
      data y_data(    44,   7) /   0.161994887580D+00/
      data y_data(    44,   8) /   0.948701755271D-06/
      data y_data(    44,   9) /   0.800625149638D-01/
      data y_data(    44,  10) /   0.476382979927D-04/
      data y_data(    44,  11) /   0.441856528714D-04/
      data y_data(    44,  12) /   0.743242127942D+00/
      data x_data(    45     ) /   0.842968750000D+00/
      data y_data(    45,   1) /   0.878767541528D+03/
      data y_data(    45,   2) /   0.741566338638D+01/
      data y_data(    45,   3) /   0.381056785250D-03/
      data y_data(    45,   4) /   0.138686490267D-01/
      data y_data(    45,   5) /   0.104340048869D-05/
      data y_data(    45,   6) /   0.253541296416D-05/
      data y_data(    45,   7) /   0.161027393513D+00/
      data y_data(    45,   8) /   0.159697895756D-05/
      data y_data(    45,   9) /   0.817287076446D-01/
      data y_data(    45,  10) /   0.508491382008D-04/
      data y_data(    45,  11) /   0.426792846809D-04/
      data y_data(    45,  12) /   0.743276545601D+00/
      data x_data(    46     ) /   0.848046875000D+00/
      data y_data(    46,   1) /   0.892489711878D+03/
      data y_data(    46,   2) /   0.753191492142D+01/
      data y_data(    46,   3) /   0.375175354474D-03/
      data y_data(    46,   4) /   0.131350927301D-01/
      data y_data(    46,   5) /   0.163252680126D-05/
      data y_data(    46,   6) /   0.389439578235D-05/
      data y_data(    46,   7) /   0.160045648173D+00/
      data y_data(    46,   8) /   0.260651740418D-05/
      data y_data(    46,   9) /   0.834063767409D-01/
      data y_data(    46,  10) /   0.535941071666D-04/
      data y_data(    46,  11) /   0.407379048170D-04/
      data y_data(    46,  12) /   0.743310416904D+00/
      data x_data(    47     ) /   0.853125000000D+00/
      data y_data(    47,   1) /   0.906325711122D+03/
      data y_data(    47,   2) /   0.764921612629D+01/
      data y_data(    47,   3) /   0.369422017087D-03/
      data y_data(    47,   4) /   0.124056059671D-01/
      data y_data(    47,   5) /   0.247499366857D-05/
      data y_data(    47,   6) /   0.586002407021D-05/
      data y_data(    47,   7) /   0.159051293549D+00/
      data y_data(    47,   8) /   0.411942263598D-05/
      data y_data(    47,   9) /   0.850928080698D-01/
      data y_data(    47,  10) /   0.556862053604D-04/
      data y_data(    47,  11) /   0.383510026880D-04/
      data y_data(    47,  12) /   0.743343800765D+00/
      data x_data(    48     ) /   0.858203125000D+00/
      data y_data(    48,   1) /   0.920237935087D+03/
      data y_data(    48,   2) /   0.776725059810D+01/
      data y_data(    48,   3) /   0.363808121654D-03/
      data y_data(    48,   4) /   0.116813651892D-01/
      data y_data(    48,   5) /   0.363494870828D-05/
      data y_data(    48,   6) /   0.862191545979D-05/
      data y_data(    48,   7) /   0.158046550967D+00/
      data y_data(    48,   8) /   0.629996494363D-05/
      data y_data(    48,   9) /   0.867842475760D-01/
      data y_data(    48,  10) /   0.569958818484D-04/
      data y_data(    48,  11) /   0.355396269085D-04/
      data y_data(    48,  12) /   0.743376743930D+00/
      data x_data(    49     ) /   0.860742187500D+00/
      data y_data(    49,   1) /   0.927204474196D+03/
      data y_data(    49,   2) /   0.782638914364D+01/
      data y_data(    49,   3) /   0.361059078286D-03/
      data y_data(    49,   4) /   0.113218100187D-01/
      data y_data(    49,   5) /   0.435662759702D-05/
      data y_data(    49,   6) /   0.103778715997D-04/
      data y_data(    49,   7) /   0.157541372775D+00/
      data y_data(    49,   8) /   0.770634127819D-05/
      data y_data(    49,   9) /   0.876299758094D-01/
      data y_data(    49,  10) /   0.573400579298D-04/
      data y_data(    49,  11) /   0.339966296827D-04/
      data y_data(    49,  12) /   0.743393063869D+00/
      data x_data(    50     ) /   0.863281250000D+00/
      data y_data(    50,   1) /   0.934170705883D+03/
      data y_data(    50,   2) /   0.788554713581D+01/
      data y_data(    50,   3) /   0.358350384804D-03/
      data y_data(    50,   4) /   0.109642054722D-01/
      data y_data(    50,   5) /   0.517839797066D-05/
      data y_data(    50,   6) /   0.124095042473D-04/
      data y_data(    50,   7) /   0.157034761446D+00/
      data y_data(    50,   8) /   0.934702092946D-05/
      data y_data(    50,   9) /   0.884749525654D-01/
      data y_data(    50,  10) /   0.574796975822D-04/
      data y_data(    50,  11) /   0.323730287983D-04/
      data y_data(    50,  12) /   0.743409292867D+00/
      data x_data(    51     ) /   0.868359375000D+00/
      data y_data(    51,   1) /   0.948078494118D+03/
      data y_data(    51,   2) /   0.800371986624D+01/
      data y_data(    51,   3) /   0.353059439578D-03/
      data y_data(    51,   4) /   0.102556399801D-01/
      data y_data(    51,   5) /   0.713418588251D-05/
      data y_data(    51,   6) /   0.173681319873D-04/
      data y_data(    51,   7) /   0.156018732497D+00/
      data y_data(    51,   8) /   0.133966598311D-04/
      data y_data(    51,   9) /   0.901601463789D-01/
      data y_data(    51,  10) /   0.571746323407D-04/
      data y_data(    51,  11) /   0.289254068085D-04/
      data y_data(    51,  12) /   0.743441482128D+00/
      data x_data(    52     ) /   0.873437500000D+00/
      data y_data(    52,   1) /   0.961882779429D+03/
      data y_data(    52,   2) /   0.812109963171D+01/
      data y_data(    52,   3) /   0.347956431846D-03/
      data y_data(    52,   4) /   0.955845135273D-02/
      data y_data(    52,   5) /   0.952053386401D-05/
      data y_data(    52,   6) /   0.236604503863D-04/
      data y_data(    52,   7) /   0.155003612059D+00/
      data y_data(    52,   8) /   0.186129361126D-04/
      data y_data(    52,   9) /   0.918312918873D-01/
      data y_data(    52,  10) /   0.562136002051D-04/
      data y_data(    52,  11) /   0.253418397281D-04/
      data y_data(    52,  12) /   0.743473295341D+00/
      data x_data(    53     ) /   0.878515625000D+00/
      data y_data(    53,   1) /   0.975504378190D+03/
      data y_data(    53,   2) /   0.823700960659D+01/
      data y_data(    53,   3) /   0.343060040655D-03/
      data y_data(    53,   4) /   0.887558779607D-02/
      data y_data(    53,   5) /   0.123108743842D-04/
      data y_data(    53,   6) /   0.313453816827D-04/
      data y_data(    53,   7) /   0.153994927145D+00/
      data y_data(    53,   8) /   0.250942096855D-04/
      data y_data(    53,   9) /   0.934794915814D-01/
      data y_data(    53,  10) /   0.547548723637D-04/
      data y_data(    53,  11) /   0.217694284320D-04/
      data y_data(    53,  12) /   0.743504718711D+00/
      data x_data(    54     ) /   0.883593750000D+00/
      data y_data(    54,   1) /   0.988858748332D+03/
      data y_data(    54,   2) /   0.835072482931D+01/
      data y_data(    54,   3) /   0.338388452293D-03/
      data y_data(    54,   4) /   0.821035379899D-02/
      data y_data(    54,   5) /   0.154328652027D-04/
      data y_data(    54,   6) /   0.403677750339D-04/
      data y_data(    54,   7) /   0.152999011797D+00/
      data y_data(    54,   8) /   0.328697856687D-04/
      data y_data(    54,   9) /   0.950949374534D-01/
      data y_data(    54,  10) /   0.529581183561D-04/
      data y_data(    54,  11) /   0.183531478642D-04/
      data y_data(    54,  12) /   0.743535715258D+00/
      data x_data(    55     ) /   0.888671875000D+00/
      data y_data(    55,   1) /   0.100185991973D+04/
      data y_data(    55,   2) /   0.846150564164D+01/
      data y_data(    55,   3) /   0.333958159480D-03/
      data y_data(    55,   4) /   0.756626785739D-02/
      data y_data(    55,   5) /   0.187696156998D-04/
      data y_data(    55,   6) /   0.505424833281D-04/
      data y_data(    55,   7) /   0.152022794978D+00/
      data y_data(    55,   8) /   0.418832888219D-04/
      data y_data(    55,   9) /   0.966673411033D-01/
      data y_data(    55,  10) /   0.509594591094D-04/
      data y_data(    55,  11) /   0.152168658935D-04/
      data y_data(    55,  12) /   0.743566224348D+00/
      data x_data(    56     ) /   0.893750000000D+00/
      data y_data(    56,   1) /   0.101442476606D+04/
      data y_data(    56,   2) /   0.856863430647D+01/
      data y_data(    56,   3) /   0.329782874312D-03/
      data y_data(    56,   4) /   0.694687458673D-02/
      data y_data(    56,   5) /   0.221688520324D-04/
      data y_data(    56,   6) /   0.615589512942D-04/
      data y_data(    56,   7) /   0.151073477926D+00/
      data y_data(    56,   8) /   0.519859244051D-04/
      data y_data(    56,   9) /   0.981864590495D-01/
      data y_data(    56,  10) /   0.488615366085D-04/
      data y_data(    56,  11) /   0.124490084562D-04/
      data y_data(    56,  12) /   0.743596164165D+00/
      data x_data(    57     ) /   0.898828125000D+00/
      data y_data(    57,   1) /   0.102647717010D+04/
      data y_data(    57,   2) /   0.867145098611D+01/
      data y_data(    57,   3) /   0.325872665951D-03/
      data y_data(    57,   4) /   0.635553206177D-02/
      data y_data(    57,   5) /   0.254588535792D-04/
      data y_data(    57,   6) /   0.730067127076D-04/
      data y_data(    57,   7) /   0.150158137621D+00/
      data y_data(    57,   8) /   0.629422169526D-04/
      data y_data(    57,   9) /   0.996426552271D-01/
      data y_data(    57,  10) /   0.467348067776D-04/
      data y_data(    57,  11) /   0.100958615504D-04/
      data y_data(    57,  12) /   0.743625436638D+00/
      data x_data(    58     ) /   0.903906250000D+00/
      data y_data(    58,   1) /   0.103795156816D+04/
      data y_data(    58,   2) /   0.876938464803D+01/
      data y_data(    58,   3) /   0.322233425027D-03/
      data y_data(    58,   4) /   0.579520185281D-02/
      data y_data(    58,   5) /   0.284681418199D-04/
      data y_data(    58,   6) /   0.844169357055D-04/
      data y_data(    58,   7) /   0.149283310996D+00/
      data y_data(    58,   8) /   0.744480834292D-04/
      data y_data(    58,   9) /   0.101027432893D+00/
      data y_data(    58,  10) /   0.446240928288D-04/
      data y_data(    58,  11) /   0.816307013950D-05/
      data y_data(    58,  12) /   0.743653933933D+00/
      data x_data(    59     ) /   0.908984375000D+00/
      data y_data(    59,   1) /   0.104879559822D+04/
      data y_data(    59,   2) /   0.886197644481D+01/
      data y_data(    59,   3) /   0.318866662320D-03/
      data y_data(    59,   4) /   0.526826976660D-02/
      data y_data(    59,   5) /   0.310450003560D-04/
      data y_data(    59,   6) /   0.953116288865D-04/
      data y_data(    59,   7) /   0.148454618567D+00/
      data y_data(    59,   8) /   0.861581002568D-04/
      data y_data(    59,   9) /   0.102333871868D+00/
      data y_data(    59,  10) /   0.425559382975D-04/
      data y_data(    59,  11) /   0.662357688262D-05/
      data y_data(    59,  12) /   0.743681545553D+00/
      data x_data(    60     ) /   0.914062500000D+00/
      data y_data(    60,   1) /   0.105897165186D+04/
      data y_data(    60,   2) /   0.894889374295D+01/
      data y_data(    60,   3) /   0.315769628256D-03/
      data y_data(    60,   4) /   0.477641949926D-02/
      data y_data(    60,   5) /   0.330731637023D-04/
      data y_data(    60,   6) /   0.105251220580D-03/
      data y_data(    60,   7) /   0.147676476462D+00/
      data y_data(    60,   8) /   0.977168889498D-04/
      data y_data(    60,   9) /   0.103556923908D+00/
      data y_data(    60,  10) /   0.405447205631D-04/
      data y_data(    60,  11) /   0.542889370193D-05/
      data y_data(    60,  12) /   0.743708165243D+00/
      data x_data(    61     ) /   0.919140625000D+00/
      data y_data(    61,   1) /   0.106845730451D+04/
      data y_data(    61,   2) /   0.902993447506D+01/
      data y_data(    61,   3) /   0.312935698295D-03/
      data y_data(    61,   4) /   0.432057116439D-02/
      data y_data(    61,   5) /   0.344812320365D-04/
      data y_data(    61,   6) /   0.113872805559D-03/
      data y_data(    61,   7) /   0.146951926608D+00/
      data y_data(    61,   8) /   0.108789226729D-03/
      data y_data(    61,   9) /   0.104693544275D+00/
      data y_data(    61,  10) /   0.385971290309D-04/
      data y_data(    61,  11) /   0.452052535668D-05/
      data y_data(    61,  12) /   0.743733697034D+00/
      data x_data(    62     ) /   0.924218750000D+00/
      data y_data(    62,   1) /   0.107724474030D+04/
      data y_data(    62,   2) /   0.910502272956D+01/
      data y_data(    62,   3) /   0.310354947422D-03/
      data y_data(    62,   4) /   0.390088514220D-02/
      data y_data(    62,   5) /   0.352450418053D-04/
      data y_data(    62,   6) /   0.120914483496D-03/
      data y_data(    62,   7) /   0.146282592263D+00/
      data y_data(    62,   8) /   0.119084556251D-03/
      data y_data(    62,   9) /   0.105742664000D+00/
      data y_data(    62,  10) /   0.367152691010D-04/
      data y_data(    62,  11) /   0.383927086729D-05/
      data y_data(    62,  12) /   0.743758059973D+00/
      data x_data(    63     ) /   0.929296875000D+00/
      data y_data(    63,   1) /   0.108533938368D+04/
      data y_data(    63,   2) /   0.917419735869D+01/
      data y_data(    63,   3) /   0.308014831165D-03/
      data y_data(    63,   4) /   0.351682192291D-02/
      data y_data(    63,   5) /   0.353837773462D-04/
      data y_data(    63,   6) /   0.126224693401D-03/
      data y_data(    63,   7) /   0.145668746086D+00/
      data y_data(    63,   8) /   0.128373388601D-03/
      data y_data(    63,   9) /   0.106705028680D+00/
      data y_data(    63,  10) /   0.348987515278D-04/
      data y_data(    63,  11) /   0.333139990153D-05/
      data y_data(    63,  12) /   0.743781191300D+00/
      data x_data(    64     ) /   0.934375000000D+00/
      data y_data(    64,   1) /   0.109275799491D+04/
      data y_data(    64,   2) /   0.923759580460D+01/
      data y_data(    64,   3) /   0.305900897840D-03/
      data y_data(    64,   4) /   0.316724247871D-02/
      data y_data(    64,   5) /   0.349516405094D-04/
      data y_data(    64,   6) /   0.129758299736D-03/
      data y_data(    64,   7) /   0.145109464445D+00/
      data y_data(    64,   8) /   0.136494999417D-03/
      data y_data(    64,   9) /   0.107582942234D+00/
      data y_data(    64,  10) /   0.331460518999D-04/
      data y_data(    64,  11) /   0.295178310695D-05/
      data y_data(    64,  12) /   0.743803048067D+00/
      data x_data(    65     ) /   0.939453125000D+00/
      data y_data(    65,   1) /   0.109952648463D+04/
      data y_data(    65,   2) /   0.929543535954D+01/
      data y_data(    65,   3) /   0.303997472008D-03/
      data y_data(    65,   4) /   0.285053163590D-02/
      data y_data(    65,   5) /   0.340272672265D-04/
      data y_data(    65,   6) /   0.131562908468D-03/
      data y_data(    65,   7) /   0.144602835902D+00/
      data y_data(    65,   8) /   0.143357332041D-03/
      data y_data(    65,   9) /   0.108379957580D+00/
      data y_data(    65,  10) /   0.314553466337D-04/
      data y_data(    65,  11) /   0.266467808921D-05/
      data y_data(    65,  12) /   0.743823607349D+00/
      data x_data(    66     ) /   0.944531250000D+00/
      data y_data(    66,   1) /   0.110567766910D+04/
      data y_data(    66,   2) /   0.934799380221D+01/
      data y_data(    66,   3) /   0.302288267440D-03/
      data y_data(    66,   4) /   0.256472823329D-02/
      data y_data(    66,   5) /   0.327028920641D-04/
      data y_data(    66,   6) /   0.131759454802D-03/
      data y_data(    66,   7) /   0.144146192801D+00/
      data y_data(    66,   8) /   0.148930923933D-03/
      data y_data(    66,   9) /   0.109100552372D+00/
      data y_data(    66,  10) /   0.298249831689D-04/
      data y_data(    66,  11) /   0.244304660566D-05/
      data y_data(    66,  12) /   0.743842865293D+00/
      data x_data(    67     ) /   0.949609375000D+00/
      data y_data(    67,   1) /   0.111124913649D+04/
      data y_data(    67,   2) /   0.939559091603D+01/
      data y_data(    67,   3) /   0.300756905634D-03/
      data y_data(    67,   4) /   0.230764927217D-02/
      data y_data(    67,   5) /   0.310747399154D-04/
      data y_data(    67,   6) /   0.130520779324D-03/
      data y_data(    67,   7) /   0.143736340338D+00/
      data y_data(    67,   8) /   0.153238958549D-03/
      data y_data(    67,   9) /   0.109749819709D+00/
      data y_data(    67,  10) /   0.282537127027D-04/
      data y_data(    67,  11) /   0.226716217791D-05/
      data y_data(    67,  12) /   0.743860835327D+00/
      data x_data(    68     ) /   0.954687500000D+00/
      data y_data(    68,   1) /   0.111628133868D+04/
      data y_data(    68,   2) /   0.943857191170D+01/
      data y_data(    68,   3) /   0.299387330726D-03/
      data y_data(    68,   4) /   0.207699948032D-02/
      data y_data(    68,   5) /   0.292355083649D-04/
      data y_data(    68,   6) /   0.128051063458D-03/
      data y_data(    68,   7) /   0.143369765025D+00/
      data y_data(    68,   8) /   0.156345327826D-03/
      data y_data(    68,   9) /   0.110333193964D+00/
      data y_data(    68,  10) /   0.267407893936D-04/
      data y_data(    68,  11) /   0.212303492090D-05/
      data y_data(    68,  12) /   0.743877545806D+00/
      data x_data(    69     ) /   0.959765625000D+00/
      data y_data(    69,   1) /   0.112081597187D+04/
      data y_data(    69,   2) /   0.947729332669D+01/
      data y_data(    69,   3) /   0.298164122720D-03/
      data y_data(    69,   4) /   0.187046172417D-02/
      data y_data(    69,   5) /   0.272692851470D-04/
      data y_data(    69,   6) /   0.124567932805D-03/
      data y_data(    69,   7) /   0.143042812126D+00/
      data y_data(    69,   8) /   0.158341984736D-03/
      data y_data(    69,   9) /   0.110856222612D+00/
      data y_data(    69,  10) /   0.252859920069D-04/
      data y_data(    69,  11) /   0.200095142227D-05/
      data y_data(    69,  12) /   0.743893037391D+00/
      data x_data(    70     ) /   0.964843750000D+00/
      data y_data(    70,   1) /   0.112489466835D+04/
      data y_data(    70,   2) /   0.951211160966D+01/
      data y_data(    70,   3) /   0.297072718075D-03/
      data y_data(    70,   4) /   0.168576690939D-02/
      data y_data(    70,   5) /   0.252489599016D-04/
      data y_data(    70,   6) /   0.120287874994D-03/
      data y_data(    70,   7) /   0.142751828661D+00/
      data y_data(    70,   8) /   0.159335858217D-03/
      data y_data(    70,   9) /   0.111324387659D+00/
      data y_data(    70,  10) /   0.238894375440D-04/
      data y_data(    70,  11) /   0.189425668679D-05/
      data y_data(    70,  12) /   0.743907360384D+00/
      data x_data(    71     ) /   0.975000000000D+00/
      data y_data(    71,   1) /   0.113180909713D+04/
      data y_data(    71,   2) /   0.957110781726D+01/
      data y_data(    71,   3) /   0.295241564975D-03/
      data y_data(    71,   4) /   0.137527582143D-02/
      data y_data(    71,   5) /   0.212304705842D-04/
      data y_data(    71,   6) /   0.109946789612D-03/
      data y_data(    71,   7) /   0.142266944324D+00/
      data y_data(    71,   8) /   0.158638871449D-03/
      data y_data(    71,   9) /   0.112112330793D+00/
      data y_data(    71,  10) /   0.212678722305D-04/
      data y_data(    71,  11) /   0.171332398566D-05/
      data y_data(    71,  12) /   0.743932651734D+00/
      data x_data(    72     ) /   0.985156250000D+00/
      data y_data(    72,   1) /   0.113737955004D+04/
      data y_data(    72,   2) /   0.961860732786D+01/
      data y_data(    72,   3) /   0.293783575334D-03/
      data y_data(    72,   4) /   0.112761031413D-02/
      data y_data(    72,   5) /   0.175367910591D-04/
      data y_data(    72,   6) /   0.985846006952D-04/
      data y_data(    72,   7) /   0.141884522354D+00/
      data y_data(    72,   8) /   0.155399464750D-03/
      data y_data(    72,   9) /   0.112741889553D+00/
      data y_data(    72,  10) /   0.188742922641D-04/
      data y_data(    72,  11) /   0.155750440984D-05/
      data y_data(    72,  12) /   0.743954025126D+00/
      data x_data(    73     ) /   0.995312500000D+00/
      data y_data(    73,   1) /   0.114186550067D+04/
      data y_data(    73,   2) /   0.965683451288D+01/
      data y_data(    73,   3) /   0.292620614627D-03/
      data y_data(    73,   4) /   0.929697977733D-03/
      data y_data(    73,   5) /   0.143114559013D-04/
      data y_data(    73,   6) /   0.871621613520D-04/
      data y_data(    73,   7) /   0.141582819044D+00/
      data y_data(    73,   8) /   0.150456107704D-03/
      data y_data(    73,   9) /   0.113245411055D+00/
      data y_data(    73,  10) /   0.167037986706D-04/
      data y_data(    73,  11) /   0.141894526716D-05/
      data y_data(    73,  12) /   0.743972019454D+00/
      data x_data(    74     ) /   0.100546875000D+01/
      data y_data(    74,   1) /   0.114548344294D+04/
      data y_data(    74,   2) /   0.968764477517D+01/
      data y_data(    74,   3) /   0.291689973785D-03/
      data y_data(    74,   4) /   0.770959837324D-03/
      data y_data(    74,   5) /   0.115903054882D-04/
      data y_data(    74,   6) /   0.762971086476D-04/
      data y_data(    74,   7) /   0.141344185397D+00/
      data y_data(    74,   8) /   0.144470861181D-03/
      data y_data(    74,   9) /   0.113649307371D+00/
      data y_data(    74,  10) /   0.147492319814D-04/
      data y_data(    74,  11) /   0.129413069504D-05/
      data y_data(    74,  12) /   0.743987145756D+00/
      data x_data(    75     ) /   0.101562500000D+01/
      data y_data(    75,   1) /   0.114840976651D+04/
      data y_data(    75,   2) /   0.971254902357D+01/
      data y_data(    75,   3) /   0.290942042470D-03/
      data y_data(    75,   4) /   0.643007427736D-03/
      data y_data(    75,   5) /   0.934669569606D-05/
      data y_data(    75,   6) /   0.663346909255D-04/
      data y_data(    75,   7) /   0.141154651063D+00/
      data y_data(    75,   8) /   0.137937168545D-03/
      data y_data(    75,   9) /   0.113974675595D+00/
      data y_data(    75,  10) /   0.130004395231D-04/
      data y_data(    75,  11) /   0.118132525518D-05/
      data y_data(    75,  12) /   0.743999865595D+00/
      data x_data(    76     ) /   0.102578125000D+01/
      data y_data(    76,   1) /   0.115078598495D+04/
      data y_data(    76,   2) /   0.973275864876D+01/
      data y_data(    76,   3) /   0.290337914716D-03/
      data y_data(    76,   4) /   0.539266794948D-03/
      data y_data(    76,   5) /   0.752427911929D-05/
      data y_data(    76,   6) /   0.574267313559D-04/
      data y_data(    76,   7) /   0.141003323029D+00/
      data y_data(    76,   8) /   0.131205743161D-03/
      data y_data(    76,   9) /   0.114238147508D+00/
      data y_data(    76,  10) /   0.114444919829D-04/
      data y_data(    76,  11) /   0.107946430364D-05/
      data y_data(    76,  12) /   0.744010581958D+00/
      data x_data(    77     ) /   0.103593750000D+01/
      data y_data(    77,   1) /   0.115272455561D+04/
      data y_data(    77,   2) /   0.974923567475D+01/
      data y_data(    77,   3) /   0.289847219288D-03/
      data y_data(    77,   4) /   0.454615830645D-03/
      data y_data(    77,   5) /   0.605669458299D-05/
      data y_data(    77,   6) /   0.496017985433D-04/
      data y_data(    77,   7) /   0.140881771495D+00/
      data y_data(    77,   8) /   0.124518705569D-03/
      data y_data(    77,   9) /   0.114452742354D+00/
      data y_data(    77,  10) /   0.100671979929D-04/
      data y_data(    77,  11) /   0.987711510863D-06/
      data y_data(    77,  12) /   0.744019638212D+00/
      data x_data(    78     ) /   0.105625000000D+01/
      data y_data(    78,   1) /   0.115555650251D+04/
      data y_data(    78,   2) /   0.977328103882D+01/
      data y_data(    78,   3) /   0.289134103408D-03/
      data y_data(    78,   4) /   0.330593232152D-03/
      data y_data(    78,   5) /   0.397764348718D-05/
      data y_data(    78,   6) /   0.371038309905D-04/
      data y_data(    78,   7) /   0.140708339933D+00/
      data y_data(    78,   8) /   0.111803221470D-03/
      data y_data(    78,   9) /   0.114765895594D+00/
      data y_data(    78,  10) /   0.782881694407D-05/
      data y_data(    78,  11) /   0.832132086116D-06/
      data y_data(    78,  12) /   0.744033625596D+00/
      data x_data(    79     ) /   0.107656250000D+01/
      data y_data(    79,   1) /   0.115750524833D+04/
      data y_data(    79,   2) /   0.978980957927D+01/
      data y_data(    79,   3) /   0.288645946342D-03/
      data y_data(    79,   4) /   0.245055218512D-03/
      data y_data(    79,   5) /   0.264814777464D-05/
      data y_data(    79,   6) /   0.279000190459D-04/
      data y_data(    79,   7) /   0.140592019865D+00/
      data y_data(    79,   8) /   0.100358204418D-03/
      data y_data(    79,   9) /   0.114981357954D+00/
      data y_data(    79,  10) /   0.610797737872D-05/
      data y_data(    79,  11) /   0.706219234776D-06/
      data y_data(    79,  12) /   0.744043846394D+00/
      data x_data(    80     ) /   0.109687500000D+01/
      data y_data(    80,   1) /   0.115887350857D+04/
      data y_data(    80,   2) /   0.980140173614D+01/
      data y_data(    80,   3) /   0.288304563631D-03/
      data y_data(    80,   4) /   0.184716316313D-03/
      data y_data(    80,   5) /   0.179136915564D-05/
      data y_data(    80,   6) /   0.211648098784D-04/
      data y_data(    80,   7) /   0.140512345505D+00/
      data y_data(    80,   8) /   0.902466584681D-04/
      data y_data(    80,   9) /   0.115132866400D+00/
      data y_data(    80,  10) /   0.478980936452D-05/
      data y_data(    80,  11) /   0.603778811276D-06/
      data y_data(    80,  12) /   0.744051475353D+00/
      data x_data(    81     ) /   0.111718750000D+01/
      data y_data(    81,   1) /   0.115985335318D+04/
      data y_data(    81,   2) /   0.980969325225D+01/
      data y_data(    81,   3) /   0.288060877934D-03/
      data y_data(    81,   4) /   0.141220979807D-03/
      data y_data(    81,   5) /   0.123112065779D-05/
      data y_data(    81,   6) /   0.162198312967D-04/
      data y_data(    81,   7) /   0.140456705636D+00/
      data y_data(    81,   8) /   0.813733071651D-04/
      data y_data(    81,   9) /   0.115241652057D+00/
      data y_data(    81,  10) /   0.377835396736D-05/
      data y_data(    81,  11) /   0.519704101506D-06/
      data y_data(    81,  12) /   0.744057299010D+00/
      data x_data(    82     ) /   0.113750000000D+01/
      data y_data(    82,   1) /   0.116056893561D+04/
      data y_data(    82,   2) /   0.981574067984D+01/
      data y_data(    82,   3) /   0.287883405102D-03/
      data y_data(    82,   4) /   0.109191406524D-03/
      data y_data(    82,   5) /   0.857664440974D-06/
      data y_data(    82,   6) /   0.125518513185D-04/
      data y_data(    82,   7) /   0.140417130821D+00/
      data y_data(    82,   8) /   0.736006074558D-04/
      data y_data(    82,   9) /   0.115321373799D+00/
      data y_data(    82,  10) /   0.299662600596D-05/
      data y_data(    82,  11) /   0.450043386323D-06/
      data y_data(    82,  12) /   0.744061847181D+00/
      data x_data(    83     ) /   0.117812500000D+01/
      data y_data(    83,   1) /   0.116145338313D+04/
      data y_data(    83,   2) /   0.982319644314D+01/
      data y_data(    83,   3) /   0.287664902852D-03/
      data y_data(    83,   4) /   0.688945401398D-04/
      data y_data(    83,   5) /   0.447169556509D-06/
      data y_data(    83,   6) /   0.792026973941D-05/
      data y_data(    83,   7) /   0.140370554936D+00/
      data y_data(    83,   8) /   0.610997845526D-04/
      data y_data(    83,   9) /   0.115420572295D+00/
      data y_data(    83,  10) /   0.196446086822D-05/
      data y_data(    83,  11) /   0.345174518780D-06/
      data y_data(    83,  12) /   0.744068201369D+00/
      data x_data(    84     ) /   0.121875000000D+01/
      data y_data(    84,   1) /   0.116197732451D+04/
      data y_data(    84,   2) /   0.982759949215D+01/
      data y_data(    84,   3) /   0.287536020650D-03/
      data y_data(    84,   4) /   0.446931285404D-04/
      data y_data(    84,   5) /   0.242650181812D-06/
      data y_data(    84,   6) /   0.516286266766D-05/
      data y_data(    84,   7) /   0.140344843390D+00/
      data y_data(    84,   8) /   0.512078247030D-04/
      data y_data(    84,   9) /   0.115479747003D+00/
      data y_data(    84,  10) /   0.131470352556D-05/
      data y_data(    84,  11) /   0.267973115935D-06/
      data y_data(    84,  12) /   0.744072520464D+00/
      data x_data(    85     ) /   0.125937500000D+01/
      data y_data(    85,   1) /   0.116231001420D+04/
      data y_data(    85,   2) /   0.983038515682D+01/
      data y_data(    85,   3) /   0.287454540736D-03/
      data y_data(    85,   4) /   0.290629439941D-04/
      data y_data(    85,   5) /   0.133500427849D-06/
      data y_data(    85,   6) /   0.342315762226D-05/
      data y_data(    85,   7) /   0.140329879981D+00/
      data y_data(    85,   8) /   0.430981879237D-04/
      data y_data(    85,   9) /   0.115517645461D+00/
      data y_data(    85,  10) /   0.883778045697D-06/
      data y_data(    85,  11) /   0.208586780104D-06/
      data y_data(    85,  12) /   0.744075664403D+00/
      data x_data(    86     ) /   0.130000000000D+01/
      data y_data(    86,   1) /   0.116254287623D+04/
      data y_data(    86,   2) /   0.983232869029D+01/
      data y_data(    86,   3) /   0.287397720268D-03/
      data y_data(    86,   4) /   0.179746675666D-04/
      data y_data(    86,   5) /   0.707554923781D-07/
      data y_data(    86,   6) /   0.224531088249D-05/
      data y_data(    86,   7) /   0.140320266222D+00/
      data y_data(    86,   8) /   0.362071691845D-04/
      data y_data(    86,   9) /   0.115544402074D+00/
      data y_data(    86,  10) /   0.574035203697D-06/
      data y_data(    86,  11) /   0.161091235992D-06/
      data y_data(    86,  12) /   0.744078098674D+00/
      data x_data(    87     ) /   0.160000000000D+01/
      data y_data(    87,   1) /   0.116285523253D+04/
      data y_data(    87,   2) /   0.983490791155D+01/
      data y_data(    87,   3) /   0.287322349729D-03/
      data y_data(    87,   4) /   0.400886488866D-05/
      data y_data(    87,   5) /   0.925301209880D-08/
      data y_data(    87,   6) /   0.591853984728D-06/
      data y_data(    87,   7) /   0.140312590285D+00/
      data y_data(    87,   8) /   0.197422604616D-04/
      data y_data(    87,   9) /   0.115580218020D+00/
      data y_data(    87,  10) /   0.147931914856D-06/
      data y_data(    87,  11) /   0.621179450633D-07/
      data y_data(    87,  12) /   0.744082629413D+00/
      data x_data(    88     ) /   0.180000000000D+01/
      data y_data(    88,   1) /   0.116292052863D+04/
      data y_data(    88,   2) /   0.983544756642D+01/
      data y_data(    88,   3) /   0.287306584823D-03/
      data y_data(    88,   4) /   0.181060170009D-05/
      data y_data(    88,   5) /   0.360211740592D-08/
      data y_data(    88,   6) /   0.335717837266D-06/
      data y_data(    88,   7) /   0.140311761453D+00/
      data y_data(    88,   8) /   0.151982114553D-04/
      data y_data(    88,   9) /   0.115587370272D+00/
      data y_data(    88,  10) /   0.776613230195D-07/
      data y_data(    88,  11) /   0.400369825313D-07/
      data y_data(    88,  12) /   0.744083402443D+00/
      data x_data(    89     ) /   0.200000000000D+01/
      data y_data(    89,   1) /   0.116292052863D+04/
      data y_data(    89,   2) /   0.983544756642D+01/
      data y_data(    89,   3) /   0.287306584823D-03/
      data y_data(    89,   4) /   0.181060170009D-05/
      data y_data(    89,   5) /   0.360211740592D-08/
      data y_data(    89,   6) /   0.335717837266D-06/
      data y_data(    89,   7) /   0.140311761453D+00/
      data y_data(    89,   8) /   0.151982114553D-04/
      data y_data(    89,   9) /   0.115587370272D+00/
      data y_data(    89,  10) /   0.776613230195D-07/
      data y_data(    89,  11) /   0.400369825313D-07/
      data y_data(    89,  12) /   0.744083402443D+00/
c                                                 
c     interpolation routine                       
c                                                 
      lo_loside = 0
      lo_hiside = 0
      hi_loside = 0
      hi_hiside = 0
      if (xlo .le. x_data(1)) then
         lo_loside = 1
         lo_hiside = 1
      end if
      if (xhi .le. x_data(1)) then
         hi_loside = 1
         hi_hiside = 1
      end if
      if (xlo .ge. x_data(N)) then
         lo_loside = N
         lo_hiside = N
      end if
      if (xhi .ge. x_data(N)) then
         hi_loside = N
         hi_hiside = N
      end if
      if (lo_loside.eq.0) then
         do i = 1, N-1                           
            if ( (xlo .ge. x_data(i))
     &           .and.
     &           (xlo .le. x_data(i+1)) ) then
               lo_loside  = i
               lo_hiside  = i+1
            end if
         end do
      end if
      if (hi_loside.eq.0) then            
         do i = 1, N-1                           
            if ( (xhi .ge. x_data(i))
     &           .and.
     &           (xhi .le. x_data(i+1)) ) then
               hi_loside = i
               hi_hiside = i + 1
            end if
         end do
      end if
         
      do j = 1, M
         
         x1 = x_data(lo_loside)
         y1 = y_data(lo_loside,j)
         
         x2 = x_data(lo_hiside)
         y2 = y_data(lo_hiside,j)
          
         if (lo_loside.eq.lo_hiside) then
            dydx = 0.d0
         else
            dydx = (y2-y1)/(x2-x1)
         end if
         
         ylo = y1 + dydx*(xlo - x1)
         
         if (lo_loside .eq. hi_loside) then
            
            yhi = y1 + dydx*(xhi - x1)
            
            y_vector(j) = 0.5d0*(ylo + yhi)
            
         else
            
            sum = (x2 - xlo) * 0.5d0 * (ylo + y2)
            
            x1 = x_data(hi_loside)
            y1 = y_data(hi_loside,j)
         
            x2 = x_data(hi_hiside)
            y2 = y_data(hi_hiside,j)
            
            if (hi_loside.eq.hi_hiside) then
               dydx = 0.d0
            else
               dydx = (y2-y1)/(x2-x1)
            end if
            
            yhi = y1 + dydx*(xhi - x1)
            
            sum = sum + (xhi - x1)*0.5d0*(yhi+y1)
            
            do k = lo_hiside,hi_loside-1
               
               sum = sum + (x_data(k+1)-x_data(k))
     &              * 0.5d0
     &              * (y_data(k,j) + y_data(k+1,j))
               
            end do
            
            y_vector(j) = sum / (xhi - xlo)
            
         end if
      end do
      end                                         
c     LAST LINE                                   
c-------------------------------------------------
