ifeq (${CHEMISTRY_MODEL}, DRM19)
  CHEM_MECHFILE = drm19.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/gri/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/gri
endif
ifeq (${CHEMISTRY_MODEL}, CHEMH)
  CHEM_MECHFILE = chem-H.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/chem-H/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/chem-H
endif
ifeq (${CHEMISTRY_MODEL}, LIDRY)
  CHEM_MECHFILE = LiDryer.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/LiDryer/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/LiDryer
endif
ifeq (${CHEMISTRY_MODEL}, LIDRYMOD)
  CHEM_MECHFILE = LiDryerMOD.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/LiDryer/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/LiDryer
endif
ifeq (${CHEMISTRY_MODEL}, GRI12)
  CHEM_MECHFILE = grimech12.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/gri/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/gri
endif
ifeq (${CHEMISTRY_MODEL}, GRI30)
  CHEM_MECHFILE = grimech30.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/gri/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/gri
endif
ifeq (${CHEMISTRY_MODEL}, GRI30_noArN)
  CHEM_MECHFILE = grimech30-noArN.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/gri/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/gri
endif
ifeq (${CHEMISTRY_MODEL}, GLARSKEL)
  CHEM_MECHFILE = glarSkel.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/glar/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/glar
endif
ifeq (${CHEMISTRY_MODEL}, LUDME)
  CHEM_MECHFILE = LuDME.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/Lu/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/Lu
endif
ifeq (${CHEMISTRY_MODEL},WANGDODECANE)
  CHEM_MECHFILE = dodecane_wang.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/dodecane_wang/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/dodecane_wang
endif
ifeq (${CHEMISTRY_MODEL},DODECANE_LU)
  CHEM_MECHFILE = dodecane_lu.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/dodecane_lu/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/dodecane_lu
endif
ifeq (${CHEMISTRY_MODEL},DODECANEZHAO)
  CHEM_MECHFILE = dodecane_zhao_1.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/dodecane_zhao_1/PMFs
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/dodecane_zhao_1
endif
ifeq (${CHEMISTRY_MODEL}, BURKE)
  CHEM_MECHFILE = BurkeDryer.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/BurkeDryer
endif
ifeq (${CHEMISTRY_MODEL}, BURKEMOD)
  CHEM_MECHFILE = BurkeDryer_mod.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/BurkeDryer_mod
endif
ifeq (${CHEMISTRY_MODEL}, ALZETA)
  CHEM_MECHFILE = alzeta.c
  VPATH_LOCATIONS += ${CHEMISTRY_DIR}/data/Alzeta
endif
