c      implicit none
c      double precision x,y,u,v,w,dx,L
c      integer N
c      parameter (N=256)
c      integer i,j
c      L = .25
c      dx = (L/2)/(N/2)
c      print *,'VARIABLES = X Y Vx Vy Vz'
c      print *,'ZONE I=',N,' J=',N,' F=POINT'
c      do j=1,N
c         y = -L/2 + (j-.5d0)*dx
c         do i=1,N
c            x = -L/2 + (i-.5d0)*dx
c            call vswirlXYZ(x,y,u,v,w)
c            print *,x,y,u,v,w
c         enddo
c      enddo
c      end

      implicit none
      double precision dr,L,r1,r2,r,v1(3),v2(3),Pi,A,T,At,v,Rtran,eta
      double precision Rfu,Rpipe,eta1,eta2
      integer N,M
      parameter (N=10000)
      integer i,j
      L = 30
      dr = DBLE(L)/DBLE(N)
      Pi = 2*ACOS(0.d0)
      Rtran = 1.d0
      Rfu = 27.5d0
      Rpipe = 25.d0
      At = 0.d0
      T = 0.d0
      do i=1,N
         r1 = (i-1)*dr
         r2 = (i  )*dr
         r = 0.5*(r1+r2)
         call vswirl(r1,v1,M)
         call vswirl(r2,v2,M)
         if (r.gt.Rfu) then
            eta1 = TANH(2*(r1-Rfu)/Rtran)
            eta2 = TANH(2*(r2-Rfu)/Rtran)
            do j=1,3
               v1(j) = (1.d0 - eta1)*v1(j)
               v2(j) = (1.d0 - eta2)*v2(j)
            enddo
         endif
         A = 2*r*Pi*dr
         v = 0.5*(v1(3) + v2(3))
         T = T + v*A
         At = At + A
      enddo
      print *,'Area =',At,Pi*L**2
      print *,'Mean flow =',T/At
      print *,'Mean bulk flow through pipe =',T/(Pi*Rpipe**2)
      end

      subroutine vswirlXYZ(x,y,u,v,w)
      implicit none
      double precision x,y,vel(3),u,v,w,r,eps
      integer N
      parameter (eps=1.e-9)

c     x,y come in as MKS.  Convert to mm.  Result already in MKS
      r = SQRT( x*x + y*y ) * 1000
      call vswirl(r,vel,N)

      if (r.lt.eps) then
         u = 0.d0
         v = 0.d0
      else
         u = 1000*(x*vel(1) - y*vel(2))/r
         v = 1000*(y*vel(1) + x*vel(2))/r
      endif
      w = vel(3)

      end


c-------------------------------------------------
c                                                 
c                                                 
c                              -USAGE-            
c                                                 
c     OVERVIEW: call vswirl    (x,y,Niny)   
c     interpolates y(x). Here x is a scalar, y    
c     a vector, with Niny components used. Piece- 
c     constant Extrapolation is applied to points 
c     laying outside the range of the orig data   
c                                                 
c     domain: x in [ 0.00000E+00, 0.27669E+02]  
c     number of states in vector y:     3         
c     number of x data points:   399              
c                                                 
c     CALLING PROGRAM NEEDS: none                 
c     PROCEDURE NEEDS:  none                      
c     COMPILER NEEDS: f77, long names (14 char)   
c     SYSTEM NEEDS: none                          
c     NOTES: This routine was generated by        
c     subroutine makeRoutine.                     
c                                                 
c-------------------------------------------------
c                                                 
c                          -SPECIFICATION-        
c     SYNTAX:                                     
c     subroutine vswirl    (x:dp,y:dp arr, Niny: int)      
c     returns: none                               
c     REQUIRES: none                              
c     MODIFIES: y, N                              
c     SIGNALS: none                               
c     EFFECTS: computes the value of y at x       
c     and returns number of components used, N.   
c                                                 
c-------------------------------------------------
c                                                 
c                         -IMPLEMENTATION-        
c     AUTHOR: auto-generated by makeAveInterp     
c     MODIFICATION HISTORY: none                  
c     NOTES: interpolation x,y data is defined in 
c     data statements for efficiency.             
c     REQUIRES: none                              
c     LOCAL VARIABLES:                            
c     x...............(dp) interpolate y here
c     y_vector........(1D dp arr) computed y(x)   
c     Niny............(int) no. of used components
c     x_data..........(dp) x data points          
c     y_data..........(dp) y(x) data points       
c     N...............(int) number of x points    
c     M...............(int) dimension of y_data   
c     i,j,k...........(int) loop index            
c     loside..........(int) idx of data below x   
c     hiside..........(int) idx of data above x   
c     x1..............(dp) interpolation point    
c     x2..............(dp) interpolation point    
c     y1..............(dp) interpolation value    
c     y2..............(dp) interpolation value    
c     dydx............(dp) slope of linear interp 
c     y...............(dp) value at x             
c     GLOBAL VARIABLES:none                       
c     PROCEDURES: none                            
c     FILES: none                                 
c     I/O: none                                   
c-------------------------------------------------
c                                                 
c                             -CODE-              
c     FIRST LINE:                                 
      subroutine vswirl    (x,y_vector,Niny)
c                                                 
c     declare local variables                     
c                                                 
      integer N,M,i,j,k,loside,hiside,Niny        
      double precision x,y_vector(*)              
      double precision y,x1,y1,x2,y2,dydx         
      double precision x_data(   399)              
      double precision y_data(   399,     3)        
      data N,M /   399,     3/                   
      Niny =      3                                
c                                                 
c     interpolation x,y data                      
c                                                 
      data x_data(     1     ) /   0.000000000000E+00/
      data y_data(     1,   1) /   0.E0/
      data y_data(     1,   2) /   0.E0/
      data y_data(     1,   3) /   0.349565764553E+01/
      data x_data(     2     ) /   0.206480000000E-01/
      data y_data(     2,   1) /   0.463122760280E-03/
      data y_data(     2,   2) /  -0.924471103854E-03/
      data y_data(     2,   3) /   0.349565764553E+01/
      data x_data(     3     ) /   0.904660000000E-01/
      data y_data(     3,   1) /   0.202889257785E-02/
      data y_data(     3,   2) /  -0.405341315993E-02/
      data y_data(     3,   3) /   0.349565664000E+01/
      data x_data(     4     ) /   0.160285000000E+00/
      data y_data(     4,   1) /   0.359617159369E-02/
      data y_data(     4,   2) /  -0.719078196479E-02/
      data y_data(     4,   3) /   0.349566455405E+01/
      data x_data(     5     ) /   0.230104000000E+00/
      data y_data(     5,   1) /   0.516085453816E-02/
      data y_data(     5,   2) /  -0.103192331314E-01/
      data y_data(     5,   3) /   0.349567125832E+01/
      data x_data(     6     ) /   0.299922000000E+00/
      data y_data(     6,   1) /   0.662416649002E-02/
      data y_data(     6,   2) /  -0.119250000215E-01/
      data y_data(     6,   3) /   0.349584893965E+01/
      data x_data(     7     ) /   0.369741000000E+00/
      data y_data(     7,   1) /   0.801417014709E-02/
      data y_data(     7,   2) /  -0.124832471534E-01/
      data y_data(     7,   3) /   0.349614376395E+01/
      data x_data(     8     ) /   0.439559000000E+00/
      data y_data(     8,   1) /   0.939937075682E-02/
      data y_data(     8,   2) /  -0.130438018849E-01/
      data y_data(     8,   3) /   0.349643516525E+01/
      data x_data(     9     ) /   0.509378000000E+00/
      data y_data(     9,   1) /   0.107793744110E-01/
      data y_data(     9,   2) /  -0.136060490841E-01/
      data y_data(     9,   3) /   0.349672219379E+01/
      data x_data(    10     ) /   0.579197000000E+00/
      data y_data(    10,   1) /   0.121540786749E-01/
      data y_data(    10,   2) /  -0.141703021814E-01/
      data y_data(    10,   3) /   0.349700510232E+01/
      data x_data(    11     ) /   0.649015000000E+00/
      data y_data(    11,   1) /   0.135235750236E-01/
      data y_data(    11,   2) /  -0.147360610802E-01/
      data y_data(    11,   3) /   0.349728441219E+01/
      data x_data(    12     ) /   0.718834000000E+00/
      data y_data(    12,   1) /   0.148885786749E-01/
      data y_data(    12,   2) /  -0.153041041121E-01/
      data y_data(    12,   3) /   0.349755923643E+01/
      data x_data(    13     ) /   0.788652000000E+00/
      data y_data(    13,   1) /   0.162485750236E-01/
      data y_data(    13,   2) /  -0.158743629437E-01/
      data y_data(    13,   3) /   0.349783034205E+01/
      data x_data(    14     ) /   0.858471000000E+00/
      data y_data(    14,   1) /   0.176037829387E-01/
      data y_data(    14,   2) /  -0.164464060428E-01/
      data y_data(    14,   3) /   0.349809746202E+01/
      data x_data(    15     ) /   0.928290000000E+00/
      data y_data(    15,   1) /   0.186764872026E-01/
      data y_data(    15,   2) /  -0.159421591401E-01/
      data y_data(    15,   3) /   0.349842227907E+01/
      data x_data(    16     ) /   0.998108000000E+00/
      data y_data(    16,   1) /   0.197522792904E-01/
      data y_data(    16,   2) /  -0.154484178722E-01/
      data y_data(    16,   3) /   0.349874788472E+01/
      data x_data(    17     ) /   0.106792700000E+01/
      data y_data(    17,   1) /   0.208309872026E-01/
      data y_data(    17,   2) /  -0.149646653347E-01/
      data y_data(    17,   3) /   0.349907420892E+01/
      data x_data(    18     ) /   0.113774500000E+01/
      data y_data(    18,   1) /   0.219126878241E-01/
      data y_data(    18,   2) /  -0.144917197356E-01/
      data y_data(    18,   3) /   0.349940081459E+01/
      data x_data(    19     ) /   0.120756400000E+01/
      data y_data(    19,   1) /   0.229974872026E-01/
      data y_data(    19,   2) /  -0.140294672654E-01/
      data y_data(    19,   3) /   0.349972863877E+01/
      data x_data(    20     ) /   0.127738300000E+01/
      data y_data(    20,   1) /   0.240856914665E-01/
      data y_data(    20,   2) /  -0.135772203627E-01/
      data y_data(    20,   3) /   0.350005775156E+01/
      data x_data(    21     ) /   0.134720100000E+01/
      data y_data(    21,   1) /   0.251758920909E-01/
      data y_data(    21,   2) /  -0.131357746641E-01/
      data y_data(    21,   3) /   0.350038735726E+01/
      data x_data(    22     ) /   0.141702000000E+01/
      data y_data(    22,   1) /   0.264456544565E-01/
      data y_data(    22,   2) /  -0.134165633925E-01/
      data y_data(    22,   3) /   0.350041987513E+01/
      data x_data(    23     ) /   0.148683800000E+01/
      data y_data(    23,   1) /   0.278403533401E-01/
      data y_data(    23,   2) /  -0.141923087241E-01/
      data y_data(    23,   3) /   0.350024916673E+01/
      data x_data(    24     ) /   0.155665700000E+01/
      data y_data(    24,   1) /   0.292381544565E-01/
      data y_data(    24,   2) /  -0.149670571979E-01/
      data y_data(    24,   3) /   0.350008205808E+01/
      data x_data(    25     ) /   0.162647600000E+01/
      data y_data(    25,   1) /   0.306388587204E-01/
      data y_data(    25,   2) /  -0.157420998367E-01/
      data y_data(    25,   3) /   0.349991864955E+01/
      data x_data(    26     ) /   0.169629400000E+01/
      data y_data(    26,   1) /   0.320426490733E-01/
      data y_data(    26,   2) /  -0.165163452620E-01/
      data y_data(    26,   3) /   0.349975873687E+01/
      data x_data(    27     ) /   0.176611300000E+01/
      data y_data(    27,   1) /   0.334501544565E-01/
      data y_data(    27,   2) /  -0.172895936421E-01/
      data y_data(    27,   3) /   0.349960203676E+01/
      data x_data(    28     ) /   0.183593100000E+01/
      data y_data(    28,   1) /   0.348606490733E-01/
      data y_data(    28,   2) /  -0.180626348649E-01/
      data y_data(    28,   3) /   0.349944891980E+01/
      data x_data(    29     ) /   0.190575000000E+01/
      data y_data(    29,   1) /   0.362749501926E-01/
      data y_data(    29,   2) /  -0.188353831837E-01/
      data y_data(    29,   3) /   0.349929951544E+01/
      data x_data(    30     ) /   0.197556900000E+01/
      data y_data(    30,   1) /   0.376916544565E-01/
      data y_data(    30,   2) /  -0.196071300864E-01/
      data y_data(    30,   3) /   0.349915381118E+01/
      data x_data(    31     ) /   0.204538700000E+01/
      data y_data(    31,   1) /   0.402669448065E-01/
      data y_data(    31,   2) /  -0.203936714028E-01/
      data y_data(    31,   3) /   0.349858939846E+01/
      data x_data(    32     ) /   0.211520600000E+01/
      data y_data(    32,   1) /   0.428371544565E-01/
      data y_data(    32,   2) /  -0.211729196279E-01/
      data y_data(    32,   3) /   0.349802478986E+01/
      data x_data(    33     ) /   0.218502400000E+01/
      data y_data(    33,   1) /   0.454019448065E-01/
      data y_data(    33,   2) /  -0.219451652726E-01/
      data y_data(    33,   3) /   0.349746008140E+01/
      data x_data(    34     ) /   0.225484300000E+01/
      data y_data(    34,   1) /   0.479614501926E-01/
      data y_data(    34,   2) /  -0.227094134333E-01/
      data y_data(    34,   3) /   0.349689517706E+01/
      data x_data(    35     ) /   0.232466200000E+01/
      data y_data(    35,   1) /   0.505159501926E-01/
      data y_data(    35,   2) /  -0.234664560721E-01/
      data y_data(    35,   3) /   0.349633026854E+01/
      data x_data(    36     ) /   0.239448000000E+01/
      data y_data(    36,   1) /   0.530652405397E-01/
      data y_data(    36,   2) /  -0.242167018104E-01/
      data y_data(    36,   3) /   0.349576565153E+01/
      data x_data(    37     ) /   0.246429900000E+01/
      data y_data(    37,   1) /   0.556094501926E-01/
      data y_data(    37,   2) /  -0.249597456137E-01/
      data y_data(    37,   3) /   0.349520045148E+01/
      data x_data(    38     ) /   0.253411700000E+01/
      data y_data(    38,   1) /   0.579956422126E-01/
      data y_data(    38,   2) /  -0.255981951932E-01/
      data y_data(    38,   3) /   0.349516844994E+01/
      data x_data(    39     ) /   0.260393600000E+01/
      data y_data(    39,   1) /   0.602714418282E-01/
      data y_data(    39,   2) /  -0.261672654865E-01/
      data y_data(    39,   3) /   0.349550375517E+01/
      data x_data(    40     ) /   0.267375500000E+01/
      data y_data(    40,   1) /   0.625421460920E-01/
      data y_data(    40,   2) /  -0.267378356393E-01/
      data y_data(    40,   3) /   0.349583884665E+01/
      data x_data(    41     ) /   0.274357300000E+01/
      data y_data(    41,   1) /   0.648074379458E-01/
      data y_data(    41,   2) /  -0.273093141239E-01/
      data y_data(    41,   3) /   0.349617363287E+01/
      data x_data(    42     ) /   0.281339200000E+01/
      data y_data(    42,   1) /   0.670679418282E-01/
      data y_data(    42,   2) /  -0.278823844727E-01/
      data y_data(    42,   3) /   0.349650773385E+01/
      data x_data(    43     ) /   0.288321000000E+01/
      data y_data(    43,   1) /   0.693232336790E-01/
      data y_data(    43,   2) /  -0.284561586554E-01/
      data y_data(    43,   3) /   0.349684202007E+01/
      data x_data(    44     ) /   0.295302900000E+01/
      data y_data(    44,   1) /   0.715734418282E-01/
      data y_data(    44,   2) /  -0.290314333061E-01/
      data y_data(    44,   3) /   0.349717562106E+01/
      data x_data(    45     ) /   0.302284800000E+01/
      data y_data(    45,   1) /   0.738182375643E-01/
      data y_data(    45,   2) /  -0.296080034589E-01/
      data y_data(    45,   3) /   0.349750891680E+01/
      data x_data(    46     ) /   0.309266600000E+01/
      data y_data(    46,   1) /   0.760580294122E-01/
      data y_data(    46,   2) /  -0.301854818528E-01/
      data y_data(    46,   3) /   0.349784170301E+01/
      data x_data(    47     ) /   0.316248500000E+01/
      data y_data(    47,   1) /   0.768322375643E-01/
      data y_data(    47,   2) /  -0.299553480285E-01/
      data y_data(    47,   3) /   0.349779959974E+01/
      data x_data(    48     ) /   0.323230300000E+01/
      data y_data(    48,   1) /   0.776120294122E-01/
      data y_data(    48,   2) /  -0.297303263843E-01/
      data y_data(    48,   3) /   0.349775659021E+01/
      data x_data(    49     ) /   0.330212200000E+01/
      data y_data(    49,   1) /   0.783985333004E-01/
      data y_data(    49,   2) /  -0.295103968619E-01/
      data y_data(    49,   3) /   0.349771369122E+01/
      data x_data(    50     ) /   0.337194100000E+01/
      data y_data(    50,   1) /   0.791905333004E-01/
      data y_data(    50,   2) /  -0.292946712786E-01/
      data y_data(    50,   3) /   0.349767028269E+01/
      data x_data(    51     ) /   0.344175900000E+01/
      data y_data(    51,   1) /   0.799883251454E-01/
      data y_data(    51,   2) /  -0.290844453150E-01/
      data y_data(    51,   3) /   0.349762627314E+01/
      data x_data(    52     ) /   0.351157800000E+01/
      data y_data(    52,   1) /   0.807928290365E-01/
      data y_data(    52,   2) /  -0.288782201120E-01/
      data y_data(    52,   3) /   0.349758137416E+01/
      data x_data(    53     ) /   0.358139600000E+01/
      data y_data(    53,   1) /   0.816028251454E-01/
      data y_data(    53,   2) /  -0.286777898465E-01/
      data y_data(    53,   3) /   0.349753695607E+01/
      data x_data(    54     ) /   0.365121500000E+01/
      data y_data(    54,   1) /   0.822168412681E-01/
      data y_data(    54,   2) /  -0.291191717512E-01/
      data y_data(    54,   3) /   0.349688491086E+01/
      data x_data(    55     ) /   0.372103400000E+01/
      data y_data(    55,   1) /   0.826968412681E-01/
      data y_data(    55,   2) /  -0.300059461679E-01/
      data y_data(    55,   3) /   0.349580827055E+01/
      data x_data(    56     ) /   0.379085200000E+01/
      data y_data(    56,   1) /   0.831837265748E-01/
      data y_data(    56,   2) /  -0.308977138059E-01/
      data y_data(    56,   3) /   0.349472383103E+01/
      data x_data(    57     ) /   0.386067100000E+01/
      data y_data(    57,   1) /   0.836772284765E-01/
      data y_data(    57,   2) /  -0.317942907375E-01/
      data y_data(    57,   3) /   0.349363060273E+01/
      data x_data(    58     ) /   0.393048900000E+01/
      data y_data(    58,   1) /   0.841773180412E-01/
      data y_data(    58,   2) /  -0.326957626042E-01/
      data y_data(    58,   3) /   0.349252875477E+01/
      data x_data(    59     ) /   0.400030800000E+01/
      data y_data(    59,   1) /   0.846841156848E-01/
      data y_data(    59,   2) /  -0.336013395709E-01/
      data y_data(    59,   3) /   0.349141852638E+01/
      data x_data(    60     ) /   0.407012700000E+01/
      data y_data(    60,   1) /   0.851969114210E-01/
      data y_data(    60,   2) /  -0.345129097237E-01/
      data y_data(    60,   3) /   0.349029938608E+01/
      data x_data(    61     ) /   0.413994500000E+01/
      data y_data(    61,   1) /   0.857165009740E-01/
      data y_data(    61,   2) /  -0.354288815348E-01/
      data y_data(    61,   3) /   0.348917244678E+01/
      data x_data(    62     ) /   0.420976400000E+01/
      data y_data(    62,   1) /   0.862422986293E-01/
      data y_data(    62,   2) /  -0.363491628210E-01/
      data y_data(    62,   3) /   0.348803651399E+01/
      data x_data(    63     ) /   0.427958200000E+01/
      data y_data(    63,   1) /   0.871475924403E-01/
      data y_data(    63,   2) /  -0.381472260663E-01/
      data y_data(    63,   3) /   0.348707637051E+01/
      data x_data(    64     ) /   0.434940100000E+01/
      data y_data(    64,   1) /   0.880508901015E-01/
      data y_data(    64,   2) /  -0.399500073905E-01/
      data y_data(    64,   3) /   0.348611164191E+01/
      data x_data(    65     ) /   0.441922000000E+01/
      data y_data(    65,   1) /   0.889529815738E-01/
      data y_data(    65,   2) /  -0.417562818072E-01/
      data y_data(    65,   3) /   0.348514250160E+01/
      data x_data(    66     ) /   0.448903800000E+01/
      data y_data(    66,   1) /   0.898537753731E-01/
      data y_data(    66,   2) /  -0.435673449970E-01/
      data y_data(    66,   3) /   0.348416906252E+01/
      data x_data(    67     ) /   0.455885700000E+01/
      data y_data(    67,   1) /   0.907528687821E-01/
      data y_data(    67,   2) /  -0.453823306407E-01/
      data y_data(    67,   3) /   0.348319192526E+01/
      data x_data(    68     ) /   0.462867500000E+01/
      data y_data(    68,   1) /   0.916506625727E-01/
      data y_data(    68,   2) /  -0.472013937953E-01/
      data y_data(    68,   3) /   0.348220969052E+01/
      data x_data(    69     ) /   0.469849400000E+01/
      data y_data(    69,   1) /   0.925469602544E-01/
      data y_data(    69,   2) /  -0.490246752102E-01/
      data y_data(    69,   3) /   0.348122355317E+01/
      data x_data(    70     ) /   0.476831300000E+01/
      data y_data(    70,   1) /   0.929967646056E-01/
      data y_data(    70,   2) /  -0.511586279809E-01/
      data y_data(    70,   3) /   0.348013079243E+01/
      data x_data(    71     ) /   0.483813100000E+01/
      data y_data(    71,   1) /   0.931389499842E-01/
      data y_data(    71,   2) /  -0.535027733822E-01/
      data y_data(    71,   3) /   0.347896856498E+01/
      data x_data(    72     ) /   0.490795000000E+01/
      data y_data(    72,   1) /   0.932814262307E-01/
      data y_data(    72,   2) /  -0.558413473696E-01/
      data y_data(    72,   3) /   0.347781334127E+01/
      data x_data(    73     ) /   0.497776800000E+01/
      data y_data(    73,   1) /   0.934241115830E-01/
      data y_data(    73,   2) /  -0.581739928528E-01/
      data y_data(    73,   3) /   0.347666390951E+01/
      data x_data(    74     ) /   0.504758700000E+01/
      data y_data(    74,   1) /   0.935665878557E-01/
      data y_data(    74,   2) /  -0.605003624944E-01/
      data y_data(    74,   3) /   0.347552068584E+01/
      data x_data(    75     ) /   0.511740600000E+01/
      data y_data(    75,   1) /   0.937089750641E-01/
      data y_data(    75,   2) /  -0.628215179249E-01/
      data y_data(    75,   3) /   0.347438425599E+01/
      data x_data(    76     ) /   0.518722400000E+01/
      data y_data(    76,   1) /   0.938509561145E-01/
      data y_data(    76,   2) /  -0.651368677920E-01/
      data y_data(    76,   3) /   0.347325352844E+01/
      data x_data(    77     ) /   0.525704300000E+01/
      data y_data(    77,   1) /   0.939936366892E-01/
      data y_data(    77,   2) /  -0.674467373136E-01/
      data y_data(    77,   3) /   0.347212960056E+01/
      data x_data(    78     ) /   0.532686100000E+01/
      data y_data(    78,   1) /   0.941361177132E-01/
      data y_data(    78,   2) /  -0.697500872626E-01/
      data y_data(    78,   3) /   0.347101157724E+01/
      data x_data(    79     ) /   0.539668000000E+01/
      data y_data(    79,   1) /   0.932350025781E-01/
      data y_data(    79,   2) /  -0.713817524384E-01/
      data y_data(    79,   3) /   0.347101844513E+01/
      data x_data(    80     ) /   0.546649900000E+01/
      data y_data(    80,   1) /   0.923369812587E-01/
      data y_data(    80,   2) /  -0.730091121328E-01/
      data y_data(    80,   3) /   0.347103142381E+01/
      data x_data(    81     ) /   0.553631700000E+01/
      data y_data(    81,   1) /   0.914421665115E-01/
      data y_data(    81,   2) /  -0.746334622017E-01/
      data y_data(    81,   3) /   0.347105049190E+01/
      data x_data(    82     ) /   0.560613600000E+01/
      data y_data(    82,   1) /   0.905501428837E-01/
      data y_data(    82,   2) /  -0.762533315215E-01/
      data y_data(    82,   3) /   0.347107576838E+01/
      data x_data(    83     ) /   0.567595400000E+01/
      data y_data(    83,   1) /   0.896613281102E-01/
      data y_data(    83,   2) /  -0.778699774055E-01/
      data y_data(    83,   3) /   0.347110683643E+01/
      data x_data(    84     ) /   0.574577300000E+01/
      data y_data(    84,   1) /   0.887755087727E-01/
      data y_data(    84,   2) /  -0.794828466463E-01/
      data y_data(    84,   3) /   0.347114411295E+01/
      data x_data(    85     ) /   0.581559200000E+01/
      data y_data(    85,   1) /   0.878926917172E-01/
      data y_data(    85,   2) /  -0.810920020768E-01/
      data y_data(    85,   3) /   0.347118768310E+01/
      data x_data(    86     ) /   0.588541000000E+01/
      data y_data(    86,   1) /   0.871188408577E-01/
      data y_data(    86,   2) /  -0.818842903334E-01/
      data y_data(    86,   3) /   0.347085516381E+01/
      data x_data(    87     ) /   0.595522900000E+01/
      data y_data(    87,   1) /   0.864191567195E-01/
      data y_data(    87,   2) /  -0.821151789198E-01/
      data y_data(    87,   3) /   0.347026188777E+01/
      data x_data(    88     ) /   0.602504800000E+01/
      data y_data(    88,   1) /   0.857184720129E-01/
      data y_data(    88,   2) /  -0.823515681486E-01/
      data y_data(    88,   3) /   0.346966761096E+01/
      data x_data(    89     ) /   0.609486600000E+01/
      data y_data(    89,   1) /   0.850170865667E-01/
      data y_data(    89,   2) /  -0.825919533365E-01/
      data y_data(    89,   3) /   0.346907324747E+01/
      data x_data(    90     ) /   0.616468500000E+01/
      data y_data(    90,   1) /   0.843146993583E-01/
      data y_data(    90,   2) /  -0.828373405448E-01/
      data y_data(    90,   3) /   0.346847826879E+01/
      data x_data(    91     ) /   0.623450300000E+01/
      data y_data(    91,   1) /   0.836115176602E-01/
      data y_data(    91,   2) /  -0.830872263313E-01/
      data y_data(    91,   3) /   0.346788320035E+01/
      data x_data(    92     ) /   0.630432200000E+01/
      data y_data(    92,   1) /   0.829076292055E-01/
      data y_data(    92,   2) /  -0.833416149615E-01/
      data y_data(    92,   3) /   0.346728712848E+01/
      data x_data(    93     ) /   0.637414100000E+01/
      data y_data(    93,   1) /   0.822029444269E-01/
      data y_data(    93,   2) /  -0.836010042539E-01/
      data y_data(    93,   3) /   0.346669105579E+01/
      data x_data(    94     ) /   0.644395900000E+01/
      data y_data(    94,   1) /   0.814967633166E-01/
      data y_data(    94,   2) /  -0.838648893782E-01/
      data y_data(    94,   3) /   0.346609457965E+01/
      data x_data(    95     ) /   0.651377800000E+01/
      data y_data(    95,   1) /   0.816103761082E-01/
      data y_data(    95,   2) /  -0.829507765866E-01/
      data y_data(    95,   3) /   0.346729271376E+01/
      data x_data(    96     ) /   0.658359600000E+01/
      data y_data(    96,   1) /   0.817199901959E-01/
      data y_data(    96,   2) /  -0.820346623292E-01/
      data y_data(    96,   3) /   0.346848994115E+01/
      data x_data(    97     ) /   0.665341500000E+01/
      data y_data(    97,   1) /   0.818253059554E-01/
      data y_data(    97,   2) /  -0.811165510033E-01/
      data y_data(    97,   3) /   0.346968666493E+01/
      data x_data(    98     ) /   0.672323400000E+01/
      data y_data(    98,   1) /   0.819264168409E-01/
      data y_data(    98,   2) /  -0.801964403592E-01/
      data y_data(    98,   3) /   0.347088179636E+01/
      data x_data(    99     ) /   0.679305200000E+01/
      data y_data(    99,   1) /   0.820227358026E-01/
      data y_data(    99,   2) /  -0.792743254200E-01/
      data y_data(    99,   3) /   0.347207582036E+01/
      data x_data(   100     ) /   0.686287100000E+01/
      data y_data(   100,   1) /   0.821148485942E-01/
      data y_data(   100,   2) /  -0.783502126284E-01/
      data y_data(   100,   3) /   0.347326875020E+01/
      data x_data(   101     ) /   0.693268900000E+01/
      data y_data(   101,   1) /   0.822026669985E-01/
      data y_data(   101,   2) /  -0.774240983271E-01/
      data y_data(   101,   3) /   0.347446068196E+01/
      data x_data(   102     ) /   0.700250800000E+01/
      data y_data(   102,   1) /   0.820680251866E-01/
      data y_data(   102,   2) /  -0.770779957247E-01/
      data y_data(   102,   3) /   0.347673489130E+01/
      data x_data(   103     ) /   0.707232700000E+01/
      data y_data(   103,   1) /   0.817819774986E-01/
      data y_data(   103,   2) /  -0.771327807013E-01/
      data y_data(   103,   3) /   0.347976026994E+01/
      data x_data(   104     ) /   0.714214500000E+01/
      data y_data(   104,   1) /   0.814978484367E-01/
      data y_data(   104,   2) /  -0.771875445581E-01/
      data y_data(   104,   3) /   0.348279162308E+01/
      data x_data(   105     ) /   0.721196400000E+01/
      data y_data(   105,   1) /   0.812161015340E-01/
      data y_data(   105,   2) /  -0.772416147109E-01/
      data y_data(   105,   3) /   0.348582978470E+01/
      data x_data(   106     ) /   0.728178200000E+01/
      data y_data(   106,   1) /   0.809364708313E-01/
      data y_data(   106,   2) /  -0.772953817783E-01/
      data y_data(   106,   3) /   0.348887414170E+01/
      data x_data(   107     ) /   0.735160100000E+01/
      data y_data(   107,   1) /   0.806584247841E-01/
      data y_data(   107,   2) /  -0.773489592804E-01/
      data y_data(   107,   3) /   0.349192451648E+01/
      data x_data(   108     ) /   0.742142000000E+01/
      data y_data(   108,   1) /   0.803825815549E-01/
      data y_data(   108,   2) /  -0.774022443926E-01/
      data y_data(   108,   3) /   0.349498139530E+01/
      data x_data(   109     ) /   0.749123800000E+01/
      data y_data(   109,   1) /   0.801087480342E-01/
      data y_data(   109,   2) /  -0.774550081138E-01/
      data y_data(   109,   3) /   0.349804454399E+01/
      data x_data(   110     ) /   0.756105700000E+01/
      data y_data(   110,   1) /   0.798372053954E-01/
      data y_data(   110,   2) /  -0.775072825305E-01/
      data y_data(   110,   3) /   0.350111411415E+01/
      data x_data(   111     ) /   0.763087500000E+01/
      data y_data(   111,   1) /   0.795218702913E-01/
      data y_data(   111,   2) /  -0.772153452405E-01/
      data y_data(   111,   3) /   0.350369106250E+01/
      data x_data(   112     ) /   0.770069400000E+01/
      data y_data(   112,   1) /   0.792165286455E-01/
      data y_data(   112,   2) /  -0.769274228362E-01/
      data y_data(   112,   3) /   0.350628064166E+01/
      data x_data(   113     ) /   0.777051300000E+01/
      data y_data(   113,   1) /   0.789204813515E-01/
      data y_data(   113,   2) /  -0.766434123435E-01/
      data y_data(   113,   3) /   0.350888302065E+01/
      data x_data(   114     ) /   0.784033100000E+01/
      data y_data(   114,   1) /   0.786343518956E-01/
      data y_data(   114,   2) /  -0.763627674057E-01/
      data y_data(   114,   3) /   0.351149816917E+01/
      data x_data(   115     ) /   0.791015000000E+01/
      data y_data(   115,   1) /   0.783581049929E-01/
      data y_data(   115,   2) /  -0.760857460863E-01/
      data y_data(   115,   3) /   0.351412603506E+01/
      data x_data(   116     ) /   0.797996800000E+01/
      data y_data(   116,   1) /   0.780914740182E-01/
      data y_data(   116,   2) /  -0.758123087026E-01/
      data y_data(   116,   3) /   0.351676639183E+01/
      data x_data(   117     ) /   0.804978700000E+01/
      data y_data(   117,   1) /   0.778349282430E-01/
      data y_data(   117,   2) /  -0.755425906558E-01/
      data y_data(   117,   3) /   0.351942006258E+01/
      data x_data(   118     ) /   0.811960600000E+01/
      data y_data(   118,   1) /   0.767060005013E-01/
      data y_data(   118,   2) /  -0.748629259800E-01/
      data y_data(   118,   3) /   0.352308365065E+01/
      data x_data(   119     ) /   0.818942400000E+01/
      data y_data(   119,   1) /   0.749675275072E-01/
      data y_data(   119,   2) /  -0.739082030279E-01/
      data y_data(   119,   3) /   0.352744258282E+01/
      data x_data(   120     ) /   0.825924300000E+01/
      data y_data(   120,   1) /   0.732203264871E-01/
      data y_data(   120,   2) /  -0.729677829387E-01/
      data y_data(   120,   3) /   0.353180375725E+01/
      data x_data(   121     ) /   0.832906100000E+01/
      data y_data(   121,   1) /   0.714653536481E-01/
      data y_data(   121,   2) /  -0.720417640866E-01/
      data y_data(   121,   3) /   0.353616768949E+01/
      data x_data(   122     ) /   0.839888000000E+01/
      data y_data(   122,   1) /   0.697026524728E-01/
      data y_data(   122,   2) /  -0.711303441613E-01/
      data y_data(   122,   3) /   0.354053386385E+01/
      data x_data(   123     ) /   0.846869900000E+01/
      data y_data(   123,   1) /   0.679311675976E-01/
      data y_data(   123,   2) /  -0.702338290365E-01/
      data y_data(   123,   3) /   0.354490201928E+01/
      data x_data(   124     ) /   0.853851700000E+01/
      data y_data(   124,   1) /   0.661514907259E-01/
      data y_data(   124,   2) /  -0.693514014079E-01/
      data y_data(   124,   3) /   0.354927245162E+01/
      data x_data(   125     ) /   0.860833600000E+01/
      data y_data(   125,   1) /   0.643642893195E-01/
      data y_data(   125,   2) /  -0.684841859952E-01/
      data y_data(   125,   3) /   0.355364562588E+01/
      data x_data(   126     ) /   0.867815400000E+01/
      data y_data(   126,   1) /   0.625685211335E-01/
      data y_data(   126,   2) /  -0.676309624667E-01/
      data y_data(   126,   3) /   0.355802105829E+01/
      data x_data(   127     ) /   0.874797300000E+01/
      data y_data(   127,   1) /   0.592726153053E-01/
      data y_data(   127,   2) /  -0.667502472178E-01/
      data y_data(   127,   3) /   0.356207193674E+01/
      data x_data(   128     ) /   0.881779200000E+01/
      data y_data(   128,   1) /   0.559628346940E-01/
      data y_data(   128,   2) /  -0.658830278291E-01/
      data y_data(   128,   3) /   0.356611618364E+01/
      data x_data(   129     ) /   0.888761000000E+01/
      data y_data(   129,   1) /   0.526389539445E-01/
      data y_data(   129,   2) /  -0.650295997880E-01/
      data y_data(   129,   3) /   0.357015332043E+01/
      data x_data(   130     ) /   0.895742900000E+01/
      data y_data(   130,   1) /   0.493001606798E-01/
      data y_data(   130,   2) /  -0.641895890517E-01/
      data y_data(   130,   3) /   0.357418299450E+01/
      data x_data(   131     ) /   0.902724700000E+01/
      data y_data(   131,   1) /   0.459477800854E-01/
      data y_data(   131,   2) /  -0.633636608468E-01/
      data y_data(   131,   3) /   0.357820542710E+01/
      data x_data(   132     ) /   0.909706600000E+01/
      data y_data(   132,   1) /   0.425809866655E-01/
      data y_data(   132,   2) /  -0.625506502743E-01/
      data y_data(   132,   3) /   0.358222110110E+01/
      data x_data(   133     ) /   0.916688500000E+01/
      data y_data(   133,   1) /   0.391997975265E-01/
      data y_data(   133,   2) /  -0.617517266217E-01/
      data y_data(   133,   3) /   0.358622955226E+01/
      data x_data(   134     ) /   0.923670300000E+01/
      data y_data(   134,   1) /   0.346722590378E-01/
      data y_data(   134,   2) /  -0.585645574494E-01/
      data y_data(   134,   3) /   0.359257999372E+01/
      data x_data(   135     ) /   0.930652200000E+01/
      data y_data(   135,   1) /   0.293571220012E-01/
      data y_data(   135,   2) /  -0.537137791933E-01/
      data y_data(   135,   3) /   0.360055604161E+01/
      data x_data(   136     ) /   0.937634000000E+01/
      data y_data(   136,   1) /   0.240428291701E-01/
      data y_data(   136,   2) /  -0.488457433255E-01/
      data y_data(   136,   3) /   0.360854221025E+01/
      data x_data(   137     ) /   0.944615900000E+01/
      data y_data(   137,   1) /   0.187288964179E-01/
      data y_data(   137,   2) /  -0.439612606096E-01/
      data y_data(   137,   3) /   0.361653825826E+01/
      data x_data(   138     ) /   0.951597800000E+01/
      data y_data(   138,   1) /   0.134155793624E-01/
      data y_data(   138,   2) /  -0.390597055816E-01/
      data y_data(   138,   3) /   0.362454426446E+01/
      data x_data(   139     ) /   0.958579600000E+01/
      data y_data(   139,   1) /   0.810328650205E-02/
      data y_data(   139,   2) /  -0.341409657395E-01/
      data y_data(   139,   3) /   0.363256043290E+01/
      data x_data(   140     ) /   0.965561500000E+01/
      data y_data(   140,   1) /   0.279164951518E-02/
      data y_data(   140,   2) /  -0.292054827339E-01/
      data y_data(   140,   3) /   0.364058598111E+01/
      data x_data(   141     ) /   0.972543300000E+01/
      data y_data(   141,   1) /  -0.251943909880E-02/
      data y_data(   141,   2) /  -0.242529473488E-01/
      data y_data(   141,   3) /   0.364862194516E+01/
      data x_data(   142     ) /   0.979525200000E+01/
      data y_data(   142,   1) /  -0.783007606812E-02/
      data y_data(   142,   2) /  -0.192831684140E-01/
      data y_data(   142,   3) /   0.365666769776E+01/
      data x_data(   143     ) /   0.986507100000E+01/
      data y_data(   143,   1) /  -0.132068931236E-01/
      data y_data(   143,   2) /  -0.134086133860E-01/
      data y_data(   143,   3) /   0.366767140822E+01/
      data x_data(   144     ) /   0.993488900000E+01/
      data y_data(   144,   1) /  -0.185824817669E-01/
      data y_data(   144,   2) /  -0.751666976281E-02/
      data y_data(   144,   3) /   0.367868287209E+01/
      data x_data(   145     ) /   0.100047080000E+02/
      data y_data(   145,   1) /  -0.239571187069E-01/
      data y_data(   145,   2) /  -0.160839053839E-02/
      data y_data(   145,   3) /   0.368970292061E+01/
      data x_data(   146     ) /   0.100745260000E+02/
      data y_data(   146,   1) /  -0.293309116345E-01/
      data y_data(   146,   2) /   0.431714436105E-02/
      data y_data(   146,   3) /   0.370073008862E+01/
      data x_data(   147     ) /   0.101443450000E+02/
      data y_data(   147,   1) /  -0.347030485541E-01/
      data y_data(   147,   2) /   0.102591280454E-01/
      data y_data(   147,   3) /   0.371176563726E+01/
      data x_data(   148     ) /   0.102141640000E+02/
      data y_data(   148,   1) /  -0.400736613458E-01/
      data y_data(   148,   2) /   0.162186830734E-01/
      data y_data(   148,   3) /   0.372280884772E+01/
      data x_data(   149     ) /   0.102839820000E+02/
      data y_data(   149,   1) /  -0.454434543026E-01/
      data y_data(   149,   2) /   0.221949219471E-01/
      data y_data(   149,   3) /   0.373385931127E+01/
      data x_data(   150     ) /   0.103538010000E+02/
      data y_data(   150,   1) /  -0.491719386843E-01/
      data y_data(   150,   2) /   0.303523985663E-01/
      data y_data(   150,   3) /   0.374574464682E+01/
      data x_data(   151     ) /   0.104236190000E+02/
      data y_data(   151,   1) /  -0.517666350869E-01/
      data y_data(   151,   2) /   0.400109694420E-01/
      data y_data(   151,   3) /   0.375819913861E+01/
      data x_data(   152     ) /   0.104934380000E+02/
      data y_data(   152,   1) /  -0.543615514760E-01/
      data y_data(   152,   2) /   0.496681241496E-01/
      data y_data(   152,   3) /   0.377064543636E+01/
      data x_data(   153     ) /   0.105632570000E+02/
      data y_data(   153,   1) /  -0.569560514760E-01/
      data y_data(   153,   2) /   0.593247369412E-01/
      data y_data(   153,   3) /   0.378308347900E+01/
      data x_data(   154     ) /   0.106330750000E+02/
      data y_data(   154,   1) /  -0.595507478874E-01/
      data y_data(   154,   2) /   0.689795121101E-01/
      data y_data(   154,   3) /   0.379551317515E+01/
      data x_data(   155     ) /   0.107028940000E+02/
      data y_data(   155,   1) /  -0.621451642676E-01/
      data y_data(   155,   2) /   0.786331667884E-01/
      data y_data(   155,   3) /   0.380793476854E+01/
      data x_data(   156     ) /   0.107727120000E+02/
      data y_data(   156,   1) /  -0.647393606878E-01/
      data y_data(   156,   2) /   0.882852377109E-01/
      data y_data(   156,   3) /   0.382034796475E+01/
      data x_data(   157     ) /   0.108425310000E+02/
      data y_data(   157,   1) /  -0.673338685315E-01/
      data y_data(   157,   2) /   0.979365966356E-01/
      data y_data(   157,   3) /   0.383275355809E+01/
      data x_data(   158     ) /   0.109123500000E+02/
      data y_data(   158,   1) /  -0.699277770593E-01/
      data y_data(   158,   2) /   0.107586505163E+00/
      data y_data(   158,   3) /   0.384515030499E+01/
      data x_data(   159     ) /   0.109821680000E+02/
      data y_data(   159,   1) /  -0.734182692214E-01/
      data y_data(   159,   2) /   0.120534780379E+00/
      data y_data(   159,   3) /   0.385877000129E+01/
      data x_data(   160     ) /   0.110519870000E+02/
      data y_data(   160,   1) /  -0.769081855870E-01/
      data y_data(   160,   2) /   0.133482935011E+00/
      data y_data(   160,   3) /   0.387238979879E+01/
      data x_data(   161     ) /   0.111218050000E+02/
      data y_data(   161,   1) /  -0.803973820218E-01/
      data y_data(   161,   2) /   0.146431210247E+00/
      data y_data(   161,   3) /   0.388601008663E+01/
      data x_data(   162     ) /   0.111916240000E+02/
      data y_data(   162,   1) /  -0.838870941148E-01/
      data y_data(   162,   2) /   0.159379864858E+00/
      data y_data(   162,   3) /   0.389963058834E+01/
      data x_data(   163     ) /   0.112614430000E+02/
      data y_data(   163,   1) /  -0.873770941148E-01/
      data y_data(   163,   2) /   0.172328477649E+00/
      data y_data(   163,   3) /   0.391325192671E+01/
      data x_data(   164     ) /   0.113312610000E+02/
      data y_data(   164,   1) /  -0.908664948223E-01/
      data y_data(   164,   2) /   0.185277048648E+00/
      data y_data(   164,   3) /   0.392687362316E+01/
      data x_data(   165     ) /   0.114010800000E+02/
      data y_data(   165,   1) /  -0.943557069064E-01/
      data y_data(   165,   2) /   0.198226703233E+00/
      data y_data(   165,   3) /   0.394049592052E+01/
      data x_data(   166     ) /   0.114708980000E+02/
      data y_data(   166,   1) /  -0.981063314976E-01/
      data y_data(   166,   2) /   0.212130105259E+00/
      data y_data(   166,   3) /   0.395575854905E+01/
      data x_data(   167     ) /   0.115407170000E+02/
      data y_data(   167,   1) /  -0.102035567482E+00/
      data y_data(   167,   2) /   0.226695043684E+00/
      data y_data(   167,   3) /   0.397215879861E+01/
      data x_data(   168     ) /   0.116105360000E+02/
      data y_data(   168,   1) /  -0.105962497329E+00/
      data y_data(   168,   2) /   0.241263726629E+00/
      data y_data(   168,   3) /   0.398856618582E+01/
      data x_data(   169     ) /   0.116803540000E+02/
      data y_data(   169,   1) /  -0.109886508300E+00/
      data y_data(   169,   2) /   0.255835562591E+00/
      data y_data(   169,   3) /   0.400498130211E+01/
      data x_data(   170     ) /   0.117501730000E+02/
      data y_data(   170,   1) /  -0.113807948495E+00/
      data y_data(   170,   2) /   0.270411001046E+00/
      data y_data(   170,   3) /   0.402140405171E+01/
      data x_data(   171     ) /   0.118199910000E+02/
      data y_data(   171,   1) /  -0.117726663769E+00/
      data y_data(   171,   2) /   0.284989836990E+00/
      data y_data(   171,   3) /   0.403783437225E+01/
      data x_data(   172     ) /   0.118898100000E+02/
      data y_data(   172,   1) /  -0.121642899662E+00/
      data y_data(   172,   2) /   0.299571775462E+00/
      data y_data(   172,   3) /   0.405427162186E+01/
      data x_data(   173     ) /   0.119596290000E+02/
      data y_data(   173,   1) /  -0.125556125245E+00/
      data y_data(   173,   2) /   0.314156662671E+00/
      data y_data(   173,   3) /   0.407071730480E+01/
      data x_data(   174     ) /   0.120294470000E+02/
      data y_data(   174,   1) /  -0.129467340571E+00/
      data y_data(   174,   2) /   0.328745294322E+00/
      data y_data(   174,   3) /   0.408716962531E+01/
      data x_data(   175     ) /   0.120992660000E+02/
      data y_data(   175,   1) /  -0.134701076412E+00/
      data y_data(   175,   2) /   0.346794937087E+00/
      data y_data(   175,   3) /   0.410857587496E+01/
      data x_data(   176     ) /   0.121690840000E+02/
      data y_data(   176,   1) /  -0.139927996040E+00/
      data y_data(   176,   2) /   0.364839068722E+00/
      data y_data(   176,   3) /   0.412997419544E+01/
      data x_data(   177     ) /   0.122389030000E+02/
      data y_data(   177,   1) /  -0.145148231842E+00/
      data y_data(   177,   2) /   0.382878507240E+00/
      data y_data(   177,   3) /   0.415136444511E+01/
      data x_data(   178     ) /   0.123087220000E+02/
      data y_data(   178,   1) /  -0.150361753162E+00/
      data y_data(   178,   2) /   0.400912894449E+00/
      data y_data(   178,   3) /   0.417274762805E+01/
      data x_data(   179     ) /   0.123785400000E+02/
      data y_data(   179,   1) /  -0.155568672842E+00/
      data y_data(   179,   2) /   0.418942230320E+00/
      data y_data(   179,   3) /   0.419412244851E+01/
      data x_data(   180     ) /   0.124483590000E+02/
      data y_data(   180,   1) /  -0.160768908592E+00/
      data y_data(   180,   2) /   0.436966464601E+00/
      data y_data(   180,   3) /   0.421548999394E+01/
      data x_data(   181     ) /   0.125181770000E+02/
      data y_data(   181,   1) /  -0.165962328311E+00/
      data y_data(   181,   2) /   0.454986004719E+00/
      data y_data(   181,   3) /   0.423684951864E+01/
      data x_data(   182     ) /   0.125879960000E+02/
      data y_data(   182,   1) /  -0.170125612792E+00/
      data y_data(   182,   2) /   0.475633769146E+00/
      data y_data(   182,   3) /   0.425850942539E+01/
      data x_data(   183     ) /   0.126578150000E+02/
      data y_data(   183,   1) /  -0.173580570153E+00/
      data y_data(   183,   2) /   0.498091811785E+00/
      data y_data(   183,   3) /   0.428037617849E+01/
      data x_data(   184     ) /   0.127276330000E+02/
      data y_data(   184,   1) /  -0.177037618931E+00/
      data y_data(   184,   2) /   0.520537777063E+00/
      data y_data(   184,   3) /   0.430223915742E+01/
      data x_data(   185     ) /   0.127974520000E+02/
      data y_data(   185,   1) /  -0.180496076347E+00/
      data y_data(   185,   2) /   0.542972601326E+00/
      data y_data(   185,   3) /   0.432409848042E+01/
      data x_data(   186     ) /   0.128672700000E+02/
      data y_data(   186,   1) /  -0.183957125061E+00/
      data y_data(   186,   2) /   0.565395362399E+00/
      data y_data(   186,   3) /   0.434595366355E+01/
      data x_data(   187     ) /   0.129370890000E+02/
      data y_data(   187,   1) /  -0.187419582542E+00/
      data y_data(   187,   2) /   0.587807186604E+00/
      data y_data(   187,   3) /   0.436780448662E+01/
      data x_data(   188     ) /   0.130069080000E+02/
      data y_data(   188,   1) /  -0.190883335639E+00/
      data y_data(   188,   2) /   0.610206729243E+00/
      data y_data(   188,   3) /   0.438965153545E+01/
      data x_data(   189     ) /   0.130767260000E+02/
      data y_data(   189,   1) /  -0.194349588523E+00/
      data y_data(   189,   2) /   0.632594194670E+00/
      data y_data(   189,   3) /   0.441149442275E+01/
      data x_data(   190     ) /   0.131465450000E+02/
      data y_data(   190,   1) /  -0.197817341834E+00/
      data y_data(   190,   2) /   0.654970814520E+00/
      data y_data(   190,   3) /   0.443333354164E+01/
      data x_data(   191     ) /   0.132163630000E+02/
      data y_data(   191,   1) /  -0.204008594653E+00/
      data y_data(   191,   2) /   0.681054280007E+00/
      data y_data(   191,   3) /   0.445890872461E+01/
      data x_data(   192     ) /   0.132861820000E+02/
      data y_data(   192,   1) /  -0.210204848028E+00/
      data y_data(   192,   2) /   0.707122604062E+00/
      data y_data(   192,   3) /   0.448448704784E+01/
      data x_data(   193     ) /   0.133560010000E+02/
      data y_data(   193,   1) /  -0.216404601126E+00/
      data y_data(   193,   2) /   0.733175146701E+00/
      data y_data(   193,   3) /   0.451006959667E+01/
      data x_data(   194     ) /   0.134258190000E+02/
      data y_data(   194,   1) /  -0.222609353849E+00/
      data y_data(   194,   2) /   0.759211612278E+00/
      data y_data(   194,   3) /   0.453565627954E+01/
      data x_data(   195     ) /   0.134956380000E+02/
      data y_data(   195,   1) /  -0.228818107320E+00/
      data y_data(   195,   2) /   0.785233231978E+00/
      data y_data(   195,   3) /   0.456124660287E+01/
      data x_data(   196     ) /   0.135654560000E+02/
      data y_data(   196,   1) /  -0.235030859979E+00/
      data y_data(   196,   2) /   0.811239697614E+00/
      data y_data(   196,   3) /   0.458684078567E+01/
      data x_data(   197     ) /   0.136352750000E+02/
      data y_data(   197,   1) /  -0.241247817779E+00/
      data y_data(   197,   2) /   0.837230317256E+00/
      data y_data(   197,   3) /   0.461243860906E+01/
      data x_data(   198     ) /   0.137050940000E+02/
      data y_data(   198,   1) /  -0.249153288066E+00/
      data y_data(   198,   2) /   0.865598456559E+00/
      data y_data(   198,   3) /   0.464054406413E+01/
      data x_data(   199     ) /   0.137749120000E+02/
      data y_data(   199,   1) /  -0.258217060507E+00/
      data y_data(   199,   2) /   0.895606468740E+00/
      data y_data(   199,   3) /   0.467037039274E+01/
      data x_data(   200     ) /   0.138447310000E+02/
      data y_data(   200,   1) /  -0.267269162885E+00/
      data y_data(   200,   2) /   0.925602977879E+00/
      data y_data(   200,   3) /   0.470018150291E+01/
      data x_data(   201     ) /   0.139145490000E+02/
      data y_data(   201,   1) /  -0.276309435446E+00/
      data y_data(   201,   2) /   0.955587785807E+00/
      data y_data(   201,   3) /   0.472997662742E+01/
      data x_data(   202     ) /   0.139843680000E+02/
      data y_data(   202,   1) /  -0.285338446232E+00/
      data y_data(   202,   2) /   0.985560999198E+00/
      data y_data(   202,   3) /   0.475975644168E+01/
      data x_data(   203     ) /   0.140541870000E+02/
      data y_data(   203,   1) /  -0.294355827246E+00/
      data y_data(   203,   2) /   0.101552211199E+01/
      data y_data(   203,   3) /   0.478952016107E+01/
      data x_data(   204     ) /   0.141240050000E+02/
      data y_data(   204,   1) /  -0.303361304255E+00/
      data y_data(   204,   2) /   0.104547191994E+01/
      data y_data(   204,   3) /   0.481926828583E+01/
      data x_data(   205     ) /   0.141938240000E+02/
      data y_data(   205,   1) /  -0.312355906329E+00/
      data y_data(   205,   2) /   0.107540992905E+01/
      data y_data(   205,   3) /   0.484900059985E+01/
      data x_data(   206     ) /   0.142636420000E+02/
      data y_data(   206,   1) /  -0.321338179194E+00/
      data y_data(   206,   2) /   0.110533614554E+01/
      data y_data(   206,   3) /   0.487871702050E+01/
      data x_data(   207     ) /   0.143334610000E+02/
      data y_data(   207,   1) /  -0.329498985412E+00/
      data y_data(   207,   2) /   0.114198045036E+01/
      data y_data(   207,   3) /   0.491358733436E+01/
      data x_data(   208     ) /   0.144032800000E+02/
      data y_data(   208,   1) /  -0.337648274954E+00/
      data y_data(   208,   2) /   0.117863156316E+01/
      data y_data(   208,   3) /   0.494843855375E+01/
      data x_data(   209     ) /   0.144730980000E+02/
      data y_data(   209,   1) /  -0.345786048003E+00/
      data y_data(   209,   2) /   0.121529057541E+01/
      data y_data(   209,   3) /   0.498326988318E+01/
      data x_data(   210     ) /   0.145429170000E+02/
      data y_data(   210,   1) /  -0.353912649773E+00/
      data y_data(   210,   2) /   0.125195658448E+01/
      data y_data(   210,   3) /   0.501808199253E+01/
      data x_data(   211     ) /   0.146127350000E+02/
      data y_data(   211,   1) /  -0.362027922943E+00/
      data y_data(   211,   2) /   0.128863039248E+01/
      data y_data(   211,   3) /   0.505287561786E+01/
      data x_data(   212     ) /   0.146825540000E+02/
      data y_data(   212,   1) /  -0.370132024592E+00/
      data y_data(   212,   2) /   0.132531160579E+01/
      data y_data(   212,   3) /   0.508764972704E+01/
      data x_data(   213     ) /   0.147523730000E+02/
      data y_data(   213,   1) /  -0.378224018398E+00/
      data y_data(   213,   2) /   0.136200021859E+01/
      data y_data(   213,   3) /   0.512240515070E+01/
      data x_data(   214     ) /   0.148221910000E+02/
      data y_data(   214,   1) /  -0.386557643631E+00/
      data y_data(   214,   2) /   0.140324804337E+01/
      data y_data(   214,   3) /   0.515740693614E+01/
      data x_data(   215     ) /   0.148920100000E+02/
      data y_data(   215,   1) /  -0.395064506889E+00/
      data y_data(   215,   2) /   0.144764406992E+01/
      data y_data(   215,   3) /   0.519257286477E+01/
      data x_data(   216     ) /   0.149618280000E+02/
      data y_data(   216,   1) /  -0.403576536960E+00/
      data y_data(   216,   2) /   0.149203860124E+01/
      data y_data(   216,   3) /   0.522771819215E+01/
      data x_data(   217     ) /   0.150316470000E+02/
      data y_data(   217,   1) /  -0.412093900292E+00/
      data y_data(   217,   2) /   0.153643371916E+01/
      data y_data(   217,   3) /   0.526284362060E+01/
      data x_data(   218     ) /   0.151014660000E+02/
      data y_data(   218,   1) /  -0.420616744862E+00/
      data y_data(   218,   2) /   0.158082839591E+01/
      data y_data(   218,   3) /   0.529794854426E+01/
      data x_data(   219     ) /   0.151712840000E+02/
      data y_data(   219,   1) /  -0.429145070555E+00/
      data y_data(   219,   2) /   0.162522272312E+01/
      data y_data(   219,   3) /   0.533303348470E+01/
      data x_data(   220     ) /   0.152411030000E+02/
      data y_data(   220,   1) /  -0.437678934001E+00/
      data y_data(   220,   2) /   0.166961724941E+01/
      data y_data(   220,   3) /   0.536809750435E+01/
      data x_data(   221     ) /   0.153109210000E+02/
      data y_data(   221,   1) /  -0.446218259618E+00/
      data y_data(   221,   2) /   0.171401107672E+01/
      data y_data(   221,   3) /   0.540314203644E+01/
      data x_data(   222     ) /   0.153807400000E+02/
      data y_data(   222,   1) /  -0.454762827404E+00/
      data y_data(   222,   2) /   0.175840489865E+01/
      data y_data(   222,   3) /   0.543816596445E+01/
      data x_data(   223     ) /   0.154505590000E+02/
      data y_data(   223,   1) /  -0.461116467709E+00/
      data y_data(   223,   2) /   0.180859707539E+01/
      data y_data(   223,   3) /   0.547769809237E+01/
      data x_data(   224     ) /   0.155203770000E+02/
      data y_data(   224,   1) /  -0.467492497479E+00/
      data y_data(   224,   2) /   0.185878210713E+01/
      data y_data(   224,   3) /   0.551719512472E+01/
      data x_data(   225     ) /   0.155901960000E+02/
      data y_data(   225,   1) /  -0.473891361112E+00/
      data y_data(   225,   2) /   0.190896072463E+01/
      data y_data(   225,   3) /   0.555665634820E+01/
      data x_data(   226     ) /   0.156600140000E+02/
      data y_data(   226,   1) /  -0.480312686542E+00/
      data y_data(   226,   2) /   0.195913246073E+01/
      data y_data(   226,   3) /   0.559608238073E+01/
      data x_data(   227     ) /   0.157298330000E+02/
      data y_data(   227,   1) /  -0.486756254515E+00/
      data y_data(   227,   2) /   0.200929837387E+01/
      data y_data(   227,   3) /   0.563547330830E+01/
      data x_data(   228     ) /   0.157996520000E+02/
      data y_data(   228,   1) /  -0.493222894821E+00/
      data y_data(   228,   2) /   0.205945675488E+01/
      data y_data(   228,   3) /   0.567482823195E+01/
      data x_data(   229     ) /   0.158694700000E+02/
      data y_data(   229,   1) /  -0.499712424403E+00/
      data y_data(   229,   2) /   0.210960878687E+01/
      data y_data(   229,   3) /   0.571414796901E+01/
      data x_data(   230     ) /   0.159392890000E+02/
      data y_data(   230,   1) /  -0.506003169080E+00/
      data y_data(   230,   2) /   0.216378794903E+01/
      data y_data(   230,   3) /   0.575481032235E+01/
      data x_data(   231     ) /   0.160091070000E+02/
      data y_data(   231,   1) /  -0.512169136770E+00/
      data y_data(   231,   2) /   0.222074978575E+01/
      data y_data(   231,   3) /   0.579638765876E+01/
      data x_data(   232     ) /   0.160789260000E+02/
      data y_data(   232,   1) /  -0.518365230303E+00/
      data y_data(   232,   2) /   0.227771199166E+01/
      data y_data(   232,   3) /   0.583792741656E+01/
      data x_data(   233     ) /   0.161487450000E+02/
      data y_data(   233,   1) /  -0.524591510914E+00/
      data y_data(   233,   2) /   0.233467410446E+01/
      data y_data(   233,   3) /   0.587942927006E+01/
      data x_data(   234     ) /   0.162185630000E+02/
      data y_data(   234,   1) /  -0.530848274091E+00/
      data y_data(   234,   2) /   0.239163644122E+01/
      data y_data(   234,   3) /   0.592089260677E+01/
      data x_data(   235     ) /   0.162883820000E+02/
      data y_data(   235,   1) /  -0.537135072137E+00/
      data y_data(   235,   2) /   0.244859914709E+01/
      data y_data(   235,   3) /   0.596231936427E+01/
      data x_data(   236     ) /   0.163582000000E+02/
      data y_data(   236,   1) /  -0.543452335150E+00/
      data y_data(   236,   2) /   0.250556077962E+01/
      data y_data(   236,   3) /   0.600370740545E+01/
      data x_data(   237     ) /   0.164280190000E+02/
      data y_data(   237,   1) /  -0.549799633359E+00/
      data y_data(   237,   2) /   0.256252378121E+01/
      data y_data(   237,   3) /   0.604505795848E+01/
      data x_data(   238     ) /   0.164978380000E+02/
      data y_data(   238,   1) /  -0.556177709707E+00/
      data y_data(   238,   2) /   0.261948580253E+01/
      data y_data(   238,   3) /   0.608637081198E+01/
      data x_data(   239     ) /   0.165676560000E+02/
      data y_data(   239,   1) /  -0.562124176738E+00/
      data y_data(   239,   2) /   0.268420143509E+01/
      data y_data(   239,   3) /   0.613212514920E+01/
      data x_data(   240     ) /   0.166374750000E+02/
      data y_data(   240,   1) /  -0.568100770929E+00/
      data y_data(   240,   2) /   0.274891393664E+01/
      data y_data(   240,   3) /   0.617786340619E+01/
      data x_data(   241     ) /   0.167072930000E+02/
      data y_data(   241,   1) /  -0.574108033530E+00/
      data y_data(   241,   2) /   0.281362177349E+01/
      data y_data(   241,   3) /   0.622358544787E+01/
      data x_data(   242     ) /   0.167771120000E+02/
      data y_data(   242,   1) /  -0.580145332152E+00/
      data y_data(   242,   2) /   0.287832577501E+01/
      data y_data(   242,   3) /   0.626929120466E+01/
      data x_data(   243     ) /   0.168469310000E+02/
      data y_data(   243,   1) /  -0.586213112763E+00/
      data y_data(   243,   2) /   0.294302659207E+01/
      data y_data(   243,   3) /   0.631498085389E+01/
      data x_data(   244     ) /   0.169167490000E+02/
      data y_data(   244,   1) /  -0.592311375118E+00/
      data y_data(   244,   2) /   0.300772242896E+01/
      data y_data(   244,   3) /   0.636065419162E+01/
      data x_data(   245     ) /   0.169865680000E+02/
      data y_data(   245,   1) /  -0.598439173986E+00/
      data y_data(   245,   2) /   0.307241543044E+01/
      data y_data(   245,   3) /   0.640631115237E+01/
      data x_data(   246     ) /   0.170563860000E+02/
      data y_data(   246,   1) /  -0.603337521313E+00/
      data y_data(   246,   2) /   0.314082261225E+01/
      data y_data(   246,   3) /   0.645273488752E+01/
      data x_data(   247     ) /   0.171262050000E+02/
      data y_data(   247,   1) /  -0.607387618736E+00/
      data y_data(   247,   2) /   0.321179879080E+01/
      data y_data(   247,   3) /   0.649968563023E+01/
      data x_data(   248     ) /   0.171960240000E+02/
      data y_data(   248,   1) /  -0.611455005944E+00/
      data y_data(   248,   2) /   0.328277854390E+01/
      data y_data(   248,   3) /   0.654662166667E+01/
      data x_data(   249     ) /   0.172658420000E+02/
      data y_data(   249,   1) /  -0.615540387178E+00/
      data y_data(   249,   2) /   0.335376177998E+01/
      data y_data(   249,   3) /   0.659354397580E+01/
      data x_data(   250     ) /   0.173356610000E+02/
      data y_data(   250,   1) /  -0.619643484625E+00/
      data y_data(   250,   2) /   0.342474845862E+01/
      data y_data(   250,   3) /   0.664045212677E+01/
      data x_data(   251     ) /   0.174054790000E+02/
      data y_data(   251,   1) /  -0.623763865844E+00/
      data y_data(   251,   2) /   0.349573849037E+01/
      data y_data(   251,   3) /   0.668734564034E+01/
      data x_data(   252     ) /   0.174752980000E+02/
      data y_data(   252,   1) /  -0.627901759041E+00/
      data y_data(   252,   2) /   0.356673246482E+01/
      data y_data(   252,   3) /   0.673422529113E+01/
      data x_data(   253     ) /   0.175451170000E+02/
      data y_data(   253,   1) /  -0.632057350513E+00/
      data y_data(   253,   2) /   0.363772992218E+01/
      data y_data(   253,   3) /   0.678109071478E+01/
      data x_data(   254     ) /   0.176149350000E+02/
      data y_data(   254,   1) /  -0.636230435976E+00/
      data y_data(   254,   2) /   0.370873065810E+01/
      data y_data(   254,   3) /   0.682794163716E+01/
      data x_data(   255     ) /   0.176847540000E+02/
      data y_data(   255,   1) /  -0.635060829194E+00/
      data y_data(   255,   2) /   0.378166083690E+01/
      data y_data(   255,   3) /   0.687565387914E+01/
      data x_data(   256     ) /   0.177545720000E+02/
      data y_data(   256,   1) /  -0.633902210376E+00/
      data y_data(   256,   2) /   0.385459936850E+01/
      data y_data(   256,   3) /   0.692335759743E+01/
      data x_data(   257     ) /   0.178243910000E+02/
      data y_data(   257,   1) /  -0.632754807875E+00/
      data y_data(   257,   2) /   0.392754684309E+01/
      data y_data(   257,   3) /   0.697105254351E+01/
      data x_data(   258     ) /   0.178942100000E+02/
      data y_data(   258,   1) /  -0.631617695083E+00/
      data y_data(   258,   2) /   0.400050280046E+01/
      data y_data(   258,   3) /   0.701874017142E+01/
      data x_data(   259     ) /   0.179640280000E+02/
      data y_data(   259,   1) /  -0.630491780508E+00/
      data y_data(   259,   2) /   0.407346653623E+01/
      data y_data(   259,   3) /   0.706641938998E+01/
      data x_data(   260     ) /   0.180338470000E+02/
      data y_data(   260,   1) /  -0.629376673764E+00/
      data y_data(   260,   2) /   0.414643851091E+01/
      data y_data(   260,   3) /   0.711409033578E+01/
      data x_data(   261     ) /   0.181036650000E+02/
      data y_data(   261,   1) /  -0.628272054907E+00/
      data y_data(   261,   2) /   0.421941924663E+01/
      data y_data(   261,   3) /   0.716175275879E+01/
      data x_data(   262     ) /   0.181734840000E+02/
      data y_data(   262,   1) /  -0.627642366677E+00/
      data y_data(   262,   2) /   0.429150238164E+01/
      data y_data(   262,   3) /   0.721172113526E+01/
      data x_data(   263     ) /   0.182433030000E+02/
      data y_data(   263,   1) /  -0.627353513177E+00/
      data y_data(   263,   2) /   0.436297247931E+01/
      data y_data(   263,   3) /   0.726330824532E+01/
      data x_data(   264     ) /   0.183131210000E+02/
      data y_data(   264,   1) /  -0.627092148808E+00/
      data y_data(   264,   2) /   0.443445756838E+01/
      data y_data(   264,   3) /   0.731493810593E+01/
      data x_data(   265     ) /   0.183829400000E+02/
      data y_data(   265,   1) /  -0.626858306177E+00/
      data y_data(   265,   2) /   0.450595708317E+01/
      data y_data(   265,   3) /   0.736661073985E+01/
      data x_data(   266     ) /   0.184527580000E+02/
      data y_data(   266,   1) /  -0.626652237331E+00/
      data y_data(   266,   2) /   0.457747176358E+01/
      data y_data(   266,   3) /   0.741832530431E+01/
      data x_data(   267     ) /   0.185225770000E+02/
      data y_data(   267,   1) /  -0.626473894914E+00/
      data y_data(   267,   2) /   0.464900177851E+01/
      data y_data(   267,   3) /   0.747008214291E+01/
      data x_data(   268     ) /   0.185923960000E+02/
      data y_data(   268,   1) /  -0.626323337150E+00/
      data y_data(   268,   2) /   0.472054637617E+01/
      data y_data(   268,   3) /   0.752188134443E+01/
      data x_data(   269     ) /   0.186622140000E+02/
      data y_data(   269,   1) /  -0.626200176516E+00/
      data y_data(   269,   2) /   0.479210596490E+01/
      data y_data(   269,   3) /   0.757372299975E+01/
      data x_data(   270     ) /   0.187320330000E+02/
      data y_data(   270,   1) /  -0.626104630151E+00/
      data y_data(   270,   2) /   0.486368077577E+01/
      data y_data(   270,   3) /   0.762560754323E+01/
      data x_data(   271     ) /   0.188018510000E+02/
      data y_data(   271,   1) /  -0.624296060772E+00/
      data y_data(   271,   2) /   0.493385266009E+01/
      data y_data(   271,   3) /   0.767424290240E+01/
      data x_data(   272     ) /   0.188716700000E+02/
      data y_data(   272,   1) /  -0.622517423151E+00/
      data y_data(   272,   2) /   0.500404487963E+01/
      data y_data(   272,   3) /   0.772292424202E+01/
      data x_data(   273     ) /   0.189414890000E+02/
      data y_data(   273,   1) /  -0.620768865388E+00/
      data y_data(   273,   2) /   0.507425827303E+01/
      data y_data(   273,   3) /   0.777165044355E+01/
      data x_data(   274     ) /   0.190113070000E+02/
      data y_data(   274,   1) /  -0.619049999957E+00/
      data y_data(   274,   2) /   0.514449236142E+01/
      data y_data(   274,   3) /   0.782042180210E+01/
      data x_data(   275     ) /   0.190811260000E+02/
      data y_data(   275,   1) /  -0.617360658388E+00/
      data y_data(   275,   2) /   0.521474817263E+01/
      data y_data(   275,   3) /   0.786923814234E+01/
      data x_data(   276     ) /   0.191509440000E+02/
      data y_data(   276,   1) /  -0.615701588480E+00/
      data y_data(   276,   2) /   0.528502426088E+01/
      data y_data(   276,   3) /   0.791810020475E+01/
      data x_data(   277     ) /   0.192207630000E+02/
      data y_data(   277,   1) /  -0.614072747125E+00/
      data y_data(   277,   2) /   0.535532157223E+01/
      data y_data(   277,   3) /   0.796700813687E+01/
      data x_data(   278     ) /   0.192905820000E+02/
      data y_data(   278,   1) /  -0.611632911579E+00/
      data y_data(   278,   2) /   0.542181284453E+01/
      data y_data(   278,   3) /   0.801183975560E+01/
      data x_data(   279     ) /   0.193604000000E+02/
      data y_data(   279,   1) /  -0.608631611805E+00/
      data y_data(   279,   2) /   0.548568217470E+01/
      data y_data(   279,   3) /   0.805384956536E+01/
      data x_data(   280     ) /   0.194302190000E+02/
      data y_data(   280,   1) /  -0.605641524370E+00/
      data y_data(   280,   2) /   0.554957106119E+01/
      data y_data(   280,   3) /   0.809586748118E+01/
      data x_data(   281     ) /   0.195000370000E+02/
      data y_data(   281,   1) /  -0.602661928872E+00/
      data y_data(   281,   2) /   0.561347939122E+01/
      data y_data(   281,   3) /   0.813789349523E+01/
      data x_data(   282     ) /   0.195698560000E+02/
      data y_data(   282,   1) /  -0.599693341426E+00/
      data y_data(   282,   2) /   0.567740857358E+01/
      data y_data(   282,   3) /   0.817992841103E+01/
      data x_data(   283     ) /   0.196396750000E+02/
      data y_data(   283,   1) /  -0.596736045690E+00/
      data y_data(   283,   2) /   0.574135728403E+01/
      data y_data(   283,   3) /   0.822197181955E+01/
      data x_data(   284     ) /   0.197094930000E+02/
      data y_data(   284,   1) /  -0.593789450206E+00/
      data y_data(   284,   2) /   0.580532640961E+01/
      data y_data(   284,   3) /   0.826402274217E+01/
      data x_data(   285     ) /   0.197793120000E+02/
      data y_data(   285,   1) /  -0.590853362745E+00/
      data y_data(   285,   2) /   0.586931529642E+01/
      data y_data(   285,   3) /   0.830608324940E+01/
      data x_data(   286     ) /   0.198491310000E+02/
      data y_data(   286,   1) /  -0.587928777063E+00/
      data y_data(   286,   2) /   0.593332426238E+01/
      data y_data(   286,   3) /   0.834815170934E+01/
      data x_data(   287     ) /   0.199189490000E+02/
      data y_data(   287,   1) /  -0.585077475537E+00/
      data y_data(   287,   2) /   0.599145380881E+01/
      data y_data(   287,   3) /   0.837873767925E+01/
      data x_data(   288     ) /   0.199887680000E+02/
      data y_data(   288,   1) /  -0.582225884065E+00/
      data y_data(   288,   2) /   0.604960701927E+01/
      data y_data(   288,   3) /   0.840933629204E+01/
      data x_data(   289     ) /   0.200585860000E+02/
      data y_data(   289,   1) /  -0.579374288608E+00/
      data y_data(   289,   2) /   0.610778334880E+01/
      data y_data(   289,   3) /   0.843994701043E+01/
      data x_data(   290     ) /   0.201284050000E+02/
      data y_data(   290,   1) /  -0.576522201120E+00/
      data y_data(   290,   2) /   0.616598273592E+01/
      data y_data(   290,   3) /   0.847056972189E+01/
      data x_data(   291     ) /   0.201982240000E+02/
      data y_data(   291,   1) /  -0.573670411140E+00/
      data y_data(   291,   2) /   0.622420579382E+01/
      data y_data(   291,   3) /   0.850120447750E+01/
      data x_data(   292     ) /   0.202680420000E+02/
      data y_data(   292,   1) /  -0.570818018176E+00/
      data y_data(   292,   2) /   0.628245145258E+01/
      data y_data(   292,   3) /   0.853185135600E+01/
      data x_data(   293     ) /   0.203378610000E+02/
      data y_data(   293,   1) /  -0.567965518176E+00/
      data y_data(   293,   2) /   0.634072025451E+01/
      data y_data(   293,   3) /   0.856250976453E+01/
      data x_data(   294     ) /   0.204076790000E+02/
      data y_data(   294,   1) /  -0.565207170164E+00/
      data y_data(   294,   2) /   0.639181641649E+01/
      data y_data(   294,   3) /   0.859124097323E+01/
      data x_data(   295     ) /   0.204774980000E+02/
      data y_data(   295,   1) /  -0.562516040942E+00/
      data y_data(   295,   2) /   0.643796236685E+01/
      data y_data(   295,   3) /   0.861867276037E+01/
      data x_data(   296     ) /   0.205473170000E+02/
      data y_data(   296,   1) /  -0.559829413976E+00/
      data y_data(   296,   2) /   0.648412766043E+01/
      data y_data(   296,   3) /   0.864616378812E+01/
      data x_data(   297     ) /   0.206171350000E+02/
      data y_data(   297,   1) /  -0.557147772719E+00/
      data y_data(   297,   2) /   0.653031135172E+01/
      data y_data(   297,   3) /   0.867371467582E+01/
      data x_data(   298     ) /   0.206869540000E+02/
      data y_data(   298,   1) /  -0.554471138608E+00/
      data y_data(   298,   2) /   0.657651528777E+01/
      data y_data(   298,   3) /   0.870132538354E+01/
      data x_data(   299     ) /   0.207567720000E+02/
      data y_data(   299,   1) /  -0.551798499492E+00/
      data y_data(   299,   2) /   0.662273773061E+01/
      data y_data(   299,   3) /   0.872899680623E+01/
      data x_data(   300     ) /   0.208265910000E+02/
      data y_data(   300,   1) /  -0.549131370386E+00/
      data y_data(   300,   2) /   0.666897927264E+01/
      data y_data(   300,   3) /   0.875672759472E+01/
      data x_data(   301     ) /   0.208964100000E+02/
      data y_data(   301,   1) /  -0.546467947850E+00/
      data y_data(   301,   2) /   0.671524047504E+01/
      data y_data(   301,   3) /   0.878451862442E+01/
      data x_data(   302     ) /   0.209662280000E+02/
      data y_data(   302,   1) /  -0.543809602164E+00/
      data y_data(   302,   2) /   0.676152025752E+01/
      data y_data(   302,   3) /   0.881236930591E+01/
      data x_data(   303     ) /   0.210360470000E+02/
      data y_data(   303,   1) /  -0.539867468053E+00/
      data y_data(   303,   2) /   0.679504210209E+01/
      data y_data(   303,   3) /   0.882942671789E+01/
      data x_data(   304     ) /   0.211058650000E+02/
      data y_data(   304,   1) /  -0.535940328819E+00/
      data y_data(   304,   2) /   0.682856734047E+01/
      data y_data(   304,   3) /   0.884654413923E+01/
      data x_data(   305     ) /   0.211756840000E+02/
      data y_data(   305,   1) /  -0.532027199831E+00/
      data y_data(   305,   2) /   0.686209608696E+01/
      data y_data(   305,   3) /   0.886372142907E+01/
      data x_data(   306     ) /   0.212455030000E+02/
      data y_data(   306,   1) /  -0.528128777464E+00/
      data y_data(   306,   2) /   0.689562838112E+01/
      data y_data(   306,   3) /   0.888095905221E+01/
      data x_data(   307     ) /   0.213153210000E+02/
      data y_data(   307,   1) /  -0.524244431609E+00/
      data y_data(   307,   2) /   0.692916436757E+01/
      data y_data(   307,   3) /   0.889825604878E+01/
      data x_data(   308     ) /   0.213851400000E+02/
      data y_data(   308,   1) /  -0.520375297498E+00/
      data y_data(   308,   2) /   0.696270421214E+01/
      data y_data(   308,   3) /   0.891561234798E+01/
      data x_data(   309     ) /   0.214549580000E+02/
      data y_data(   309,   1) /  -0.516520362414E+00/
      data y_data(   309,   2) /   0.699624695033E+01/
      data y_data(   309,   3) /   0.893302897223E+01/
      data x_data(   310     ) /   0.215247770000E+02/
      data y_data(   310,   1) /  -0.503722478007E+00/
      data y_data(   310,   2) /   0.702080538919E+01/
      data y_data(   310,   3) /   0.894014790164E+01/
      data x_data(   311     ) /   0.215945960000E+02/
      data y_data(   311,   1) /  -0.484743646782E+00/
      data y_data(   311,   2) /   0.703915106991E+01/
      data y_data(   311,   3) /   0.894014803618E+01/
      data x_data(   312     ) /   0.216644140000E+02/
      data y_data(   312,   1) /  -0.465765057090E+00/
      data y_data(   312,   2) /   0.705748690432E+01/
      data y_data(   312,   3) /   0.894016542915E+01/
      data x_data(   313     ) /   0.217342330000E+02/
      data y_data(   313,   1) /  -0.446787142368E+00/
      data y_data(   313,   2) /   0.707581305975E+01/
      data y_data(   313,   3) /   0.894020079504E+01/
      data x_data(   314     ) /   0.218040510000E+02/
      data y_data(   314,   1) /  -0.427809311238E+00/
      data y_data(   314,   2) /   0.709412860636E+01/
      data y_data(   314,   3) /   0.894025447530E+01/
      data x_data(   315     ) /   0.218738700000E+02/
      data y_data(   315,   1) /  -0.408832017187E+00/
      data y_data(   315,   2) /   0.711243348340E+01/
      data y_data(   315,   3) /   0.894032532256E+01/
      data x_data(   316     ) /   0.219436890000E+02/
      data y_data(   316,   1) /  -0.389854306729E+00/
      data y_data(   316,   2) /   0.713072913883E+01/
      data y_data(   316,   3) /   0.894041548418E+01/
      data x_data(   317     ) /   0.220135070000E+02/
      data y_data(   317,   1) /  -0.370877180047E+00/
      data y_data(   317,   2) /   0.714901448130E+01/
      data y_data(   317,   3) /   0.894052316436E+01/
      data x_data(   318     ) /   0.220833260000E+02/
      data y_data(   318,   1) /  -0.351900477284E+00/
      data y_data(   318,   2) /   0.716728885822E+01/
      data y_data(   318,   3) /   0.894064821596E+01/
      data x_data(   319     ) /   0.221531440000E+02/
      data y_data(   319,   1) /  -0.321998554986E+00/
      data y_data(   319,   2) /   0.716859970077E+01/
      data y_data(   319,   3) /   0.892780010036E+01/
      data x_data(   320     ) /   0.222229630000E+02/
      data y_data(   320,   1) /  -0.292082056367E+00/
      data y_data(   320,   2) /   0.716989257761E+01/
      data y_data(   320,   3) /   0.891495133494E+01/
      data x_data(   321     ) /   0.222927820000E+02/
      data y_data(   321,   1) /  -0.262151641645E+00/
      data y_data(   321,   2) /   0.717116823304E+01/
      data y_data(   321,   3) /   0.890210060936E+01/
      data x_data(   322     ) /   0.223626000000E+02/
      data y_data(   322,   1) /  -0.232206719528E+00/
      data y_data(   322,   2) /   0.717242607571E+01/
      data y_data(   322,   3) /   0.888924858516E+01/
      data x_data(   323     ) /   0.224324190000E+02/
      data y_data(   323,   1) /  -0.202247016464E+00/
      data y_data(   323,   2) /   0.717366715669E+01/
      data y_data(   323,   3) /   0.887639593261E+01/
      data x_data(   324     ) /   0.225022370000E+02/
      data y_data(   324,   1) /  -0.172273890200E+00/
      data y_data(   324,   2) /   0.717488979518E+01/
      data y_data(   324,   3) /   0.886354111262E+01/
      data x_data(   325     ) /   0.225720560000E+02/
      data y_data(   325,   1) /  -0.142286095547E+00/
      data y_data(   325,   2) /   0.717609567182E+01/
      data y_data(   325,   3) /   0.885068516439E+01/
      data x_data(   326     ) /   0.226418750000E+02/
      data y_data(   326,   1) /  -0.106349939887E+00/
      data y_data(   326,   2) /   0.716075069959E+01/
      data y_data(   326,   3) /   0.882526554721E+01/
      data x_data(   327     ) /   0.227116930000E+02/
      data y_data(   327,   1) /  -0.663239397004E-01/
      data y_data(   327,   2) /   0.713395284923E+01/
      data y_data(   327,   3) /   0.879115918369E+01/
      data x_data(   328     ) /   0.227815120000E+02/
      data y_data(   328,   1) /  -0.263218580687E-01/
      data y_data(   328,   2) /   0.710710879653E+01/
      data y_data(   328,   3) /   0.875703473908E+01/
      data x_data(   329     ) /   0.228513300000E+02/
      data y_data(   329,   1) /   0.136559381821E-01/
      data y_data(   329,   2) /   0.708021974232E+01/
      data y_data(   329,   3) /   0.872289407997E+01/
      data x_data(   330     ) /   0.229211490000E+02/
      data y_data(   330,   1) /   0.536100194861E-01/
      data y_data(   330,   2) /   0.705328539347E+01/
      data y_data(   330,   3) /   0.868873533948E+01/
      data x_data(   331     ) /   0.229909680000E+02/
      data y_data(   331,   1) /   0.935396625274E-01/
      data y_data(   331,   2) /   0.702630548768E+01/
      data y_data(   331,   3) /   0.865456012903E+01/
      data x_data(   332     ) /   0.230607860000E+02/
      data y_data(   332,   1) /   0.133445163539E+00/
      data y_data(   332,   2) /   0.699928072981E+01/
      data y_data(   332,   3) /   0.862036817437E+01/
      data x_data(   333     ) /   0.231306050000E+02/
      data y_data(   333,   1) /   0.173326244346E+00/
      data y_data(   333,   2) /   0.697221008463E+01/
      data y_data(   333,   3) /   0.858615852517E+01/
      data x_data(   334     ) /   0.232004230000E+02/
      data y_data(   334,   1) /   0.213183041422E+00/
      data y_data(   334,   2) /   0.694509432716E+01/
      data y_data(   334,   3) /   0.855193257065E+01/
      data x_data(   335     ) /   0.232702420000E+02/
      data y_data(   335,   1) /   0.271882621901E+00/
      data y_data(   335,   2) /   0.689194047731E+01/
      data y_data(   335,   3) /   0.849045092130E+01/
      data x_data(   336     ) /   0.233400610000E+02/
      data y_data(   336,   1) /   0.330580264942E+00/
      data y_data(   336,   2) /   0.683874057151E+01/
      data y_data(   336,   3) /   0.842895561937E+01/
      data x_data(   337     ) /   0.234098790000E+02/
      data y_data(   337,   1) /   0.389276062513E+00/
      data y_data(   337,   2) /   0.678549551893E+01/
      data y_data(   337,   3) /   0.836744746079E+01/
      data x_data(   338     ) /   0.234796980000E+02/
      data y_data(   338,   1) /   0.447969846761E+00/
      data y_data(   338,   2) /   0.673220316846E+01/
      data y_data(   338,   3) /   0.830592531125E+01/
      data x_data(   339     ) /   0.235495160000E+02/
      data y_data(   339,   1) /   0.506662144662E+00/
      data y_data(   339,   2) /   0.667886591201E+01/
      data y_data(   339,   3) /   0.824438985706E+01/
      data x_data(   340     ) /   0.236193350000E+02/
      data y_data(   340,   1) /   0.565352224316E+00/
      data y_data(   340,   2) /   0.662548256114E+01/
      data y_data(   340,   3) /   0.818284041165E+01/
      data x_data(   341     ) /   0.236891540000E+02/
      data y_data(   341,   1) /   0.624041163093E+00/
      data y_data(   341,   2) /   0.657205285961E+01/
      data y_data(   341,   3) /   0.812127790546E+01/
      data x_data(   342     ) /   0.237589720000E+02/
      data y_data(   342,   1) /   0.686556819123E+00/
      data y_data(   342,   2) /   0.650378955698E+01/
      data y_data(   342,   3) /   0.803978441246E+01/
      data x_data(   343     ) /   0.238287910000E+02/
      data y_data(   343,   1) /   0.751760979526E+00/
      data y_data(   343,   2) /   0.642528273321E+01/
      data y_data(   343,   3) /   0.794451731244E+01/
      data x_data(   344     ) /   0.238986090000E+02/
      data y_data(   344,   1) /   0.817040487095E+00/
      data y_data(   344,   2) /   0.634675570631E+01/
      data y_data(   344,   3) /   0.784923228127E+01/
      data x_data(   345     ) /   0.239684280000E+02/
      data y_data(   345,   1) /   0.882395148069E+00/
      data y_data(   345,   2) /   0.626820838245E+01/
      data y_data(   345,   3) /   0.775393047680E+01/
      data x_data(   346     ) /   0.240382470000E+02/
      data y_data(   346,   1) /   0.947824834472E+00/
      data y_data(   346,   2) /   0.618964235493E+01/
      data y_data(   346,   3) /   0.765860951325E+01/
      data x_data(   347     ) /   0.241080650000E+02/
      data y_data(   347,   1) /   0.101332913692E+01/
      data y_data(   347,   2) /   0.611105582819E+01/
      data y_data(   347,   3) /   0.756327168661E+01/
      data x_data(   348     ) /   0.241778840000E+02/
      data y_data(   348,   1) /   0.107890900301E+01/
      data y_data(   348,   2) /   0.603244950417E+01/
      data y_data(   348,   3) /   0.746791408614E+01/
      data x_data(   349     ) /   0.242477020000E+02/
      data y_data(   349,   1) /   0.114456350916E+01/
      data y_data(   349,   2) /   0.595382347753E+01/
      data y_data(   349,   3) /   0.737254075969E+01/
      data x_data(   350     ) /   0.243175210000E+02/
      data y_data(   350,   1) /   0.121029317156E+01/
      data y_data(   350,   2) /   0.587517794914E+01/
      data y_data(   350,   3) /   0.727714775050E+01/
      data x_data(   351     ) /   0.243873400000E+02/
      data y_data(   351,   1) /   0.128014235796E+01/
      data y_data(   351,   2) /   0.577808962589E+01/
      data y_data(   351,   3) /   0.715888228694E+01/
      data x_data(   352     ) /   0.244571580000E+02/
      data y_data(   352,   1) /   0.135002815898E+01/
      data y_data(   352,   2) /   0.568101559940E+01/
      data y_data(   352,   3) /   0.704059316504E+01/
      data x_data(   353     ) /   0.245269770000E+02/
      data y_data(   353,   1) /   0.141995052650E+01/
      data y_data(   353,   2) /   0.558395507086E+01/
      data y_data(   353,   3) /   0.692228135983E+01/
      data x_data(   354     ) /   0.245967950000E+02/
      data y_data(   354,   1) /   0.148990882696E+01/
      data y_data(   354,   2) /   0.548690824874E+01/
      data y_data(   354,   3) /   0.680394723811E+01/
      data x_data(   355     ) /   0.246666140000E+02/
      data y_data(   355,   1) /   0.155990419505E+01/
      data y_data(   355,   2) /   0.538987522010E+01/
      data y_data(   355,   3) /   0.668558952419E+01/
      data x_data(   356     ) /   0.247364330000E+02/
      data y_data(   356,   1) /   0.162993538145E+01/
      data y_data(   356,   2) /   0.529285619258E+01/
      data y_data(   356,   3) /   0.656720876490E+01/
      data x_data(   357     ) /   0.248062510000E+02/
      data y_data(   357,   1) /   0.170000268105E+01/
      data y_data(   357,   2) /   0.519585137061E+01/
      data y_data(   357,   3) /   0.644880643919E+01/
      data x_data(   358     ) /   0.248760700000E+02/
      data y_data(   358,   1) /   0.175870109941E+01/
      data y_data(   358,   2) /   0.508675781988E+01/
      data y_data(   358,   3) /   0.632275073316E+01/
      data x_data(   359     ) /   0.249458880000E+02/
      data y_data(   359,   1) /   0.180950280063E+01/
      data y_data(   359,   2) /   0.496933067266E+01/
      data y_data(   359,   3) /   0.619141945271E+01/
      data x_data(   360     ) /   0.250157070000E+02/
      data y_data(   360,   1) /   0.186024854985E+01/
      data y_data(   360,   2) /   0.485193219197E+01/
      data y_data(   360,   3) /   0.606009213276E+01/
      data x_data(   361     ) /   0.250855260000E+02/
      data y_data(   361,   1) /   0.191093722934E+01/
      data y_data(   361,   2) /   0.473456403654E+01/
      data y_data(   361,   3) /   0.592876963895E+01/
      data x_data(   362     ) /   0.251553440000E+02/
      data y_data(   362,   1) /   0.196156943134E+01/
      data y_data(   362,   2) /   0.461722568492E+01/
      data y_data(   362,   3) /   0.579745194976E+01/
      data x_data(   363     ) /   0.252251630000E+02/
      data y_data(   363,   1) /   0.201214517978E+01/
      data y_data(   363,   2) /   0.449991640862E+01/
      data y_data(   363,   3) /   0.566613883429E+01/
      data x_data(   364     ) /   0.252949810000E+02/
      data y_data(   364,   1) /   0.206266458656E+01/
      data y_data(   364,   2) /   0.438263776119E+01/
      data y_data(   364,   3) /   0.553483075776E+01/
      data x_data(   365     ) /   0.253648000000E+02/
      data y_data(   365,   1) /   0.211312763022E+01/
      data y_data(   365,   2) /   0.426538878070E+01/
      data y_data(   365,   3) /   0.540352673388E+01/
      data x_data(   366     ) /   0.254346190000E+02/
      data y_data(   366,   1) /   0.216353430971E+01/
      data y_data(   366,   2) /   0.414816942101E+01/
      data y_data(   366,   3) /   0.527222724008E+01/
      data x_data(   367     ) /   0.255044370000E+02/
      data y_data(   367,   1) /   0.215625801300E+01/
      data y_data(   367,   2) /   0.402076477345E+01/
      data y_data(   367,   3) /   0.514201525481E+01/
      data x_data(   368     ) /   0.255742560000E+02/
      data y_data(   368,   1) /   0.214895796442E+01/
      data y_data(   368,   2) /   0.389335349736E+01/
      data y_data(   368,   3) /   0.501184663968E+01/
      data x_data(   369     ) /   0.256440740000E+02/
      data y_data(   369,   1) /   0.214163366822E+01/
      data y_data(   369,   2) /   0.376593734971E+01/
      data y_data(   369,   3) /   0.488172365427E+01/
      data x_data(   370     ) /   0.257138930000E+02/
      data y_data(   370,   1) /   0.213428621059E+01/
      data y_data(   370,   2) /   0.363851486944E+01/
      data y_data(   370,   3) /   0.475164424354E+01/
      data x_data(   371     ) /   0.257837120000E+02/
      data y_data(   371,   1) /   0.212691439008E+01/
      data y_data(   371,   2) /   0.351108650975E+01/
      data y_data(   371,   3) /   0.462160963694E+01/
      data x_data(   372     ) /   0.258535300000E+02/
      data y_data(   372,   1) /   0.211951879893E+01/
      data y_data(   372,   2) /   0.338365236197E+01/
      data y_data(   372,   3) /   0.449162055986E+01/
      data x_data(   373     ) /   0.259233490000E+02/
      data y_data(   373,   1) /   0.211209984052E+01/
      data y_data(   373,   2) /   0.325621238183E+01/
      data y_data(   373,   3) /   0.436167474080E+01/
      data x_data(   374     ) /   0.259931670000E+02/
      data y_data(   374,   1) /   0.208590519538E+01/
      data y_data(   374,   2) /   0.314724789687E+01/
      data y_data(   374,   3) /   0.423880285436E+01/
      data x_data(   375     ) /   0.260629860000E+02/
      data y_data(   375,   1) /   0.204678955787E+01/
      data y_data(   375,   2) /   0.305102760857E+01/
      data y_data(   375,   3) /   0.412081106507E+01/
      data x_data(   376     ) /   0.261328050000E+02/
      data y_data(   376,   1) /   0.200774344854E+01/
      data y_data(   376,   2) /   0.295477814502E+01/
      data y_data(   376,   3) /   0.400283462283E+01/
      data x_data(   377     ) /   0.262026230000E+02/
      data y_data(   377,   1) /   0.196876554947E+01/
      data y_data(   377,   2) /   0.285849852782E+01/
      data y_data(   377,   3) /   0.388487252798E+01/
      data x_data(   378     ) /   0.262724420000E+02/
      data y_data(   378,   1) /   0.192985682135E+01/
      data y_data(   378,   2) /   0.276218883070E+01/
      data y_data(   378,   3) /   0.376692453410E+01/
      data x_data(   379     ) /   0.263422600000E+02/
      data y_data(   379,   1) /   0.189101692171E+01/
      data y_data(   379,   2) /   0.266584950942E+01/
      data y_data(   379,   3) /   0.364899164372E+01/
      data x_data(   380     ) /   0.264120790000E+02/
      data y_data(   380,   1) /   0.185224519415E+01/
      data y_data(   380,   2) /   0.256947972064E+01/
      data y_data(   380,   3) /   0.353107185389E+01/
      data x_data(   381     ) /   0.264818980000E+02/
      data y_data(   381,   1) /   0.181354267629E+01/
      data y_data(   381,   2) /   0.247308046135E+01/
      data y_data(   381,   3) /   0.341316691165E+01/
      data x_data(   382     ) /   0.265517160000E+02/
      data y_data(   382,   1) /   0.177490868434E+01/
      data y_data(   382,   2) /   0.237665193611E+01/
      data y_data(   382,   3) /   0.329527711307E+01/
      data x_data(   383     ) /   0.266215350000E+02/
      data y_data(   383,   1) /   0.172794704910E+01/
      data y_data(   383,   2) /   0.229019814703E+01/
      data y_data(   383,   3) /   0.317686902718E+01/
      data x_data(   384     ) /   0.266913530000E+02/
      data y_data(   384,   1) /   0.168106055658E+01/
      data y_data(   384,   2) /   0.220377062198E+01/
      data y_data(   384,   3) /   0.305837393308E+01/
      data x_data(   385     ) /   0.267611720000E+02/
      data y_data(   385,   1) /   0.163424942191E+01/
      data y_data(   385,   2) /   0.211736912845E+01/
      data y_data(   385,   3) /   0.293979143844E+01/
      data x_data(   386     ) /   0.268309910000E+02/
      data y_data(   386,   1) /   0.158751381257E+01/
      data y_data(   386,   2) /   0.203099357342E+01/
      data y_data(   386,   3) /   0.282112120047E+01/
      data x_data(   387     ) /   0.269008090000E+02/
      data y_data(   387,   1) /   0.154085341067E+01/
      data y_data(   387,   2) /   0.194464454866E+01/
      data y_data(   387,   3) /   0.270236390243E+01/
      data x_data(   388     ) /   0.269706280000E+02/
      data y_data(   388,   1) /   0.149426818538E+01/
      data y_data(   388,   2) /   0.185832025910E+01/
      data y_data(   388,   3) /   0.258351831600E+01/
      data x_data(   389     ) /   0.270404460000E+02/
      data y_data(   389,   1) /   0.144775878291E+01/
      data y_data(   389,   2) /   0.177202323454E+01/
      data y_data(   389,   3) /   0.246458651818E+01/
      data x_data(   390     ) /   0.271102650000E+02/
      data y_data(   390,   1) /   0.140955912612E+01/
      data y_data(   390,   2) /   0.169754637983E+01/
      data y_data(   390,   3) /   0.237131597103E+01/
      data x_data(   391     ) /   0.271800840000E+02/
      data y_data(   391,   1) /   0.137713277608E+01/
      data y_data(   391,   2) /   0.163127860887E+01/
      data y_data(   391,   3) /   0.229581175236E+01/
      data x_data(   392     ) /   0.272499020000E+02/
      data y_data(   392,   1) /   0.134479666319E+01/
      data y_data(   392,   2) /   0.156509725128E+01/
      data y_data(   392,   3) /   0.222033353516E+01/
      data x_data(   393     ) /   0.273197210000E+02/
      data y_data(   393,   1) /   0.131255257600E+01/
      data y_data(   393,   2) /   0.149900265843E+01/
      data y_data(   393,   3) /   0.214488222356E+01/
      data x_data(   394     ) /   0.273895390000E+02/
      data y_data(   394,   1) /   0.128039946235E+01/
      data y_data(   394,   2) /   0.143299450459E+01/
      data y_data(   394,   3) /   0.206945700524E+01/
      data x_data(   395     ) /   0.274593580000E+02/
      data y_data(   395,   1) /   0.124833758018E+01/
      data y_data(   395,   2) /   0.136707211652E+01/
      data y_data(   395,   3) /   0.199405839902E+01/
      data x_data(   396     ) /   0.275291770000E+02/
      data y_data(   396,   1) /   0.121636673014E+01/
      data y_data(   396,   2) /   0.130123664129E+01/
      data y_data(   396,   3) /   0.191868638462E+01/
      data x_data(   397     ) /   0.275989950000E+02/
      data y_data(   397,   1) /   0.118444980694E+01/
      data y_data(   397,   2) /   0.123546142672E+01/
      data y_data(   397,   3) /   0.184328410663E+01/
      data x_data(   398     ) /   0.276688140000E+02/
      data y_data(   398,   1) /   0.115255930694E+01/
      data y_data(   398,   2) /   0.116972942672E+01/
      data y_data(   398,   3) /   0.176781310663E+01/
      data x_data(   399     ) /   0.300000000000E+02/
      data y_data(   399,   1) /   0.000000000000E+00/
      data y_data(   399,   2) /   0.000000000000E+00/
      data y_data(   399,   3) /   0.000000000000E+00/
c
c     interpolation routine
c
      loside = 0
      hiside = 0
      if (x .le. x_data(1)) then
         loside = 1
         hiside = 1
      end if
      if (x .ge. x_data(N)) then
         loside = N
         hiside = N
      end if
      if (loside.eq.0) then
         do i = 1, N-1
            if ( (x .ge. x_data(i))
     &           .and.
     &           (x .le. x_data(i+1)) ) then
               loside  = i
               hiside  = i+1
            end if
         end do
      end if
 
      do j = 1, M

         x1 = x_data(loside)
         y1 = y_data(loside,j)
         
         x2 = x_data(hiside)
         y2 = y_data(hiside,j)
         
         if (loside.eq.hiside) then
            dydx = 0.d0
         else
            dydx = (y2-y1)/(x2-x1)
         end if
         
         y_vector(j) = y1 + dydx*(x - x1)
      end do
      end
c     LAST LINE
c-------------------------------------------------
