c-------------------------------------------------
c                                                 
c                                                 
c                              -USAGE-            
c                                                 
c     OVERVIEW: call ball      (xlo,xhi,y,Niny)   
c     computes y(xlo,xhi) by averaging data over  
c     the range [xlo,xhi]. Here x is a scalar, y  
c     a vector, with Niny components used. Piece- 
c     constant Extrapolation is applied to points 
c     laying outside the range of the orig data   
c                                                 
c     domain: x in [ 0.00000E+00, 0.50314E+01]  
c     number of states in vector y:    12         
c     number of x data points:    50              
c                                                 
c     CALLING PROGRAM NEEDS: none                 
c     PROCEDURE NEEDS:  none                      
c     COMPILER NEEDS: f77, long names (14 char)   
c     SYSTEM NEEDS: none                          
c     NOTES: This routine was generated by        
c     subroutine makeRoutine.                     
c                                                 
c-------------------------------------------------
c                                                 
c                          -SPECIFICATION-        
c     SYNTAX:                                     
c     subroutine ball      (xlo,xhi:dp,y:dp arr, Niny: int)
c     returns: none                               
c     REQUIRES: none                              
c     MODIFIES: y, N                              
c     SIGNALS: none                               
c     EFFECTS: computes the average value of y    
c     over the range [xlo,xhi] and returns number 
c     of components used, N.                      
c                                                 
c-------------------------------------------------
c                                                 
c                         -IMPLEMENTATION-        
c     AUTHOR: auto-generated by makeAveInterp     
c     MODIFICATION HISTORY: none                  
c     NOTES: interpolation x,y data is defined in 
c     data statements for efficiency.             
c     REQUIRES: none                              
c     LOCAL VARIABLES:                            
c     xlo,xhi.........(dp) average y on this range
c     y_vector........(1D dp arr) computed y(x)   
c     Niny............(int) no. of used components
c     x_data..........(dp) x data points          
c     y_data..........(dp) y(x) data points       
c     N...............(int) number of x points    
c     M...............(int) dimension of y_data   
c     i,j,k...........(int) loop index            
c     lo_{lo,hi}side..(int) idx of data near xlo  
c     hi_{lo,hi}side..(int) idx of data near xhi  
c     x1..............(dp) interpolation point    
c     x2..............(dp) interpolation point    
c     y1..............(dp) interpolation value    
c     y2..............(dp) interpolation value    
c     dydx............(dp) slope of linear interp 
c     ylo.............(dp) value at xlo           
c     yhi.............(dp) value at xhi           
c     GLOBAL VARIABLES:none                       
c     PROCEDURES: none                            
c     FILES: none                                 
c     I/O: none                                   
c-------------------------------------------------
c                                                 
c                             -CODE-              
c     FIRST LINE:                                 
      subroutine ball      (xlo,xhi,y_vector,Niny)
c                                                 
c     declare local variables                     
c                                                 
      integer N,M,i,j,k,lo_loside,lo_hiside       
      integer hi_loside,hi_hiside,Niny            
      double precision xlo,xhi,y_vector(*),sum    
      double precision ylo,yhi,x1,y1,x2,y2,dydx   
      double precision x_data(    50)              
      double precision y_data(    50,    12)        
      data N,M /    50,    12/                   
      Niny =     12                                
c                                                 
c     interpolation x,y data                      
c                                                 
      data x_data(     1     ) /  0.000000000000D+00/
      data y_data(     1,   1) /  0.000000000000D+00/
      data y_data(     1,   2) /  0.219884800000D+04/
      data y_data(     1,   3) /  0.117296000000D+06/
      data y_data(     1,   4) /  0.510272000000D+00/
      data y_data(     1,   5) /  0.562283700000D-03/
      data y_data(     1,   6) /  0.295143900000D-08/
      data y_data(     1,   7) /  0.204325600000D-07/
      data y_data(     1,   8) /  0.272361000000D-04/
      data y_data(     1,   9) /  0.302101200000D-10/
      data y_data(     1,  10) /  0.231037300000D-09/
      data y_data(     1,  11) /  0.173877200000D+00/
      data y_data(     1,  12) /  0.315261300000D+00/
      data x_data(     2     ) /  0.171008700000D+00/
      data y_data(     2,   1) /  0.123568500000D-04/
      data y_data(     2,   2) /  0.219884800000D+04/
      data y_data(     2,   3) /  0.117296000000D+06/
      data y_data(     2,   4) /  0.510272000000D+00/
      data y_data(     2,   5) /  0.562283700000D-03/
      data y_data(     2,   6) /  0.295143900000D-08/
      data y_data(     2,   7) /  0.204325600000D-07/
      data y_data(     2,   8) /  0.272361000000D-04/
      data y_data(     2,   9) /  0.302101200000D-10/
      data y_data(     2,  10) /  0.231037300000D-09/
      data y_data(     2,  11) /  0.173877200000D+00/
      data y_data(     2,  12) /  0.315261300000D+00/
      data x_data(     3     ) /  0.339112400000D+00/
      data y_data(     3,   1) /  0.722746000000D-04/
      data y_data(     3,   2) /  0.220410200000D+04/
      data y_data(     3,   3) /  0.413016100000D+05/
      data y_data(     3,   4) /  0.509265900000D+00/
      data y_data(     3,   5) /  0.578648500000D-03/
      data y_data(     3,   6) /  0.317606700000D-08/
      data y_data(     3,   7) /  0.219144800000D-07/
      data y_data(     3,   8) /  0.283600400000D-04/
      data y_data(     3,   9) /  0.325044800000D-10/
      data y_data(     3,  10) /  0.243681300000D-09/
      data y_data(     3,  11) /  0.174198700000D+00/
      data y_data(     3,  12) /  0.315928300000D+00/
      data x_data(     4     ) /  0.500180000000D+00/
      data y_data(     4,   1) /  0.217840500000D-03/
      data y_data(     4,   2) /  0.221864000000D+04/
      data y_data(     4,   3) / -0.201312400000D+06/
      data y_data(     4,   4) /  0.505394700000D+00/
      data y_data(     4,   5) /  0.625320200000D-03/
      data y_data(     4,   6) /  0.391872800000D-08/
      data y_data(     4,   7) /  0.266727400000D-07/
      data y_data(     4,   8) /  0.317929200000D-04/
      data y_data(     4,   9) /  0.400441200000D-10/
      data y_data(     4,  10) /  0.283934600000D-09/
      data y_data(     4,  11) /  0.175481200000D+00/
      data y_data(     4,  12) /  0.318467000000D+00/
      data x_data(     5     ) /  0.644338500000D+00/
      data y_data(     5,   1) /  0.456986300000D-03/
      data y_data(     5,   2) /  0.224967000000D+04/
      data y_data(     5,   3) / -0.879646000000D+06/
      data y_data(     5,   4) /  0.493660300000D+00/
      data y_data(     5,   5) /  0.732720200000D-03/
      data y_data(     5,   6) /  0.625744200000D-08/
      data y_data(     5,   7) /  0.408078800000D-07/
      data y_data(     5,   8) /  0.408005000000D-04/
      data y_data(     5,   9) /  0.635007500000D-10/
      data y_data(     5,  10) /  0.399237900000D-09/
      data y_data(     5,  11) /  0.179397600000D+00/
      data y_data(     5,  12) /  0.326168500000D+00/
      data x_data(     6     ) /  0.761212600000D+00/
      data y_data(     6,   1) /  0.752767100000D-03/
      data y_data(     6,   2) /  0.229668500000D+04/
      data y_data(     6,   3) / -0.202481600000D+07/
      data y_data(     6,   4) /  0.468608500000D+00/
      data y_data(     6,   5) /  0.916029400000D-03/
      data y_data(     6,   6) /  0.131728300000D-07/
      data y_data(     6,   7) /  0.783383500000D-07/
      data y_data(     6,   8) /  0.600147100000D-04/
      data y_data(     6,   9) /  0.131166400000D-09/
      data y_data(     6,  10) /  0.685532900000D-09/
      data y_data(     6,  11) /  0.187510700000D+00/
      data y_data(     6,  12) /  0.342904600000D+00/
      data x_data(     7     ) /  0.852461100000D+00/
      data y_data(     7,   1) /  0.106699400000D-02/
      data y_data(     7,   2) /  0.234961300000D+04/
      data y_data(     7,   3) / -0.306258400000D+07/
      data y_data(     7,   4) /  0.431216900000D+00/
      data y_data(     7,   5) /  0.114985200000D-02/
      data y_data(     7,   6) /  0.317625200000D-07/
      data y_data(     7,   7) /  0.164507700000D-06/
      data y_data(     7,   8) /  0.933008100000D-04/
      data y_data(     7,   9) /  0.305723000000D-09/
      data y_data(     7,  10) /  0.129189100000D-08/
      data y_data(     7,  11) /  0.198998800000D+00/
      data y_data(     7,  12) /  0.368540900000D+00/
      data x_data(     8     ) /  0.929315700000D+00/
      data y_data(     8,   1) /  0.140464200000D-02/
      data y_data(     8,   2) /  0.240412800000D+04/
      data y_data(     8,   3) / -0.377804100000D+07/
      data y_data(     8,   4) /  0.384018900000D+00/
      data y_data(     8,   5) /  0.141407000000D-02/
      data y_data(     8,   6) /  0.824614700000D-07/
      data y_data(     8,   7) /  0.356769300000D-06/
      data y_data(     8,   8) /  0.147949100000D-03/
      data y_data(     8,   9) /  0.754720400000D-09/
      data y_data(     8,  10) /  0.254394400000D-08/
      data y_data(     8,  11) /  0.213072800000D+00/
      data y_data(     8,  12) /  0.401345900000D+00/
      data x_data(     9     ) /  0.997377400000D+00/
      data y_data(     9,   1) /  0.177224900000D-02/
      data y_data(     9,   2) /  0.245795400000D+04/
      data y_data(     9,   3) / -0.360788100000D+07/
      data y_data(     9,   4) /  0.331181100000D+00/
      data y_data(     9,   5) /  0.168635500000D-02/
      data y_data(     9,   6) /  0.222606800000D-06/
      data y_data(     9,   7) /  0.775993500000D-06/
      data y_data(     9,   8) /  0.234845500000D-03/
      data y_data(     9,   9) /  0.190571600000D-08/
      data y_data(     9,  10) /  0.509075200000D-08/
      data y_data(     9,  11) /  0.229002200000D+00/
      data y_data(     9,  12) /  0.437894500000D+00/
      data x_data(    10     ) /  0.106401700000D+01/
      data y_data(    10,   1) /  0.220490000000D-02/
      data y_data(    10,   2) /  0.251355000000D+04/
      data y_data(    10,   3) / -0.136745800000D+07/
      data y_data(    10,   4) /  0.271843500000D+00/
      data y_data(    10,   5) /  0.195640500000D-02/
      data y_data(    10,   6) /  0.667622300000D-06/
      data y_data(    10,   7) /  0.177314600000D-05/
      data y_data(    10,   8) /  0.383115300000D-03/
      data y_data(    10,   9) /  0.521540300000D-08/
      data y_data(    10,  10) /  0.107936200000D-07/
      data y_data(    10,  11) /  0.247719900000D+00/
      data y_data(    10,  12) /  0.478094500000D+00/
      data x_data(    11     ) /  0.112881500000D+01/
      data y_data(    11,   1) /  0.270530500000D-02/
      data y_data(    11,   2) /  0.256843000000D+04/
      data y_data(    11,   3) /  0.275743900000D+07/
      data y_data(    11,   4) /  0.209190500000D+00/
      data y_data(    11,   5) /  0.216810500000D-02/
      data y_data(    11,   6) /  0.221617600000D-05/
      data y_data(    11,   7) /  0.419798900000D-05/
      data y_data(    11,   8) /  0.635225000000D-03/
      data y_data(    11,   9) /  0.152907900000D-07/
      data y_data(    11,  10) /  0.239472100000D-07/
      data y_data(    11,  11) /  0.268301700000D+00/
      data y_data(    11,  12) /  0.519698000000D+00/
      data x_data(    12     ) /  0.121330100000D+01/
      data y_data(    12,   1) /  0.349155000000D-02/
      data y_data(    12,   2) /  0.263923700000D+04/
      data y_data(    12,   3) /  0.665882600000D+06/
      data y_data(    12,   4) /  0.121561500000D+00/
      data y_data(    12,   5) /  0.220312000000D-02/
      data y_data(    12,   6) /  0.151761100000D-04/
      data y_data(    12,   7) /  0.151582900000D-04/
      data y_data(    12,   8) /  0.132549000000D-02/
      data y_data(    12,   9) /  0.804959200000D-07/
      data y_data(    12,  10) /  0.801559300000D-07/
      data y_data(    12,  11) /  0.297072500000D+00/
      data y_data(    12,  12) /  0.577806900000D+00/
      data x_data(    13     ) /  0.129355000000D+01/
      data y_data(    13,   1) /  0.438315300000D-02/
      data y_data(    13,   2) /  0.270087100000D+04/
      data y_data(    13,   3) / -0.510439900000D+08/
      data y_data(    13,   4) /  0.486760900000D-01/
      data y_data(    13,   5) /  0.176893800000D-02/
      data y_data(    13,   6) /  0.181926200000D-03/
      data y_data(    13,   7) /  0.685179000000D-04/
      data y_data(    13,   8) /  0.301392700000D-02/
      data y_data(    13,   9) /  0.614931600000D-06/
      data y_data(    13,  10) /  0.333481600000D-06/
      data y_data(    13,  11) /  0.316697400000D+00/
      data y_data(    13,  12) /  0.629592200000D+00/
      data x_data(    14     ) /  0.132707400000D+01/
      data y_data(    14,   1) /  0.479945200000D-02/
      data y_data(    14,   2) /  0.271877300000D+04/
      data y_data(    14,   3) / -0.505093500000D+09/
      data y_data(    14,   4) /  0.244420100000D-01/
      data y_data(    14,   5) /  0.134072500000D-02/
      data y_data(    14,   6) /  0.853846600000D-03/
      data y_data(    14,   7) /  0.160030300000D-03/
      data y_data(    14,   8) /  0.467500200000D-02/
      data y_data(    14,   9) /  0.204930900000D-05/
      data y_data(    14,  10) /  0.754723000000D-06/
      data y_data(    14,  11) /  0.319845100000D+00/
      data y_data(    14,  12) /  0.648680400000D+00/
      data x_data(    15     ) /  0.135061300000D+01/
      data y_data(    15,   1) /  0.510988100000D-02/
      data y_data(    15,   2) /  0.271259200000D+04/
      data y_data(    15,   3) / -0.188291100000D+10/
      data y_data(    15,   4) /  0.107744800000D-01/
      data y_data(    15,   5) /  0.870142200000D-03/
      data y_data(    15,   6) /  0.407800400000D-02/
      data y_data(    15,   7) /  0.340904000000D-03/
      data y_data(    15,   8) /  0.675851500000D-02/
      data y_data(    15,   9) /  0.649553800000D-05/
      data y_data(    15,  10) /  0.161088100000D-05/
      data y_data(    15,  11) /  0.315942500000D+00/
      data y_data(    15,  12) /  0.661227300000D+00/
      data x_data(    16     ) /  0.137120200000D+01/
      data y_data(    16,   1) /  0.539888100000D-02/
      data y_data(    16,   2) /  0.266096200000D+04/
      data y_data(    16,   3) / -0.155500600000D+10/
      data y_data(    16,   4) /  0.416372900000D-02/
      data y_data(    16,   5) /  0.444209000000D-03/
      data y_data(    16,   6) /  0.158569300000D-01/
      data y_data(    16,   7) /  0.539248900000D-03/
      data y_data(    16,   8) /  0.803502300000D-02/
      data y_data(    16,   9) /  0.156107800000D-04/
      data y_data(    16,  10) /  0.272504600000D-05/
      data y_data(    16,  11) /  0.299224300000D+00/
      data y_data(    16,  12) /  0.671718200000D+00/
      data x_data(    17     ) /  0.139046300000D+01/
      data y_data(    17,   1) /  0.569039500000D-02/
      data y_data(    17,   2) /  0.257946100000D+04/
      data y_data(    17,   3) / -0.583966200000D+09/
      data y_data(    17,   4) /  0.183806000000D-02/
      data y_data(    17,   5) /  0.212817300000D-03/
      data y_data(    17,   6) /  0.335039100000D-01/
      data y_data(    17,   7) /  0.543489400000D-03/
      data y_data(    17,   8) /  0.737368100000D-02/
      data y_data(    17,   9) /  0.217022400000D-04/
      data y_data(    17,  10) /  0.309419900000D-05/
      data y_data(    17,  11) /  0.275470100000D+00/
      data y_data(    17,  12) /  0.681033100000D+00/
      data x_data(    18     ) /  0.140882000000D+01/
      data y_data(    18,   1) /  0.599046100000D-02/
      data y_data(    18,   2) /  0.248952000000D+04/
      data y_data(    18,   3) / -0.277481100000D+09/
      data y_data(    18,   4) /  0.879678100000D-03/
      data y_data(    18,   5) /  0.100166300000D-03/
      data y_data(    18,   6) /  0.518742100000D-01/
      data y_data(    18,   7) /  0.439203300000D-03/
      data y_data(    18,   8) /  0.597464500000D-02/
      data y_data(    18,   9) /  0.229853200000D-04/
      data y_data(    18,  10) /  0.289227400000D-05/
      data y_data(    18,  11) /  0.251009000000D+00/
      data y_data(    18,  12) /  0.689697300000D+00/
      data x_data(    19     ) /  0.142589000000D+01/
      data y_data(    19,   1) /  0.629111600000D-02/
      data y_data(    19,   2) /  0.240029700000D+04/
      data y_data(    19,   3) / -0.164440300000D+09/
      data y_data(    19,   4) /  0.441074500000D-03/
      data y_data(    19,   5) /  0.470683300000D-04/
      data y_data(    19,   6) /  0.688431700000D-01/
      data y_data(    19,   7) /  0.319452500000D-03/
      data y_data(    19,   8) /  0.456807500000D-02/
      data y_data(    19,   9) /  0.213458400000D-04/
      data y_data(    19,  10) /  0.246630900000D-05/
      data y_data(    19,  11) /  0.228100800000D+00/
      data y_data(    19,  12) /  0.697656600000D+00/
      data x_data(    20     ) /  0.144337300000D+01/
      data y_data(    20,   1) /  0.662315400000D-02/
      data y_data(    20,   2) /  0.230548000000D+04/
      data y_data(    20,   3) / -0.104425800000D+09/
      data y_data(    20,   4) /  0.211537400000D-03/
      data y_data(    20,   5) /  0.203737100000D-04/
      data y_data(    20,   6) /  0.855137000000D-01/
      data y_data(    20,   7) /  0.210113300000D-03/
      data y_data(    20,   8) /  0.327234800000D-02/
      data y_data(    20,   9) /  0.181174800000D-04/
      data y_data(    20,  10) /  0.195398800000D-05/
      data y_data(    20,  11) /  0.205012800000D+00/
      data y_data(    20,  12) /  0.705739100000D+00/
      data x_data(    21     ) /  0.146419000000D+01/
      data y_data(    21,   1) /  0.705389500000D-02/
      data y_data(    21,   2) /  0.218996500000D+04/
      data y_data(    21,   3) / -0.644053100000D+08/
      data y_data(    21,   4) /  0.833750800000D-04/
      data y_data(    21,   5) /  0.683570000000D-05/
      data y_data(    21,   6) /  0.104089600000D+00/
      data y_data(    21,   7) /  0.114689500000D-03/
      data y_data(    21,   8) /  0.205081100000D-02/
      data y_data(    21,   9) /  0.136022400000D-04/
      data y_data(    21,  10) /  0.137288900000D-05/
      data y_data(    21,  11) /  0.178345700000D+00/
      data y_data(    21,  12) /  0.715294000000D+00/
      data x_data(    22     ) /  0.148619900000D+01/
      data y_data(    22,   1) /  0.755616800000D-02/
      data y_data(    22,   2) /  0.206686100000D+04/
      data y_data(    22,   3) / -0.379529500000D+08/
      data y_data(    22,   4) /  0.287814800000D-04/
      data y_data(    22,   5) /  0.190960500000D-05/
      data y_data(    22,   6) /  0.121841100000D+00/
      data y_data(    22,   7) /  0.537954000000D-04/
      data y_data(    22,   8) /  0.115684200000D-02/
      data y_data(    22,   9) /  0.916251300000D-05/
      data y_data(    22,  10) /  0.874061200000D-06/
      data y_data(    22,  11) /  0.151772800000D+00/
      data y_data(    22,  12) /  0.725134700000D+00/
      data x_data(    23     ) /  0.150806400000D+01/
      data y_data(    23,   1) /  0.810867700000D-02/
      data y_data(    23,   2) /  0.194561700000D+04/
      data y_data(    23,   3) / -0.216176300000D+08/
      data y_data(    23,   4) /  0.915167400000D-05/
      data y_data(    23,   5) /  0.473067200000D-06/
      data y_data(    23,   6) /  0.137374300000D+00/
      data y_data(    23,   7) /  0.226384700000D-04/
      data y_data(    23,   8) /  0.606370900000D-03/
      data y_data(    23,   9) /  0.569408600000D-05/
      data y_data(    23,  10) /  0.519348700000D-06/
      data y_data(    23,  11) /  0.127554200000D+00/
      data y_data(    23,  12) /  0.734426600000D+00/
      data x_data(    24     ) /  0.152950600000D+01/
      data y_data(    24,   1) /  0.870794400000D-02/
      data y_data(    24,   2) /  0.182957600000D+04/
      data y_data(    24,   3) / -0.118244100000D+08/
      data y_data(    24,   4) /  0.271677400000D-05/
      data y_data(    24,   5) /  0.106120800000D-06/
      data y_data(    24,   6) /  0.150626700000D+00/
      data y_data(    24,   7) /  0.872601700000D-05/
      data y_data(    24,   8) /  0.299401400000D-03/
      data y_data(    24,   9) /  0.331943800000D-05/
      data y_data(    24,  10) /  0.292274000000D-06/
      data y_data(    24,  11) /  0.106137800000D+00/
      data y_data(    24,  12) /  0.742921000000D+00/
      data x_data(    25     ) /  0.154990600000D+01/
      data y_data(    25,   1) /  0.933616100000D-02/
      data y_data(    25,   2) /  0.172331900000D+04/
      data y_data(    25,   3) / -0.601779200000D+07/
      data y_data(    25,   4) /  0.787254900000D-06/
      data y_data(    25,   5) /  0.228693400000D-07/
      data y_data(    25,   6) /  0.161528000000D+00/
      data y_data(    25,   7) /  0.322114200000D-05/
      data y_data(    25,   8) /  0.143655900000D-03/
      data y_data(    25,   9) /  0.186824800000D-05/
      data y_data(    25,  10) /  0.160160000000D-06/
      data y_data(    25,  11) /  0.879924400000D-01/
      data y_data(    25,  12) /  0.750329800000D+00/
      data x_data(    26     ) /  0.157187000000D+01/
      data y_data(    26,   1) /  0.100822100000D-01/
      data y_data(    26,   2) /  0.161494600000D+04/
      data y_data(    26,   3) / -0.244968600000D+07/
      data y_data(    26,   4) /  0.190415200000D-06/
      data y_data(    26,   5) /  0.391371800000D-08/
      data y_data(    26,   6) /  0.171589500000D+00/
      data y_data(    26,   7) /  0.101062100000D-05/
      data y_data(    26,   8) /  0.611993400000D-04/
      data y_data(    26,   9) /  0.947429300000D-06/
      data y_data(    26,  10) /  0.793771000000D-07/
      data y_data(    26,  11) /  0.708071600000D-01/
      data y_data(    26,  12) /  0.757539900000D+00/
      data x_data(    27     ) /  0.160502500000D+01/
      data y_data(    27,   1) /  0.113599000000D-01/
      data y_data(    27,   2) /  0.146663000000D+04/
      data y_data(    27,   3) / -0.835251800000D+06/
      data y_data(    27,   4) /  0.198454000000D-07/
      data y_data(    27,   5) /  0.232076800000D-09/
      data y_data(    27,   6) /  0.183861800000D+00/
      data y_data(    27,   7) /  0.157748300000D-06/
      data y_data(    27,   8) /  0.154396900000D-04/
      data y_data(    27,   9) /  0.309989800000D-06/
      data y_data(    27,  10) /  0.255334500000D-07/
      data y_data(    27,  11) /  0.491909000000D-01/
      data y_data(    27,  12) /  0.766931300000D+00/
      data x_data(    28     ) /  0.163567300000D+01/
      data y_data(    28,   1) /  0.127160700000D-01/
      data y_data(    28,   2) /  0.134802000000D+04/
      data y_data(    28,   3) / -0.206020500000D+06/
      data y_data(    28,   4) /  0.530351700000D-08/
      data y_data(    28,   5) /  0.157200900000D-10/
      data y_data(    28,   6) /  0.192274100000D+00/
      data y_data(    28,   7) /  0.272668300000D-07/
      data y_data(    28,   8) /  0.412787500000D-05/
      data y_data(    28,   9) /  0.103665900000D-06/
      data y_data(    28,  10) /  0.865399200000D-08/
      data y_data(    28,  11) /  0.339512500000D-01/
      data y_data(    28,  12) /  0.773770400000D+00/
      data x_data(    29     ) /  0.167303800000D+01/
      data y_data(    29,   1) /  0.146113100000D-01/
      data y_data(    29,   2) /  0.123029800000D+04/
      data y_data(    29,   3) / -0.263963700000D+06/
      data y_data(    29,   4) /  0.279071700000D-06/
      data y_data(    29,   5) /  0.304683800000D-11/
      data y_data(    29,   6) /  0.199513400000D+00/
      data y_data(    29,   7) /  0.117395200000D-08/
      data y_data(    29,   8) /  0.471753500000D-06/
      data y_data(    29,   9) /  0.988443300000D-07/
      data y_data(    29,  10) /  0.757128100000D-09/
      data y_data(    29,  11) /  0.204988300000D-01/
      data y_data(    29,  12) /  0.779986900000D+00/
      data x_data(    30     ) /  0.172597900000D+01/
      data y_data(    30,   1) /  0.177487500000D-01/
      data y_data(    30,   2) /  0.111439500000D+04/
      data y_data(    30,   3) / -0.287772000000D+06/
      data y_data(    30,   4) /  0.582176500000D-05/
      data y_data(    30,   5) /  0.174457700000D-11/
      data y_data(    30,   6) /  0.205488000000D+00/
      data y_data(    30,   7) /  0.173866300000D-09/
      data y_data(    30,   8) /  0.307792900000D-07/
      data y_data(    30,   9) /  0.262722600000D-06/
      data y_data(    30,  10) /  0.960964500000D-09/
      data y_data(    30,  11) /  0.901985300000D-02/
      data y_data(    30,  12) /  0.785486000000D+00/
      data x_data(    31     ) /  0.182070100000D+01/
      data y_data(    31,   1) /  0.244707800000D-01/
      data y_data(    31,   2) /  0.102736500000D+04/
      data y_data(    31,   3) / -0.373962200000D+06/
      data y_data(    31,   4) /  0.243336400000D-04/
      data y_data(    31,   5) /  0.138615800000D-11/
      data y_data(    31,   6) /  0.209053300000D+00/
      data y_data(    31,   7) /  0.532686900000D-09/
      data y_data(    31,   8) /  0.105031100000D-07/
      data y_data(    31,   9) /  0.309262600000D-06/
      data y_data(    31,  10) /  0.705667800000D-08/
      data y_data(    31,  11) /  0.190726100000D-02/
      data y_data(    31,  12) /  0.789014800000D+00/
      data x_data(    32     ) /  0.197091000000D+01/
      data y_data(    32,   1) /  0.373255500000D-01/
      data y_data(    32,   2) /  0.100270400000D+04/
      data y_data(    32,   3) / -0.264599600000D+06/
      data y_data(    32,   4) /  0.282828800000D-04/
      data y_data(    32,   5) /  0.906164100000D-12/
      data y_data(    32,   6) /  0.209913900000D+00/
      data y_data(    32,   7) /  0.930479400000D-09/
      data y_data(    32,   8) /  0.649524500000D-08/
      data y_data(    32,   9) /  0.256572000000D-06/
      data y_data(    32,  10) /  0.837110000000D-08/
      data y_data(    32,  11) /  0.165885700000D-03/
      data y_data(    32,  12) /  0.789891700000D+00/
      data x_data(    33     ) /  0.213847800000D+01/
      data y_data(    33,   1) /  0.543910300000D-01/
      data y_data(    33,   2) /  0.100016700000D+04/
      data y_data(    33,   3) / -0.508760300000D+05/
      data y_data(    33,   4) /  0.103729500000D-04/
      data y_data(    33,   5) /  0.181006400000D-12/
      data y_data(    33,   6) /  0.209993700000D+00/
      data y_data(    33,   7) /  0.560944200000D-09/
      data y_data(    33,   8) /  0.337288000000D-08/
      data y_data(    33,   9) /  0.110830900000D-06/
      data y_data(    33,  10) /  0.165611400000D-08/
      data y_data(    33,  11) /  0.909492500000D-05/
      data y_data(    33,  12) /  0.789986700000D+00/
      data x_data(    34     ) /  0.230766200000D+01/
      data y_data(    34,   1) /  0.745825100000D-01/
      data y_data(    34,   2) /  0.100000700000D+04/
      data y_data(    34,   3) / -0.315683300000D+04/
      data y_data(    34,   4) /  0.191325400000D-05/
      data y_data(    34,   5) /  0.141917100000D-13/
      data y_data(    34,   6) /  0.209999500000D+00/
      data y_data(    34,   7) /  0.224248900000D-09/
      data y_data(    34,   8) /  0.112165600000D-08/
      data y_data(    34,   9) /  0.259394500000D-07/
      data y_data(    34,  10) /  0.912597700000D-10/
      data y_data(    34,  11) /  0.330264500000D-06/
      data y_data(    34,  12) /  0.789998200000D+00/
      data x_data(    35     ) /  0.247726100000D+01/
      data y_data(    35,   1) /  0.980231700000D-01/
      data y_data(    35,   2) /  0.100000000000D+04/
      data y_data(    35,   3) / -0.989506300000D+02/
      data y_data(    35,   4) /  0.237293100000D-06/
      data y_data(    35,   5) /  0.818270500000D-15/
      data y_data(    35,   6) /  0.209999900000D+00/
      data y_data(    35,   7) /  0.928643200000D-10/
      data y_data(    35,   8) /  0.291153600000D-09/
      data y_data(    35,   9) /  0.306320700000D-08/
      data y_data(    35,  10) /  0.130292300000D-11/
      data y_data(    35,  11) /  0.968625000000D-08/
      data y_data(    35,  12) /  0.789999800000D+00/
      data x_data(    36     ) /  0.264715200000D+01/
      data y_data(    36,   1) /  0.124950100000D+00/
      data y_data(    36,   2) /  0.100000000000D+04/
      data y_data(    36,   3) / -0.441335700000D+01/
      data y_data(    36,   4) /  0.252422200000D-07/
      data y_data(    36,   5) /  0.494947700000D-16/
      data y_data(    36,   6) /  0.210000000000D+00/
      data y_data(    36,   7) /  0.162203300000D-10/
      data y_data(    36,   8) /  0.140440900000D-09/
      data y_data(    36,   9) /  0.205691700000D-09/
      data y_data(    36,  10) /  0.140940100000D-13/
      data y_data(    36,  11) /  0.327269300000D-09/
      data y_data(    36,  12) /  0.790000000000D+00/
      data x_data(    37     ) /  0.281726600000D+01/
      data y_data(    37,   1) /  0.155605200000D+00/
      data y_data(    37,   2) /  0.100000000000D+04/
      data y_data(    37,   3) / -0.106870300000D-01/
      data y_data(    37,   4) /  0.257359500000D-08/
      data y_data(    37,   5) /  0.157920900000D-17/
      data y_data(    37,   6) /  0.210000000000D+00/
      data y_data(    37,   7) /  0.871087400000D-12/
      data y_data(    37,   8) /  0.297652400000D-10/
      data y_data(    37,   9) /  0.740525800000D-11/
      data y_data(    37,  10) /  0.382254500000D-15/
      data y_data(    37,  11) /  0.877393700000D-11/
      data y_data(    37,  12) /  0.790000000000D+00/
      data x_data(    38     ) /  0.298755500000D+01/
      data y_data(    38,   1) /  0.190230200000D+00/
      data y_data(    38,   2) /  0.100000000000D+04/
      data y_data(    38,   3) /  0.865891000000D-02/
      data y_data(    38,   4) /  0.256438600000D-09/
      data y_data(    38,   5) /  0.563947200000D-19/
      data y_data(    38,   6) /  0.210000000000D+00/
      data y_data(    38,   7) /  0.366781200000D-13/
      data y_data(    38,   8) /  0.356277400000D-11/
      data y_data(    38,   9) /  0.292642700000D-12/
      data y_data(    38,  10) /  0.538893100000D-17/
      data y_data(    38,  11) /  0.178464600000D-12/
      data y_data(    38,  12) /  0.790000000000D+00/
      data x_data(    39     ) /  0.315798100000D+01/
      data y_data(    39,   1) /  0.229067000000D+00/
      data y_data(    39,   2) /  0.100000000000D+04/
      data y_data(    39,   3) /  0.955136400000D-03/
      data y_data(    39,   4) /  0.249376400000D-10/
      data y_data(    39,   5) /  0.371784800000D-20/
      data y_data(    39,   6) /  0.210000000000D+00/
      data y_data(    39,   7) /  0.258259300000D-14/
      data y_data(    39,   8) /  0.357443000000D-12/
      data y_data(    39,   9) /  0.195639900000D-13/
      data y_data(    39,  10) /  0.542470400000D-19/
      data y_data(    39,  11) /  0.293961800000D-14/
      data y_data(    39,  12) /  0.790000000000D+00/
      data x_data(    40     ) /  0.332851800000D+01/
      data y_data(    40,   1) /  0.272357500000D+00/
      data y_data(    40,   2) /  0.100000000000D+04/
      data y_data(    40,   3) /  0.100251300000D-03/
      data y_data(    40,   4) /  0.246289500000D-11/
      data y_data(    40,   5) /  0.347825000000D-21/
      data y_data(    40,   6) /  0.210000000000D+00/
      data y_data(    40,   7) /  0.745427900000D-15/
      data y_data(    40,   8) /  0.360911500000D-13/
      data y_data(    40,   9) /  0.183223000000D-14/
      data y_data(    40,  10) /  0.552986500000D-21/
      data y_data(    40,  11) /  0.413780100000D-16/
      data y_data(    40,  12) /  0.790000000000D+00/
      data x_data(    41     ) /  0.349914500000D+01/
      data y_data(    41,   1) /  0.320343600000D+00/
      data y_data(    41,   2) /  0.100000000000D+04/
      data y_data(    41,   3) /  0.154945600000D-04/
      data y_data(    41,   4) /  0.261392500000D-12/
      data y_data(    41,   5) /  0.380927500000D-22/
      data y_data(    41,   6) /  0.210000000000D+00/
      data y_data(    41,   7) /  0.594327400000D-15/
      data y_data(    41,   8) /  0.399199500000D-14/
      data y_data(    41,   9) /  0.202171500000D-15/
      data y_data(    41,  10) /  0.676129700000D-23/
      data y_data(    41,  11) /  0.527359900000D-18/
      data y_data(    41,  12) /  0.790000000000D+00/
      data x_data(    42     ) /  0.366984500000D+01/
      data y_data(    42,   1) /  0.373267100000D+00/
      data y_data(    42,   2) /  0.100000000000D+04/
      data y_data(    42,   3) /  0.649929100000D-05/
      data y_data(    42,   4) /  0.284277200000D-13/
      data y_data(    42,   5) /  0.412771400000D-23/
      data y_data(    42,   6) /  0.210000000000D+00/
      data y_data(    42,   7) /  0.577973500000D-15/
      data y_data(    42,   8) /  0.434387100000D-15/
      data y_data(    42,   9) /  0.218945100000D-16/
      data y_data(    42,  10) /  0.800684100000D-25/
      data y_data(    42,  11) /  0.637505900000D-20/
      data y_data(    42,  12) /  0.790000000000D+00/
      data x_data(    43     ) /  0.384060500000D+01/
      data y_data(    43,   1) /  0.431369900000D+00/
      data y_data(    43,   2) /  0.100000000000D+04/
      data y_data(    43,   3) /  0.551639400000D-05/
      data y_data(    43,   4) /  0.297575200000D-14/
      data y_data(    43,   5) /  0.419308100000D-24/
      data y_data(    43,   6) /  0.210000000000D+00/
      data y_data(    43,   7) /  0.576189600000D-15/
      data y_data(    43,   8) /  0.441800100000D-16/
      data y_data(    43,   9) /  0.221086100000D-17/
      data y_data(    43,  10) /  0.828650900000D-27/
      data y_data(    43,  11) /  0.745585200000D-22/
      data y_data(    43,  12) /  0.790000000000D+00/
      data x_data(    44     ) /  0.401141700000D+01/
      data y_data(    44,   1) /  0.494894000000D+00/
      data y_data(    44,   2) /  0.100000000000D+04/
      data y_data(    44,   3) /  0.541337900000D-05/
      data y_data(    44,   4) /  0.304941800000D-15/
      data y_data(    44,   5) /  0.417620900000D-25/
      data y_data(    44,   6) /  0.210000000000D+00/
      data y_data(    44,   7) /  0.576009300000D-15/
      data y_data(    44,   8) /  0.440134400000D-17/
      data y_data(    44,   9) /  0.218902600000D-18/
      data y_data(    44,  10) /  0.822525300000D-29/
      data y_data(    44,  11) /  0.848837300000D-24/
      data y_data(    44,  12) /  0.790000000000D+00/
      data x_data(    45     ) /  0.418227000000D+01/
      data y_data(    45,   1) /  0.564081100000D+00/
      data y_data(    45,   2) /  0.100000000000D+04/
      data y_data(    45,   3) /  0.540268800000D-05/
      data y_data(    45,   4) /  0.275689000000D-16/
      data y_data(    45,   5) /  0.324445400000D-26/
      data y_data(    45,   6) /  0.210000000000D+00/
      data y_data(    45,   7) /  0.575991200000D-15/
      data y_data(    45,   8) /  0.342328600000D-18/
      data y_data(    45,   9) /  0.164201600000D-19/
      data y_data(    45,  10) /  0.498875600000D-31/
      data y_data(    45,  11) /  0.926590800000D-26/
      data y_data(    45,  12) /  0.790000000000D+00/
      data x_data(    46     ) /  0.435316000000D+01/
      data y_data(    46,   1) /  0.639173200000D+00/
      data y_data(    46,   2) /  0.100000000000D+04/
      data y_data(    46,   3) /  0.540170500000D-05/
      data y_data(    46,   4) /  0.193761600000D-17/
      data y_data(    46,   5) /  0.181279100000D-27/
      data y_data(    46,   6) /  0.210000000000D+00/
      data y_data(    46,   7) /  0.575989900000D-15/
      data y_data(    46,   8) /  0.186238500000D-19/
      data y_data(    46,   9) /  0.857414000000D-21/
      data y_data(    46,  10) /  0.148779500000D-33/
      data y_data(    46,  11) /  0.952239800000D-28/
      data y_data(    46,  12) /  0.790000000000D+00/
      data x_data(    47     ) /  0.452408100000D+01/
      data y_data(    47,   1) /  0.720412100000D+00/
      data y_data(    47,   2) /  0.100000000000D+04/
      data y_data(    47,   3) /  0.540163500000D-05/
      data y_data(    47,   4) /  0.104121200000D-18/
      data y_data(    47,   5) /  0.791356900000D-29/
      data y_data(    47,   6) /  0.210000000000D+00/
      data y_data(    47,   7) /  0.575989800000D-15/
      data y_data(    47,   8) /  0.762111400000D-21/
      data y_data(    47,   9) /  0.344769000000D-22/
      data y_data(    47,  10) /  0.252163000000D-36/
      data y_data(    47,  11) /  0.906732500000D-30/
      data y_data(    47,  12) /  0.790000000000D+00/
      data x_data(    48     ) /  0.469502700000D+01/
      data y_data(    48,   1) /  0.808039600000D+00/
      data y_data(    48,   2) /  0.100000000000D+04/
      data y_data(    48,   3) /  0.540163200000D-05/
      data y_data(    48,   4) /  0.442653300000D-20/
      data y_data(    48,   5) /  0.287684000000D-30/
      data y_data(    48,   6) /  0.210000000000D+00/
      data y_data(    48,   7) /  0.575989900000D-15/
      data y_data(    48,   8) /  0.254742800000D-22/
      data y_data(    48,   9) /  0.115641000000D-23/
      data y_data(    48,  10) /  0.285832200000D-39/
      data y_data(    48,  11) /  0.786276600000D-32/
      data y_data(    48,  12) /  0.790000000000D+00/
      data x_data(    49     ) /  0.486599700000D+01/
      data y_data(    49,   1) /  0.902297800000D+00/
      data y_data(    49,   2) /  0.100000000000D+04/
      data y_data(    49,   3) /  0.540163100000D-05/
      data y_data(    49,   4) /  0.162243700000D-21/
      data y_data(    49,   5) /  0.920764400000D-32/
      data y_data(    49,   6) /  0.210000000000D+00/
      data y_data(    49,   7) /  0.575989900000D-15/
      data y_data(    49,   8) /  0.758211300000D-24/
      data y_data(    49,   9) /  0.339036400000D-25/
      data y_data(    49,  10) /  0.256374100000D-42/
      data y_data(    49,  11) /  0.628959500000D-34/
      data y_data(    49,  12) /  0.790000000000D+00/
      data x_data(    50     ) /  0.503137900000D+01/
      data y_data(    50,   1) /  0.100000000000D+01/
      data y_data(    50,   2) /  0.100000000000D+04/
      data y_data(    50,   3) /  0.540163100000D-05/
      data y_data(    50,   4) /  0.162243700000D-21/
      data y_data(    50,   5) /  0.920764400000D-32/
      data y_data(    50,   6) /  0.210000000000D+00/
      data y_data(    50,   7) /  0.575989900000D-15/
      data y_data(    50,   8) /  0.758211300000D-24/
      data y_data(    50,   9) /  0.339036400000D-25/
      data y_data(    50,  10) /  0.256374100000D-42/
      data y_data(    50,  11) /  0.628959500000D-34/
      data y_data(    50,  12) /  0.790000000000D+00/
c                                                 
c     interpolation routine                       
c                                                 
      lo_loside = 0
      lo_hiside = 0
      hi_loside = 0
      hi_hiside = 0
      if (xlo .le. x_data(1)) then
         lo_loside = 1
         lo_hiside = 1
      end if
      if (xhi .le. x_data(1)) then
         hi_loside = 1
         hi_hiside = 1
      end if
      if (xlo .ge. x_data(N)) then
         lo_loside = N
         lo_hiside = N
      end if
      if (xhi .ge. x_data(N)) then
         hi_loside = N
         hi_hiside = N
      end if
      if (lo_loside.eq.0) then
         do i = 1, N-1                           
            if ( (xlo .ge. x_data(i))
     &           .and.
     &           (xlo .le. x_data(i+1)) ) then
               lo_loside  = i
               lo_hiside  = i+1
            end if
         end do
      end if
      if (hi_loside.eq.0) then            
         do i = 1, N-1                           
            if ( (xhi .ge. x_data(i))
     &           .and.
     &           (xhi .le. x_data(i+1)) ) then
               hi_loside = i
               hi_hiside = i + 1
            end if
         end do
      end if
         
      do j = 1, M
         
         x1 = x_data(lo_loside)
         y1 = y_data(lo_loside,j)
         
         x2 = x_data(lo_hiside)
         y2 = y_data(lo_hiside,j)
          
         if (lo_loside.eq.lo_hiside) then
            dydx = 0.d0
         else
            dydx = (y2-y1)/(x2-x1)
         end if
         
         ylo = y1 + dydx*(xlo - x1)
         
         if (lo_loside .eq. hi_loside) then
            
            yhi = y1 + dydx*(xhi - x1)
            
            y_vector(j) = 0.5d0*(ylo + yhi)
            
         else
            
            sum = (x2 - xlo) * 0.5d0 * (ylo + y2)
            
            x1 = x_data(hi_loside)
            y1 = y_data(hi_loside,j)
         
            x2 = x_data(hi_hiside)
            y2 = y_data(hi_hiside,j)
            
            if (hi_loside.eq.hi_hiside) then
               dydx = 0.d0
            else
               dydx = (y2-y1)/(x2-x1)
            end if
            
            yhi = y1 + dydx*(xhi - x1)
            
            sum = sum + (xhi - x1)*0.5d0*(yhi+y1)
            
            do k = lo_hiside,hi_loside-1
               
               sum = sum + (x_data(k+1)-x_data(k))
     &              * 0.5d0
     &              * (y_data(k,j) + y_data(k+1,j))
               
            end do
            
            y_vector(j) = sum / (xhi - xlo)
            
         end if
      end do
      end                                         
c     LAST LINE                                   
c-------------------------------------------------
